'use server';

import { after } from 'next/server';
import { adminDb } from './firebase-admin';
import type { Activity, EntityType } from './types';
import { triggerAutomationProtocols } from './automation-processor';
import { resolveContact } from './contact-adapter';
import { buildAutomationPayload } from './automation-payload';
import { resolveAutomationTrigger } from './automation-trigger-map';

// Cache for organization logging status to prevent Firestore read flooding
const orgLoggingDisabledCache = new Map<string, { disabled: boolean; timestamp: number }>();
const CACHE_TTL_MS = 60 * 1000; // 60s cache

export async function invalidateOrgLoggingCache(orgId: string): Promise<void> {
    orgLoggingDisabledCache.delete(orgId);
}

async function isLoggingDisabledForOrg(orgId: string): Promise<boolean> {
    if (!orgId) return false;
    const cached = orgLoggingDisabledCache.get(orgId);
    if (cached && (Date.now() - cached.timestamp < CACHE_TTL_MS)) {
        return cached.disabled;
    }
    try {
        const orgSnap = await adminDb.collection('organizations').doc(orgId).get();
        if (!orgSnap.exists) return false;
        const data = orgSnap.data();
        const isDisabled = data?.activityLoggingDisabled === true || data?.activityLoggingEnabled === false;
        orgLoggingDisabledCache.set(orgId, { disabled: isDisabled, timestamp: Date.now() });
        return isDisabled;
    } catch (err) {
        console.error(`[ACTIVITY] Failed to fetch organization config for ${orgId}:`, err);
        return false;
    }
}

type LogActivityInput = Omit<Activity, 'id' | 'timestamp'>;

/**
 * Logs an activity using the Firebase Admin SDK for reliability.
 * Upgraded to serve as the platform's primary Event Bus for the Automation Engine.
 * 
 * Updated to use the Contact Adapter Layer for backward compatibility (Requirement 18)
 * Updated for workspace awareness (Requirement 12)
 * Updated to fully support entity architecture.
 * Updated with Vercel Best Practices: Non-blocking automation triggers via after().
 */
export async function logActivity(activityData: LogActivityInput): Promise<void> {
    const runAfter = (fn: () => void | Promise<void>) => {
        try {
            after(fn);
        } catch {
            // Fallback: run asynchronously outside Next.js request scope (e.g. in tests)
            Promise.resolve().then(fn).catch(err => {
                console.error("runAfter fallback execution failed:", err);
            });
        }
    };

    try {
        let finalData = { ...activityData };
        
        let entityId: string | null | undefined = activityData.entityId;
        let entityName: string | null | undefined = activityData.entityName;
        let entitySlug: string | null | undefined = activityData.entitySlug;
        let entityType: EntityType | null | undefined = activityData.entityType as EntityType;
        let displayName: string | null | undefined = activityData.displayName;
        
        // Resolution logic
        if (activityData.workspaceId) {
            if (entityId) {
                const contact = await resolveContact(entityId, activityData.workspaceId);
                if (contact) {
                    entityName = contact.name || entityName;
                    entitySlug = contact.slug || entitySlug;
                    displayName = contact.name || displayName;
                    
                    entityId = contact.entityId || entityId;
                    entityType = contact.entityType || entityType;
                }
            }
        }
        
        // Update finalData with resolved fields
        finalData = {
            ...finalData,
            entityId: entityId || undefined,
            entityName: entityName || undefined,
            entitySlug: entitySlug || undefined,
            entityType: entityType || undefined,
            displayName: displayName || undefined,
        };

        // Check if logging is disabled for this organization
        const isLoggingDisabled = await isLoggingDisabledForOrg(activityData.organizationId);
        let docRefId: string | undefined = undefined;

        if (!isLoggingDisabled) {
            // 3. Persist the Audit Log with all workspace-aware fields (Requirement 12)
            const docRef = await adminDb.collection('activities').add({
                ...finalData,
                timestamp: new Date().toISOString(),
            });
            docRefId = docRef.id;
        } else {
            console.log(`[ACTIVITY] Bypassing log persistence for org: ${activityData.organizationId}`);
        }

        // 4. BROADCAST TO AUTOMATION ENGINE
        // Guard: skip if this is a retry OR if the activity was itself generated by an automation
        // step (e.g. handleAddNote / handleUpdateEntity) — prevents infinite trigger loops.
        const triggerType = resolveAutomationTrigger(activityData.type);
        if (triggerType && !activityData.metadata?.isRetry && !activityData.metadata?.isAutomation) {
            console.log(`>>> [EVENT:BUS] Signal detected: ${triggerType}. Scheduling Logic Processor.`);

            const payload = buildAutomationPayload({
                organizationId: activityData.organizationId,
                workspaceId: activityData.workspaceId,
                entityId: finalData.entityId,
                entityType: finalData.entityType,
                action: activityData.type,
                actorId: activityData.userId ?? null,
                metadata: activityData.metadata,
                activityId: docRefId ?? '',
                entityName: finalData.entityName,
                entitySlug: finalData.entitySlug,
                displayName: finalData.displayName,
            });

            // non-blocking automation triggers via runAfter
            runAfter(async () => {
                try {
                    await triggerAutomationProtocols(triggerType, payload);
                } catch (err: any) {
                    console.error(`>>> [EVENT:BUS] Protocol trigger failed:`, err.message);
                }
            });
        }
        
        // Recalculate score asynchronously on any logged activity
        if (finalData.entityId && finalData.workspaceId && finalData.organizationId) {
            runAfter(async () => {
                try {
                    const { recalculateEntityScore } = await import('./scoring-engine');
                    await recalculateEntityScore(finalData.entityId!, finalData.workspaceId!, finalData.organizationId!);
                } catch (err: unknown) {
                    const errorMsg = err instanceof Error ? err.message : 'Unknown recalculation error';
                    console.error(`>>> [Scoring Engine] Recalculation failed on activity log:`, errorMsg);
                }

                // CENTRAL SCORING & PERFORMANCE ENGINE INTEGRATION:
                // Offload event evaluation to emitScoringEvent (runs after request matches)
                if (!activityData.metadata?.isAutomation && !activityData.metadata?.isRetry) {
                    try {
                        const { emitScoringEvent } = await import('./scoring-performance-engine');
                        
                        // Resolve target contact email or ID from metadata or fallback
                        const contactEmailOrId = 
                            activityData.metadata?.contactId || 
                            activityData.metadata?.contactEmail || 
                            activityData.metadata?.email || 
                            activityData.metadata?.recipientEmail;
                            
                        const actorType = activityData.metadata?.isAutomation 
                            ? 'Automation' 
                            : activityData.source === 'system' 
                            ? 'System' 
                            : 'User';

                        await emitScoringEvent({
                            organizationId: finalData.organizationId!,
                            workspaceId: finalData.workspaceId!,
                            eventType: activityData.type,
                            entityType: finalData.entityType || 'Contact',
                            entityId: finalData.entityId!,
                            contactId: contactEmailOrId ? String(contactEmailOrId) : undefined,
                            actorType,
                            actorId: activityData.userId || 'system-scoring-engine',
                            metadata: {
                                ...(activityData.metadata || {}),
                                activityId: docRefId
                            }
                        });
                    } catch (err: unknown) {
                        const errorMsg = err instanceof Error ? err.message : 'Unknown routing failure';
                        console.error(`>>> [Scoring Engine] Scoring Performance Engine dispatch failed:`, errorMsg);
                    }
                }
            });
        }

    } catch (error) {
        console.error("ActivityLogger: Failed to log activity.", error);
    }
}
