'use server';

import { after } from 'next/server';
import { adminDb } from './firebase-admin';
import type { Activity, EntityType } from './types';
import { triggerAutomationProtocols } from './automation-processor';
import { resolveContact } from './contact-adapter';
import { buildAutomationPayload } from './automation-payload';
import { resolveAutomationTrigger } from './automation-trigger-map';

type LogActivityInput = Omit<Activity, 'id' | 'timestamp'>;

/**
 * Logs an activity using the Firebase Admin SDK for reliability.
 * Upgraded to serve as the platform's primary Event Bus for the Automation Engine.
 * 
 * Updated to use the Contact Adapter Layer for backward compatibility (Requirement 18)
 * Updated for workspace awareness (Requirement 12)
 * Updated to fully support entity architecture.
 * Updated with Vercel Best Practices: Non-blocking automation triggers via after().
 */
export async function logActivity(activityData: LogActivityInput): Promise<void> {
    const runAfter = (fn: () => void | Promise<void>) => {
        try {
            after(fn);
        } catch {
            // Fallback: run asynchronously outside Next.js request scope (e.g. in tests)
            Promise.resolve().then(fn).catch(err => {
                console.error("runAfter fallback execution failed:", err);
            });
        }
    };

    try {
        let finalData = { ...activityData };
        
        let entityId: string | null | undefined = activityData.entityId;
        let entityName: string | null | undefined = activityData.entityName;
        let entitySlug: string | null | undefined = activityData.entitySlug;
        let entityType: EntityType | null | undefined = activityData.entityType as EntityType;
        let displayName: string | null | undefined = activityData.displayName;
        
        // Resolution logic
        if (activityData.workspaceId) {
            if (entityId) {
                const contact = await resolveContact(entityId, activityData.workspaceId);
                if (contact) {
                    entityName = contact.name || entityName;
                    entitySlug = contact.slug || entitySlug;
                    displayName = contact.name || displayName;
                    
                    if (contact.migrationStatus === 'migrated' || contact.migrationStatus === 'dual-write') {
                        entityId = contact.entityId;
                        entityType = contact.entityType || entityType;
                    } else {
                        entityId = undefined;
                        entityType = undefined;
                    }
                }
            }
        }
        
        // Update finalData with resolved fields
        finalData = {
            ...finalData,
            entityId: entityId || undefined,
            entityName: entityName || undefined,
            entitySlug: entitySlug || undefined,
            entityType: entityType || undefined,
            displayName: displayName || undefined,
        };

        // 3. Persist the Audit Log with all workspace-aware fields (Requirement 12)
        const docRef = await adminDb.collection('activities').add({
            ...finalData,
            timestamp: new Date().toISOString(),
        });

        // 4. BROADCAST TO AUTOMATION ENGINE
        // Guard: skip if this is a retry OR if the activity was itself generated by an automation
        // step (e.g. handleAddNote / handleUpdateEntity) — prevents infinite trigger loops.
        const triggerType = resolveAutomationTrigger(activityData.type);
        if (triggerType && !activityData.metadata?.isRetry && !activityData.metadata?.isAutomation) {
            console.log(`>>> [EVENT:BUS] Signal detected: ${triggerType}. Scheduling Logic Processor.`);

            const payload = buildAutomationPayload({
                organizationId: activityData.organizationId,
                workspaceId: activityData.workspaceId,
                entityId: finalData.entityId,
                entityType: finalData.entityType,
                action: activityData.type,
                actorId: activityData.userId ?? null,
                metadata: activityData.metadata,
                activityId: docRef.id,
                entityName: finalData.entityName,
                entitySlug: finalData.entitySlug,
                displayName: finalData.displayName,
            });

            // non-blocking automation triggers via runAfter
            runAfter(async () => {
                try {
                    await triggerAutomationProtocols(triggerType, payload);
                } catch (err: any) {
                    console.error(`>>> [EVENT:BUS] Protocol trigger failed:`, err.message);
                }
            });
        }
        
        // Recalculate score asynchronously on any logged activity
        if (finalData.entityId && finalData.workspaceId && finalData.organizationId) {
            runAfter(async () => {
                try {
                    const { recalculateEntityScore } = await import('./scoring-engine');
                    await recalculateEntityScore(finalData.entityId!, finalData.workspaceId!, finalData.organizationId!);
                } catch (err: any) {
                    console.error(`>>> [Scoring Engine] Recalculation failed on activity log:`, err.message);
                }

                // LEAD SCORING INTEGRATION:
                // Check if this activity triggers global engagement scoring.
                // Guard: Skip if this event was itself created by automation to avoid loops.
                if (!activityData.metadata?.isAutomation && !activityData.metadata?.isRetry) {
                    try {
                        const wsSnap = await adminDb.collection('workspaces').doc(finalData.workspaceId!).get();
                        const wsData = wsSnap.data();
                        const rules = wsData?.leadScoringSettings?.engagementRules;
                        const increment = rules ? rules[activityData.type] : undefined;

                        if (increment && increment !== 0) {
                            const entityRef = adminDb.collection('entities').doc(finalData.entityId!);
                            await adminDb.runTransaction(async (transaction) => {
                                const entitySnap = await transaction.get(entityRef);
                                if (entitySnap.exists) {
                                    const entityData = entitySnap.data() || {};
                                    const entityContacts = entityData.entityContacts || [];

                                    // Resolve target contact email or ID from metadata or fallback
                                    const contactEmailOrId = 
                                        activityData.metadata?.contactId || 
                                        activityData.metadata?.contactEmail || 
                                        activityData.metadata?.email || 
                                        activityData.metadata?.recipientEmail;

                                    const { calculateEngagementAdjustment } = await import('./scoring-rules-engine');
                                    const { entityContacts: updatedContacts, leadScore } = calculateEngagementAdjustment(
                                        entityContacts,
                                        contactEmailOrId ? String(contactEmailOrId) : undefined,
                                        Math.abs(increment),
                                        increment < 0 ? 'subtract' : 'add'
                                    );

                                    transaction.update(entityRef, {
                                        entityContacts: updatedContacts,
                                        leadScore,
                                        updatedAt: new Date().toISOString()
                                    });

                                    // Also update workspace entity
                                    const weSnap = await adminDb.collection('workspace_entities')
                                        .where('entityId', '==', finalData.entityId)
                                        .where('workspaceId', '==', finalData.workspaceId)
                                        .limit(1)
                                        .get();

                                    if (!weSnap.empty) {
                                        transaction.update(weSnap.docs[0].ref, {
                                            entityContacts: updatedContacts,
                                            leadScore,
                                            updatedAt: new Date().toISOString()
                                        });
                                    }
                                }
                            });

                            // Log a system activity event for the score change (marked isAutomation: true to prevent loops)
                            const opLabel = increment > 0 ? `increased by ${increment}` : `decreased by ${Math.abs(increment)}`;
                            await logActivity({
                                type: 'lead_score_updated',
                                description: `Lead score ${opLabel} for contact due to engagement: "${activityData.type}"`,
                                source: 'system',
                                organizationId: finalData.organizationId!,
                                workspaceId: finalData.workspaceId!,
                                entityId: finalData.entityId!,
                                userId: 'system-scoring-engine',
                                displayName: 'System Core',
                                metadata: {
                                    isAutomation: true,
                                    activityTriggerType: activityData.type,
                                    incrementValue: increment
                                }
                            });
                        }
                    } catch (err: any) {
                        console.error(`>>> [Scoring Engine] Global engagement scoring failed:`, err.message);
                    }
                }
            });
        }

    } catch (error) {
        console.error("ActivityLogger: Failed to log activity.", error);
    }
}
