import type { MessagingTrigger, MessageChannel } from './types';

export const MESSAGING_TRIGGERS: MessagingTrigger[] = [
  // ── Meetings: Invitations ────────────────────────────────────────────────
  {
    id: 'meeting_resend_join_link',
    name: 'Resend Join Link',
    description: 'Resend meeting registration details and personalized join link.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_invitation_initial',
    name: 'Initial Invitation',
    description: 'Initial invitation sent to pending records.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_invitation_1_month',
    name: 'Invitation (1 Month Before)',
    description: 'Invitation followup sent 1 month before meeting.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_invitation_1_week',
    name: 'Invitation (1 Week Before)',
    description: 'Invitation followup sent 1 week before meeting.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_invitation_5_days',
    name: 'Invitation (5 Days Before)',
    description: 'Invitation followup sent 5 days before meeting.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_invitation_3_days',
    name: 'Invitation (3 Days Before)',
    description: 'Invitation followup sent 3 days before meeting.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_invitation_2_days',
    name: 'Invitation (2 Days Before)',
    description: 'Invitation followup sent 2 days before meeting.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_invitation_1_day',
    name: 'Invitation (1 Day Before)',
    description: 'Invitation followup sent 1 day before meeting.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_invitation_today',
    name: 'Invitation (Today at 8 AM)',
    description: 'Invitation followup sent today at 8 AM.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_invitation_last_chance',
    name: 'Invitation (Last Chance)',
    description: 'Urgent final invitation followup sent before meeting.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },

  // ── Meetings: Core ────────────────────────────────────────────────────────
  {
    id: 'meeting_registration_ack',
    name: 'Registration Acknowledgement',
    description: 'Sent to a user when they successfully register for a meeting.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_facilitator_new_registration',
    name: 'Facilitator: New Registration Alert',
    description: 'Alerts the facilitator when a new user registers for their meeting.',
    category: 'meetings',
    target: 'internal_team',
    recipientType: 'internal_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_reminder_2days',
    name: 'Meeting Reminder (2 Days)',
    description: 'Reminder sent 2 days before the meeting begins.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_reminder_1day',
    name: 'Meeting Reminder (1 Day)',
    description: 'Reminder sent 1 day before the meeting begins.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_reminder_1hour',
    name: 'Meeting Reminder (1 Hour)',
    description: 'Reminder sent 1 hour before the meeting begins.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_reminder_15min',
    name: 'Meeting Reminder (15 Minutes)',
    description: 'Reminder sent 15 minutes before the meeting begins.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_time_up',
    name: 'Meeting Starting Now',
    description: 'Sent exactly when the meeting is scheduled to start.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_post_event_thankyou',
    name: 'Post-Event Thank You',
    description: 'Sent to attendees after the meeting concludes.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_post_event_absentee',
    name: 'Absentee Follow-Up',
    description: 'Sent to registrants who did not attend the meeting.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_facilitator_pre_event',
    name: 'Facilitator: Pre-Event Briefing',
    description: 'Briefing sent to the facilitator before the meeting starts.',
    category: 'meetings',
    target: 'internal_team',
    recipientType: 'internal_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_facilitator_post_event',
    name: 'Facilitator: Post-Event Debrief',
    description: 'Debrief sent to the facilitator after the meeting concludes.',
    category: 'meetings',
    target: 'internal_team',
    recipientType: 'internal_alert',
    supportedChannels: ['email', 'sms'],
  },

  // ── Forms ─────────────────────────────────────────────────────────────────
  {
    id: 'form_invitation',
    name: 'Form Invitation',
    description: 'Invite users to fill out a specific form.',
    category: 'forms',
    target: 'external_client',
    recipientType: 'respondent',
    supportedChannels: ['email', 'sms', 'push'],
  },
  {
    id: 'submission_confirmation',
    name: 'Form Submission Confirmation',
    description: 'Sent to acknowledge a successful form submission.',
    category: 'forms',
    target: 'external_client',
    recipientType: 'respondent',
    supportedChannels: ['email', 'in_app'],
  },
  {
    id: 'submission_reminder',
    name: 'Form Submission Reminder',
    description: 'Remind users to complete a pending form.',
    category: 'forms',
    target: 'external_client',
    recipientType: 'respondent',
    supportedChannels: ['email', 'sms'],
  },

  // ── Surveys ───────────────────────────────────────────────────────────────
  {
    id: 'survey_invitation',
    name: 'Survey Invitation',
    description: 'Invite users to participate in a survey.',
    category: 'surveys',
    target: 'external_client',
    recipientType: 'respondent',
    supportedChannels: ['email', 'sms', 'push'],
  },
  {
    id: 'survey_completion',
    name: 'Survey Completion',
    description: 'Sent when a user finishes a survey.',
    category: 'surveys',
    target: 'external_client',
    recipientType: 'respondent',
    supportedChannels: ['email', 'in_app'],
  },
  {
    id: 'survey_reminder',
    name: 'Survey Reminder',
    description: 'Remind users to finish a pending survey.',
    category: 'surveys',
    target: 'external_client',
    recipientType: 'respondent',
    supportedChannels: ['email', 'sms'],
  },

  // ── Agreements ────────────────────────────────────────────────────────────
  {
    id: 'contract_sent',
    name: 'Contract Sent',
    description: 'Sent when a new agreement requires a signature.',
    category: 'agreements',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email'],
  },
  {
    id: 'contract_signed',
    name: 'Contract Signed',
    description: 'Confirmation that the agreement was successfully signed.',
    category: 'agreements',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email'],
  },
  {
    id: 'contract_pending',
    name: 'Contract Pending',
    description: 'Remind the signatory that an agreement is awaiting signature.',
    category: 'agreements',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'contract_reminder',
    name: 'Contract Deadline Reminder',
    description: 'Urgent reminder before an agreement deadline expires.',
    category: 'agreements',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },

  // ── General / Entities ────────────────────────────────────────────────────
  {
    id: 'welcome_message',
    name: 'Welcome Message',
    description: 'Sent when a new user joins a workspace.',
    category: 'general',
    target: 'external_client',
    recipientType: 'entity',
    supportedChannels: ['email'],
  },
  {
    id: 'stage_change',
    name: 'Stage Change Alert',
    description: 'Alert sent when an entity moves to a new stage.',
    category: 'general',
    target: 'external_client',
    recipientType: 'entity',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'assignment_notification',
    name: 'Assignment Notification',
    description: 'Sent when an entity is assigned to a team member.',
    category: 'general',
    target: 'internal_team',
    recipientType: 'entity',
    supportedChannels: ['email'],
  },
  {
    id: 'status_update',
    name: 'Status Update',
    description: 'Sent when an entity\'s overall status changes.',
    category: 'general',
    target: 'external_client',
    recipientType: 'entity',
    supportedChannels: ['email', 'sms'],
  },

  // ── Tasks ─────────────────────────────────────────────────────────────────
  {
    id: 'task_assigned',
    name: 'Task Assigned',
    description: 'Notifies an assignee of a newly assigned task.',
    category: 'tasks',
    target: 'internal_team',
    recipientType: 'assignee',
    supportedChannels: ['email', 'in_app', 'push'],
  },
  {
    id: 'task_reminder_1day',
    name: 'Task Reminder (1 Day)',
    description: 'Reminds an assignee of a task due tomorrow.',
    category: 'tasks',
    target: 'internal_team',
    recipientType: 'assignee',
    supportedChannels: ['email'],
  },
  {
    id: 'task_overdue',
    name: 'Task Overdue',
    description: 'Alerts an assignee that a task is past its due date.',
    category: 'tasks',
    target: 'internal_team',
    recipientType: 'assignee',
    supportedChannels: ['email'],
  },
  {
    id: 'task_completed',
    name: 'Task Completed',
    description: 'Sent to relevant parties when a task is marked as done.',
    category: 'tasks',
    target: 'internal_team',
    recipientType: 'internal_alert',
    supportedChannels: ['email'],
  },

  // ── Automations ───────────────────────────────────────────────────────────
  {
    id: 'automation_failed',
    name: 'Automation Failed',
    description: 'Alerts admins when an automated workflow fails.',
    category: 'automations',
    target: 'internal_team',
    recipientType: 'internal_alert',
    supportedChannels: ['email', 'push'],
  },
  {
    id: 'automation_completed',
    name: 'Automation Completed',
    description: 'Logs or notifies when a workflow successfully finishes.',
    category: 'automations',
    target: 'internal_team',
    recipientType: 'internal_alert',
    supportedChannels: ['in_app'],
  },

  // ── QR Codes ──────────────────────────────────────────────────────────────
  {
    id: 'qr_scan_alert',
    name: 'QR Code Scan Alert',
    description: 'Alerts the owner when their QR code is scanned.',
    category: 'qr_codes',
    target: 'internal_team',
    recipientType: 'internal_alert',
    supportedChannels: ['email', 'push'],
  },

  // ── Users ─────────────────────────────────────────────────────────────────
  {
    id: 'user_invitation',
    name: 'User Invitation',
    description: 'Sent to a new team member when they are invited to join.',
    category: 'users',
    target: 'internal_team',
    recipientType: 'internal_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'user_password_reset',
    name: 'User Password Reset',
    description: 'Sent when an administrator resets a user\'s password.',
    category: 'users',
    target: 'internal_team',
    recipientType: 'internal_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'user_access_cancellation',
    name: 'Access Cancellation',
    description: 'Sent when a user\'s access to the workspace is revoked.',
    category: 'users',
    target: 'internal_team',
    recipientType: 'internal_alert',
    supportedChannels: ['email', 'sms'],
  },
  // ── Meetings: Reschedule & Cancellation ──
  {
    id: 'meeting_rescheduled_guest',
    name: 'Meeting Rescheduled (Guests)',
    description: 'Sent to guests on the roster when a meeting is rescheduled.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_rescheduled_registrant',
    name: 'Meeting Rescheduled (Registrants)',
    description: 'Sent to registrants on the schedule when a meeting is rescheduled.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_rescheduled_facilitator',
    name: 'Meeting Rescheduled (Facilitator)',
    description: 'Sent to facilitators when a meeting is rescheduled.',
    category: 'meetings',
    target: 'internal_team',
    recipientType: 'internal_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_cancelled_guest',
    name: 'Meeting Cancelled (Guests)',
    description: 'Sent to guests on the roster when a meeting is cancelled.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_cancelled_registrant',
    name: 'Meeting Cancelled (Registrants)',
    description: 'Sent to registrants on the schedule when a meeting is cancelled.',
    category: 'meetings',
    target: 'external_client',
    recipientType: 'external_alert',
    supportedChannels: ['email', 'sms'],
  },
  {
    id: 'meeting_cancelled_facilitator',
    name: 'Meeting Cancelled (Facilitator)',
    description: 'Sent to facilitators when a meeting is cancelled.',
    category: 'meetings',
    target: 'internal_team',
    recipientType: 'internal_alert',
    supportedChannels: ['email', 'sms'],
  },
];
