// Poster template definitions for the QR Canvas Designer

export interface PosterTemplate {
  id: string;
  name: string;
  category: 'social' | 'business' | 'restaurant' | 'utility' | 'academic' | 'event' | 'custom';
  description: string;
  canvasWidth: number;
  canvasHeight: number;
  backgroundColor: string;
  elements: PosterElement[];
  scope: 'system' | 'workspace';
}

export interface PosterElement {
  type: 'text' | 'qr' | 'rect' | 'circle' | 'image' | 'line';
  id: string;
  x: number; // percentage 0-100
  y: number; // percentage 0-100
  width: number; // percentage
  height: number; // percentage
  // Text props
  text?: string;
  fontSize?: number;
  fontFamily?: string;
  fontWeight?: string;
  fontStyle?: string;
  fill?: string;
  textAlign?: string;
  // Shape props
  shapeFill?: string;
  shapeStroke?: string;
  shapeStrokeWidth?: number;
  borderRadius?: number;
  opacity?: number;
  // Line props
  lineColor?: string;
  lineWidth?: number;
  // QR-specific
  isQR?: boolean;
}

// ─────────────────────────────────────────────────
// System Seed Templates
// ─────────────────────────────────────────────────

export const SYSTEM_POSTER_TEMPLATES: PosterTemplate[] = [
  // Template 1: Social Media Follow (Clean White)
  {
    id: 'tpl-social-follow',
    name: 'Social Media Follow',
    category: 'social',
    description: 'Clean white poster for social media promotion',
    canvasWidth: 600,
    canvasHeight: 800,
    backgroundColor: '#FFFFFF',
    scope: 'system',
    elements: [
      {
        type: 'text',
        id: 'heading-1',
        x: 10,
        y: 5,
        width: 80,
        height: 6,
        text: 'SCAN TO FOLLOW US ON',
        fontSize: 18,
        fontFamily: 'Inter',
        fontWeight: '400',
        fill: '#1a1a1a',
        textAlign: 'center',
      },
      {
        type: 'text',
        id: 'heading-2',
        x: 10,
        y: 11,
        width: 80,
        height: 10,
        text: 'social media',
        fontSize: 42,
        fontFamily: 'Georgia',
        fontWeight: '400',
        fontStyle: 'italic',
        fill: '#1a1a1a',
        textAlign: 'center',
      },
      {
        type: 'qr',
        id: 'qr-code',
        x: 20,
        y: 24,
        width: 60,
        height: 45,
        isQR: true,
      },
      {
        type: 'text',
        id: 'cta',
        x: 10,
        y: 72,
        width: 80,
        height: 5,
        text: 'FOLLOW  |  LIKE  |  TAG',
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: '700',
        fill: '#1a1a1a',
        textAlign: 'center',
      },
      {
        type: 'text',
        id: 'handle',
        x: 10,
        y: 79,
        width: 80,
        height: 5,
        text: '@yourbrandname',
        fontSize: 18,
        fontFamily: 'Georgia',
        fontWeight: '400',
        fontStyle: 'italic',
        fill: '#555555',
        textAlign: 'center',
      },
      {
        type: 'rect',
        id: 'divider',
        x: 30,
        y: 86,
        width: 40,
        height: 0.3,
        shapeFill: '#e0e0e0',
      },
      {
        type: 'text',
        id: 'footer',
        x: 10,
        y: 90,
        width: 80,
        height: 5,
        text: 'Connect with us on all platforms',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: '400',
        fill: '#999999',
        textAlign: 'center',
      },
    ],
  },

  // Template 2: Appointment Booking (Minimalist)
  {
    id: 'tpl-appointment',
    name: 'Appointment Booking',
    category: 'business',
    description: 'Minimalist card for booking appointments',
    canvasWidth: 500,
    canvasHeight: 700,
    backgroundColor: '#FAF5F0',
    scope: 'system',
    elements: [
      {
        type: 'rect',
        id: 'accent-shape',
        x: 60,
        y: -5,
        width: 50,
        height: 35,
        shapeFill: '#E8B4B8',
        opacity: 0.4,
        borderRadius: 100,
      },
      {
        type: 'text',
        id: 'brand',
        x: 10,
        y: 8,
        width: 80,
        height: 8,
        text: '✦ YOUR BRAND',
        fontSize: 22,
        fontFamily: 'Inter',
        fontWeight: '800',
        fill: '#2D4A3E',
        textAlign: 'center',
      },
      {
        type: 'text',
        id: 'heading',
        x: 5,
        y: 22,
        width: 90,
        height: 12,
        text: 'TO BOOK ONLINE\nAPPOINTMENT',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: '700',
        fill: '#2D4A3E',
        textAlign: 'center',
      },
      {
        type: 'text',
        id: 'subheading',
        x: 5,
        y: 34,
        width: 90,
        height: 5,
        text: 'SCAN THE QR CODE',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#6B8F7B',
        textAlign: 'center',
      },
      {
        type: 'qr',
        id: 'qr-code',
        x: 15,
        y: 42,
        width: 70,
        height: 50,
        isQR: true,
      },
      {
        type: 'text',
        id: 'footer',
        x: 10,
        y: 93,
        width: 80,
        height: 4,
        text: 'www.yourbrand.com',
        fontSize: 11,
        fontFamily: 'Inter',
        fontWeight: '500',
        fill: '#999999',
        textAlign: 'center',
      },
    ],
  },

  // Template 3: Menu Access (Bold Teal)
  {
    id: 'tpl-menu-access',
    name: 'Dining & Menu Access',
    category: 'restaurant',
    description: 'Bold restaurant menu access poster',
    canvasWidth: 600,
    canvasHeight: 850,
    backgroundColor: '#0f766e',
    scope: 'system',
    elements: [
      {
        type: 'text',
        id: 'heading-1',
        x: 5,
        y: 6,
        width: 90,
        height: 8,
        text: 'ACCESS OUR MENU',
        fontSize: 34,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#FFFFFF',
        textAlign: 'center',
      },
      {
        type: 'text',
        id: 'cta',
        x: 20,
        y: 16,
        width: 60,
        height: 5,
        text: 'SCAN WITH YOUR PHONE',
        fontSize: 13,
        fontFamily: 'Inter',
        fontWeight: '700',
        fill: '#99f6e4',
        textAlign: 'center',
      },
      {
        type: 'rect',
        id: 'qr-bg',
        x: 12,
        y: 24,
        width: 76,
        height: 48,
        shapeFill: '#FFFFFF',
        borderRadius: 24,
      },
      {
        type: 'qr',
        id: 'qr-code',
        x: 18,
        y: 28,
        width: 64,
        height: 40,
        isQR: true,
      },
      {
        type: 'text',
        id: 'hours',
        x: 5,
        y: 75,
        width: 90,
        height: 10,
        text: 'OPEN TUESDAY TO SUNDAY\n10:00 AM — 11:00 PM',
        fontSize: 15,
        fontFamily: 'Inter',
        fontWeight: '800',
        fill: '#fed7aa',
        textAlign: 'center',
      },
      {
        type: 'rect',
        id: 'footer-bg',
        x: 0,
        y: 88,
        width: 100,
        height: 12,
        shapeFill: '#FFFFFF',
      },
      {
        type: 'text',
        id: 'footer-info',
        x: 5,
        y: 91,
        width: 90,
        height: 8,
        text: 'Free High-Speed Wi-Fi Available Onsite',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: '700',
        fill: '#0f766e',
        textAlign: 'center',
      },
    ],
  },

  // Template 4: WiFi Share Sign
  {
    id: 'tpl-wifi-share',
    name: 'Wi-Fi Quick Connect',
    category: 'utility',
    description: 'Share your WiFi credentials with a single camera scan',
    canvasWidth: 500,
    canvasHeight: 750,
    backgroundColor: '#1e293b',
    scope: 'system',
    elements: [
      {
        type: 'text',
        id: 'heading-1',
        x: 8,
        y: 6,
        width: 84,
        height: 6,
        text: 'GUEST WI-FI',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: '700',
        fill: '#38bdf8',
        textAlign: 'left',
      },
      {
        type: 'text',
        id: 'heading-2',
        x: 8,
        y: 14,
        width: 84,
        height: 14,
        text: 'Connect in\nSeconds',
        fontSize: 38,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#FFFFFF',
        textAlign: 'left',
      },
      {
        type: 'rect',
        id: 'qr-card',
        x: 10,
        y: 36,
        width: 80,
        height: 44,
        shapeFill: '#FFFFFF',
        borderRadius: 20,
      },
      {
        type: 'text',
        id: 'scan-label',
        x: 20,
        y: 39,
        width: 60,
        height: 4,
        text: 'POINT CAMERA HERE',
        fontSize: 11,
        fontFamily: 'Inter',
        fontWeight: '800',
        fill: '#0f172a',
        textAlign: 'center',
      },
      {
        type: 'qr',
        id: 'qr-code',
        x: 18,
        y: 44,
        width: 64,
        height: 34,
        isQR: true,
      },
      {
        type: 'text',
        id: 'network',
        x: 10,
        y: 84,
        width: 80,
        height: 4,
        text: 'Network: SmartSapp-Guest',
        fontSize: 13,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#cbd5e1',
        textAlign: 'center',
      },
    ],
  },

  // Template 5: Admissions & Open Day Academic Flyer
  {
    id: 'tpl-admissions-open-day',
    name: 'Admissions & Open Day',
    category: 'academic',
    description: 'Professional academic admissions and campus registration poster',
    canvasWidth: 595,
    canvasHeight: 842, // A4
    backgroundColor: '#1e1b4b',
    scope: 'system',
    elements: [
      {
        type: 'text',
        id: 'school-name',
        x: 10,
        y: 6,
        width: 80,
        height: 6,
        text: 'ACADEMY OF EXCELLENCE',
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: '800',
        fill: '#a5b4fc',
        textAlign: 'center',
      },
      {
        type: 'text',
        id: 'main-title',
        x: 5,
        y: 13,
        width: 90,
        height: 14,
        text: 'OPEN HOUSE 2026',
        fontSize: 38,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#FFFFFF',
        textAlign: 'center',
      },
      {
        type: 'text',
        id: 'date-badge',
        x: 20,
        y: 28,
        width: 60,
        height: 4,
        text: 'SATURDAY, OCTOBER 24 • 10 AM',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: '700',
        fill: '#fde047',
        textAlign: 'center',
      },
      {
        type: 'rect',
        id: 'qr-card',
        x: 15,
        y: 35,
        width: 70,
        height: 42,
        shapeFill: '#FFFFFF',
        borderRadius: 24,
      },
      {
        type: 'qr',
        id: 'qr-code',
        x: 20,
        y: 39,
        width: 60,
        height: 34,
        isQR: true,
      },
      {
        type: 'text',
        id: 'cta-action',
        x: 10,
        y: 80,
        width: 80,
        height: 5,
        text: 'SCAN TO RESERVE YOUR SEAT',
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: '800',
        fill: '#FFFFFF',
        textAlign: 'center',
      },
      {
        type: 'text',
        id: 'website',
        x: 10,
        y: 88,
        width: 80,
        height: 4,
        text: 'admissions@academy.edu • www.academy.edu',
        fontSize: 11,
        fontFamily: 'Inter',
        fontWeight: '400',
        fill: '#94a3b8',
        textAlign: 'center',
      },
    ],
  },

  // Template 6: Event / Conference Badge Pass
  {
    id: 'tpl-event-badge',
    name: 'Conference Check-In Badge',
    category: 'event',
    description: 'Conference pass with attendee identification and fast QR check-in',
    canvasWidth: 350,
    canvasHeight: 500,
    backgroundColor: '#09090b',
    scope: 'system',
    elements: [
      {
        type: 'rect',
        id: 'top-bar',
        x: 0,
        y: 0,
        width: 100,
        height: 8,
        shapeFill: '#2563eb',
      },
      {
        type: 'text',
        id: 'conf-title',
        x: 5,
        y: 12,
        width: 90,
        height: 6,
        text: 'SMARTSAPP SUMMIT 2026',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#FFFFFF',
        textAlign: 'center',
      },
      {
        type: 'text',
        id: 'access-tier',
        x: 20,
        y: 20,
        width: 60,
        height: 4,
        text: 'ALL-ACCESS VIP',
        fontSize: 11,
        fontFamily: 'Inter',
        fontWeight: '800',
        fill: '#60a5fa',
        textAlign: 'center',
      },
      {
        type: 'rect',
        id: 'qr-card',
        x: 12,
        y: 28,
        width: 76,
        height: 52,
        shapeFill: '#FFFFFF',
        borderRadius: 16,
      },
      {
        type: 'qr',
        id: 'qr-code',
        x: 16,
        y: 32,
        width: 68,
        height: 44,
        isQR: true,
      },
      {
        type: 'text',
        id: 'scan-sub',
        x: 5,
        y: 84,
        width: 90,
        height: 4,
        text: 'SCAN FOR ENTRY & BADGE PRINT',
        fontSize: 9,
        fontFamily: 'Inter',
        fontWeight: '700',
        fill: '#a1a1aa',
        textAlign: 'center',
      },
    ],
  },

  // Template 7: Retail Flash Promo Coupon
  {
    id: 'tpl-retail-promo',
    name: 'Retail Flash Promo',
    category: 'business',
    description: 'High-converting discount and in-store coupon sign',
    canvasWidth: 600,
    canvasHeight: 800,
    backgroundColor: '#dc2626',
    scope: 'system',
    elements: [
      {
        type: 'text',
        id: 'promo-badge',
        x: 10,
        y: 6,
        width: 80,
        height: 6,
        text: 'EXCLUSIVE IN-STORE OFFER',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: '800',
        fill: '#fef08a',
        textAlign: 'center',
      },
      {
        type: 'text',
        id: 'headline',
        x: 5,
        y: 14,
        width: 90,
        height: 14,
        text: 'GET 25% OFF',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#FFFFFF',
        textAlign: 'center',
      },
      {
        type: 'text',
        id: 'subtext',
        x: 10,
        y: 30,
        width: 80,
        height: 5,
        text: 'YOUR ENTIRE PURCHASE TODAY',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: '700',
        fill: '#FFFFFF',
        textAlign: 'center',
      },
      {
        type: 'rect',
        id: 'qr-card',
        x: 15,
        y: 38,
        width: 70,
        height: 44,
        shapeFill: '#FFFFFF',
        borderRadius: 20,
      },
      {
        type: 'qr',
        id: 'qr-code',
        x: 20,
        y: 42,
        width: 60,
        height: 36,
        isQR: true,
      },
      {
        type: 'text',
        id: 'footer-terms',
        x: 10,
        y: 86,
        width: 80,
        height: 4,
        text: 'Scan to claim coupon code at checkout',
        fontSize: 13,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#fee2e2',
        textAlign: 'center',
      },
    ],
  },
];
