/**
 * ARCHITECTURAL NOTE (Rule 10 Maintainer Guidance):
 * Pure survey response and file processing utility functions.
 * Decoupled from Server Actions ('use server') so client components and server actions
 * can safely import synchronous parsing, sanitization, and contact extraction functions.
 */

import type {
  SurveyResponse,
  SurveyElement,
  SurveyQuestion,
  OnlinePresence,
  IndustryVertical,
} from './types';
import type { ResolvedContact } from './contact-adapter';

// Standard mapping aliases for custom field targets
export const CUSTOM_FIELD_KEY_MAP: Record<string, string> = {
  curriculum: 'curriculum',
  curricula: 'curriculum',
  curriculumtype: 'curriculum',
  'curriculum type': 'curriculum',
  capacity: 'capacity',
  schoolcapacity: 'capacity',
  studentcapacity: 'capacity',
  facilities: 'facilities',
  schoolfacilities: 'facilities',
  gendercomposition: 'genderComposition',
  'gender composition': 'genderComposition',
  gender: 'genderComposition',
  accreditation: 'accreditation',
  accreditations: 'accreditation',
  affiliation: 'affiliation',
  affiliations: 'affiliation',
  academicschedule: 'academicSchedule',
  'academic schedule': 'academicSchedule',
  schedule: 'academicSchedule',
  feestructure: 'feeStructure',
  'fee structure': 'feeStructure',
  fees: 'feeStructure',
  tuitionfee: 'feeStructure',
  foundedyear: 'foundedYear',
  'founded year': 'foundedYear',
  establishedyear: 'foundedYear',
  yearfounded: 'foundedYear',
  website: 'website',
  url: 'website',
  schoolwebsite: 'website',
  facebook: 'facebook',
  facebookurl: 'facebook',
  instagram: 'instagram',
  instagramurl: 'instagram',
  twitter: 'twitter',
  x: 'twitter',
  twitterurl: 'twitter',
  linkedin: 'linkedin',
  linkedinurl: 'linkedin',
  youtube: 'youtube',
  youtubeurl: 'youtube',
  tiktok: 'tiktok',
  tiktokurl: 'tiktok',
  googlebusinessprofile: 'googleBusinessProfile',
  gmb: 'googleBusinessProfile',
};

/**
 * Known schema-validated fields for vertical industries.
 * Prevents non-schema custom fields from being stripped by validateIndustryData.
 */
export const INDUSTRY_SCHEMA_FIELDS: Record<string, Set<string>> = {
  SchoolEnrollment: new Set([
    'gradeOfferings', 'academicYear', 'capacity', 'currentEnrollment',
    'applicationIds', 'enrollmentIds', 'schoolVisitIds', 'nominalRoll'
  ]),
  Law: new Set([
    'firmType', 'practiceAreas', 'barAssociations', 'capacity',
    'conflictCheckRequired', 'matterIds', 'intakeFormIds', 'conflictCheckIds'
  ]),
  Marketing: new Set([
    'clientIndustry', 'targetAudience', 'capacity', 'revenue',
    'monthlyBudget', 'campaignIds', 'proposalIds', 'deliverableIds'
  ]),
  RealEstate: new Set([
    'propertyPortfolio', 'developerType', 'investmentFocus', 'capacity', 'propertyIds'
  ]),
  Consultancy: new Set([
    'clientIndustry', 'capacity', 'strategicPriorities', 'painPoints',
    'discoveryIds', 'proposalIds', 'engagementIds'
  ]),
  SaaS: new Set([
    'planType', 'renewalInterval', 'capacity', 'activeUsers',
    'trialIds', 'onboardingIds', 'supportTicketIds', 'healthScoreIds'
  ]),
};

/**
 * Normalization dictionary for online presence properties
 */
export const ONLINE_PRESENCE_MAP: Record<string, keyof OnlinePresence> = {
  website: 'website',
  web: 'website',
  url: 'website',
  site: 'website',
  schoolwebsite: 'website',
  schoolwebsiteaddress: 'website',
  facebook: 'facebook',
  fb: 'facebook',
  facebookpage: 'facebook',
  instagram: 'instagram',
  ig: 'instagram',
  linkedin: 'linkedin',
  whatsapp: 'whatsapp',
  wa: 'whatsapp',
  tiktok: 'tiktok',
  youtube: 'youtube',
  yt: 'youtube',
  twitter: 'x',
  x: 'x',
  digitaladdress: 'digitalAddress',
  gpsaddress: 'digitalAddress',
  googlemap: 'googleMapLocation',
  googlemaps: 'googleMapLocation',
  googlemaplocation: 'googleMapLocation',
  googlebusiness: 'googleBusinessProfile',
  googlebusinessprofile: 'googleBusinessProfile',
  gmb: 'googleBusinessProfile',
};

/**
 * Helper to check if a value looks like a generic choice option
 */
function isGenericChoiceValue(val: unknown): boolean {
  if (typeof val !== 'string') return false;
  const trimmed = val.trim().toLowerCase();
  return ['yes', 'no', 'true', 'false', 'n/a', 'none', 'other'].includes(trimmed);
}

/**
 * Extract clean human-readable filename from Firebase Storage URL
 */
export function extractFileNameFromStorageUrl(urlStr: string): string {
  try {
    const url = new URL(urlStr);
    const path = decodeURIComponent(url.pathname);
    const rawName = path.substring(path.lastIndexOf('/') + 1);
    // Only strip leading timestamp generated by file uploaders (e.g. 1740001234567-filename.ext)
    const timestampMatch = rawName.match(/^\d{10,14}-(.+)$/);
    if (timestampMatch) {
      return timestampMatch[1];
    }
    return rawName;
  } catch {
    return 'uploaded-file';
  }
}

/**
 * ARCHITECTURAL NOTE (Rule 10 Maintainer Guidance):
 * Extracted Contact Details Interface.
 * 
 * Standardized structure holding resolved entity and contact fields
 * for table displays, response detail cards, and CSV exports.
 */
export interface ExtractedContactDetails {
  entityName: string;
  primaryContactName: string;
  primaryContactEmail: string;
  primaryContactPhone: string;
  isLiveCrm: boolean;
  entityId?: string | null;
  locationString?: string;
  zoneName?: string;
  roleOrTitle?: string;
}

/**
 * ARCHITECTURAL NOTE (Rule 10 Maintainer Guidance):
 * Resolves contact & entity details from a SurveyResponse with a resilient 5-tier fallback hierarchy:
 * Tier 1: ResolvedContact from CRM (if entityId is attached and loaded from CRM adapter)
 * Tier 2: Response top-level snapshot fields (entityName, respondentName, contactEmail, contactPhone)
 * Tier 3: Lead form capture details (response.leadDetails: company, name, email, phone)
 * Tier 4: Response variables map (entity_name, school_name, contact_name, respondent_name, name, phone, email, etc.)
 * Tier 5: Answers heuristic scan (searches response.answers for question titles or value patterns)
 */
export function extractResponseContactDetails(
  response: SurveyResponse,
  contact?: ResolvedContact | null,
  surveyQuestions?: Array<SurveyElement | SurveyQuestion | { id: string; title?: string; type?: string }>
): ExtractedContactDetails {
  const vars = (response as unknown as { variables?: Record<string, unknown> }).variables || {};
  const lead = (response as unknown as { leadDetails?: Record<string, unknown> }).leadDetails || {};
  const answers = response.answers || [];

  // Helper to find answer value by question title keyword or questionId
  const findAnswerByKeyword = (keywords: string[]): string => {
    if (!answers || !Array.isArray(answers) || answers.length === 0) return '';

    const unpackValue = (value: unknown): string => {
      if (typeof value === 'string' && value.trim().length > 0) {
        return value.trim();
      }
      if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
        const valObj = value as Record<string, unknown>;
        if (typeof valObj.other === 'string' && valObj.other.trim().length > 0) return valObj.other.trim();
        if (typeof valObj.option === 'string' && valObj.option.trim().length > 0 && valObj.option !== '__other__') return valObj.option.trim();
      }
      return '';
    };

    // 1. First try matching with survey questions if provided
    if (surveyQuestions && Array.isArray(surveyQuestions)) {
      for (const q of surveyQuestions) {
        const qTitle = (q.title || '').toLowerCase();
        const qType = (q.type || '').toLowerCase();
        if (keywords.some((kw) => qTitle.includes(kw) || qType.includes(kw))) {
          const matchedAns = answers.find((a) => a.questionId === q.id);
          if (matchedAns && matchedAns.value !== undefined && matchedAns.value !== null) {
            const unpacked = unpackValue(matchedAns.value);
            if (unpacked) return unpacked;
          }
        }
      }
    }

    // 2. Direct fallback on answer.questionId if surveyQuestions is omitted or yielded no match
    for (const ans of answers) {
      const qId = (ans.questionId || '').toLowerCase();
      if (keywords.some((kw) => qId.includes(kw.replace(/\s+/g, '_')) || qId.includes(kw.replace(/\s+/g, '')))) {
        const unpacked = unpackValue(ans.value);
        if (unpacked) return unpacked;
      }
    }

    return '';
  };

  // 1. Entity / School Name (Tiers 1 -> 5)
  const heuristicEntityName = !contact?.name && !response.entityName && !lead.company && !vars.entity_name && !vars.school_name
    ? findAnswerByKeyword(['school', 'institution', 'organization', 'company', 'entity name', 'school name'])
    : '';

  const entityName = (
    contact?.name ||
    response.entityName ||
    (typeof lead.company === 'string' ? lead.company : '') ||
    (typeof vars.entity_name === 'string' ? vars.entity_name : '') ||
    (typeof vars.school_name === 'string' ? vars.school_name : '') ||
    (typeof vars.organization_name === 'string' ? vars.organization_name : '') ||
    (typeof vars.q_entity_name_input === 'string' ? vars.q_entity_name_input : '') ||
    heuristicEntityName ||
    ''
  ).trim();

  // 2. Primary Contact Name (Tiers 1 -> 5)
  const heuristicContactName = !contact?.primaryContactName && !response.respondentName && !lead.name && !vars.contact_name && !vars.respondent_name && !vars.name
    ? findAnswerByKeyword(['your name', 'contact name', 'full name', 'respondent name', 'contact person', 'principal name', 'headmaster'])
    : '';

  const primaryContactName = (
    contact?.primaryContactName ||
    response.respondentName ||
    (typeof lead.name === 'string' ? lead.name : '') ||
    (typeof vars.contact_name === 'string' ? vars.contact_name : '') ||
    (typeof vars.respondent_name === 'string' ? vars.respondent_name : '') ||
    (typeof vars.name === 'string' ? vars.name : '') ||
    (typeof vars.fullName === 'string' ? vars.fullName : '') ||
    heuristicContactName ||
    ''
  ).trim();

  // 3. Primary Contact Email (Tiers 1 -> 5)
  const heuristicEmail = !contact?.primaryContactEmail && !response.contactEmail && !lead.email && !vars.contact_email && !vars.email
    ? findAnswerByKeyword(['email', 'e-mail', 'mail'])
    : '';

  const primaryContactEmail = (
    contact?.primaryContactEmail ||
    response.contactEmail ||
    (typeof lead.email === 'string' ? lead.email : '') ||
    (typeof vars.contact_email === 'string' ? vars.contact_email : '') ||
    (typeof vars.email === 'string' ? vars.email : '') ||
    (typeof vars.respondent_email === 'string' ? vars.respondent_email : '') ||
    heuristicEmail ||
    ''
  ).trim();

  // 4. Primary Contact Phone (Tiers 1 -> 5)
  const rawContactPhone = (response as unknown as { contactPhone?: string }).contactPhone;
  const heuristicPhone = !contact?.primaryContactPhone && !rawContactPhone && !lead.phone && !vars.contact_phone && !vars.phone
    ? findAnswerByKeyword(['phone', 'contact number', 'mobile', 'telephone', 'whatsapp'])
    : '';

  const primaryContactPhone = (
    contact?.primaryContactPhone ||
    rawContactPhone ||
    (typeof lead.phone === 'string' ? lead.phone : '') ||
    (typeof vars.contact_phone === 'string' ? vars.contact_phone : '') ||
    (typeof vars.phone === 'string' ? vars.phone : '') ||
    (typeof vars.respondent_phone === 'string' ? vars.respondent_phone : '') ||
    heuristicPhone ||
    ''
  ).trim();

  // 5. Role or Title
  const primaryEntityContact = contact?.entityContacts?.find((c) => c.isPrimary);
  const roleOrTitle = primaryEntityContact?.typeLabel || 
    (typeof lead.role === 'string' ? lead.role : '') ||
    (typeof vars.role === 'string' ? vars.role : '') || 
    (typeof vars.title === 'string' ? vars.title : '') || 
    undefined;

  const isLiveCrm = Boolean(response.entityId && contact);

  return {
    entityName,
    primaryContactName,
    primaryContactEmail,
    primaryContactPhone,
    isLiveCrm,
    entityId: response.entityId || null,
    locationString: contact?.locationString,
    zoneName: contact?.zoneName,
    roleOrTitle,
  };
}

/**
 * Sanitizes a cell value for CSV output to prevent CSV / Formula Injection attacks
 * (OWASP CSV Injection guidelines: prepend single quote if cell starts with =, +, -, @, tab, CR, or newline)
 */
export function sanitizeForCsv(val: string | number | boolean | null | undefined): string {
  if (val === null || val === undefined) return '';
  const rawStr = String(val);
  if (!rawStr) return '';
  const trimmed = rawStr.trim();
  if (/^[=+\-@\t\r\n]/.test(rawStr) || /^[=+\-@]/.test(trimmed)) {
    return `'${rawStr}`;
  }
  return trimmed;
}

export interface ParsedSurveyMappings {
  mappedInstitutionData: Record<string, unknown>;
  mappedPersonData: Record<string, string | number | boolean | string[]>;
  mappedCustomData: Record<string, string | number | boolean | string[]>;
  mappedOnlinePresence: Partial<OnlinePresence>;
  mappedLocation: Record<string, unknown>;
  overriddenEntityName: string | null;
  overriddenContactName: string | null;
  overriddenContactEmail: string | null;
  overriddenContactPhone: string | null;
  slogan: string | null;
  initials: string | null;
  logoUrl: string | null;
  referee: string | null;
  interestsText: string | null;
}

/**
 * Universal Target Field Resolver for Surveys.
 * Maps custom fields, industry data, online presence, and location safely.
 */
export function parseAndDistributeSurveyMappings(
  additionalMappings: Array<{ questionId: string; targetField: string }> | undefined,
  answers: Array<{ questionId: string; value: unknown }> | undefined,
  workspaceIndustry?: IndustryVertical | string
): ParsedSurveyMappings {
  const result: ParsedSurveyMappings = {
    mappedInstitutionData: {},
    mappedPersonData: {},
    mappedCustomData: {},
    mappedOnlinePresence: {},
    mappedLocation: {},
    overriddenEntityName: null,
    overriddenContactName: null,
    overriddenContactEmail: null,
    overriddenContactPhone: null,
    slogan: null,
    initials: null,
    logoUrl: null,
    referee: null,
    interestsText: null,
  };

  if (!additionalMappings?.length || !answers?.length) {
    return result;
  }

  const getAnswerValue = (qId?: string) => {
    if (!qId) return null;
    const ans = answers.find((a) => a.questionId === qId);
    return ans ? ans.value : null;
  };

  additionalMappings.forEach((m) => {
    const val = getAnswerValue(m.questionId);
    if (val === null || val === undefined || val === '') return;

    const rawTarget = m.targetField.trim();
    const cleanLower = rawTarget.toLowerCase().replace(/[\s_-]+/g, '');

    // 1. Identity & Contact Overrides
    if (rawTarget === 'entity.name' || cleanLower === 'name' || cleanLower === 'schoolname') {
      if (!isGenericChoiceValue(val)) result.overriddenEntityName = String(val).trim();
      return;
    }
    if (rawTarget === 'contacts.name' || cleanLower === 'contactname' || cleanLower === 'contactperson') {
      if (!isGenericChoiceValue(val)) result.overriddenContactName = String(val).trim();
      return;
    }
    if (rawTarget === 'contacts.email' || cleanLower === 'contactemail' || cleanLower === 'email') {
      result.overriddenContactEmail = String(val).trim().toLowerCase();
      return;
    }
    if (rawTarget === 'contacts.phone' || cleanLower === 'contactphone' || cleanLower === 'phone') {
      result.overriddenContactPhone = String(val).trim();
      return;
    }

    // 2. Online Presence (e.g. onlinePresence.website, Website, Facebook, etc.)
    if (rawTarget.toLowerCase().startsWith('onlinepresence.')) {
      const subKey = rawTarget.substring('onlinepresence.'.length).trim();
      const normSub = subKey.toLowerCase().replace(/[\s_-]+/g, '');
      const mappedKey = ONLINE_PRESENCE_MAP[normSub] || (subKey as keyof OnlinePresence);
      result.mappedOnlinePresence[mappedKey] = String(val).trim();
      return;
    }
    if (ONLINE_PRESENCE_MAP[cleanLower]) {
      const mappedKey = ONLINE_PRESENCE_MAP[cleanLower];
      result.mappedOnlinePresence[mappedKey] = String(val).trim();
      if (mappedKey === 'digitalAddress') {
        result.mappedLocation.locationString = String(val).trim();
      }
      return;
    }

    // 3. Location fields
    if (rawTarget.toLowerCase().startsWith('location.')) {
      const subKey = rawTarget.substring('location.'.length).trim();
      result.mappedLocation[subKey] = val;
      return;
    }
    if (cleanLower === 'address' || cleanLower === 'digitaladdress') {
      result.mappedLocation.locationString = String(val).trim();
      return;
    }

    // 4. Direct Root Entity Branding/Attributes
    if (cleanLower === 'slogan') {
      result.slogan = String(val).trim();
      return;
    }
    if (cleanLower === 'initials') {
      result.initials = String(val).trim();
      return;
    }
    if (cleanLower === 'logo' || cleanLower === 'logourl') {
      result.logoUrl = String(val).trim();
      return;
    }
    if (cleanLower === 'referee') {
      result.referee = String(val).trim();
      return;
    }

    // 5. Custom Data prefix
    if (rawTarget.startsWith('customData.')) {
      const field = rawTarget.substring('customData.'.length).trim();
      result.mappedCustomData[field] = val as string | number | boolean | string[];
      return;
    }

    // 6. Institution Data prefix
    if (rawTarget.startsWith('institutionData.')) {
      const field = rawTarget.substring('institutionData.'.length).trim();
      const isSchemaField = workspaceIndustry && INDUSTRY_SCHEMA_FIELDS[workspaceIndustry]?.has(field);
      if (isSchemaField) {
        result.mappedInstitutionData[field] = (field === 'nominalRoll' || field === 'capacity' || field === 'currentEnrollment') ? Number(val) : val;
      } else {
        // Dynamic/custom field (e.g. staff_data, parent_and_student_data) → preserve in customData!
        result.mappedCustomData[field] = val as string | number | boolean | string[];
        result.mappedInstitutionData[field] = val;
      }
      return;
    }

    // 7. Person Data prefix
    if (rawTarget.startsWith('personData.')) {
      const field = rawTarget.substring('personData.'.length).trim();
      result.mappedPersonData[field] = val as string | number | boolean | string[];
      result.mappedCustomData[field] = val as string | number | boolean | string[];
      return;
    }

    // 8. Default fallback: route to customData
    result.mappedCustomData[rawTarget] = val as string | number | boolean | string[];
  });

  return result;
}
