/**
 * @fileOverview Static template variable definitions
 * 
 * This file contains the static variable definitions used by the template system.
 * It's separated from the registry to avoid 'use server' constraints.
 */

import type { TemplateVariable } from './types';

/**
 * Static variable definitions for all template contexts.
 * These are the built-in variables available in templates.
 */
export const STATIC_VARIABLES: TemplateVariable[] = [
  // ── Common (available in all contexts) ──────────────────────────────────
  {
    id: 'common_contact_name',
    name: 'contact_name',
    label: 'Contact Name',
    description: 'Full name of the primary contact',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Jane Doe',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_contact_email',
    name: 'contact_email',
    label: 'Contact Email',
    description: 'Email address of the primary contact',
    dataType: 'string',
    context: 'common',
    exampleValue: 'jane.doe@example.com',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_contact_phone',
    name: 'contact_phone',
    label: 'Contact Phone',
    description: 'Phone number of the primary contact',
    dataType: 'string',
    context: 'common',
    exampleValue: '+1 555-123-4567',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_entity_name',
    name: 'entity_name',
    label: 'Entity Name',
    description: 'Name of the entity (school, family, or person)',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Greenwood Academy',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_organization_name',
    name: 'organization_name',
    label: 'Organization Name',
    description: 'Name of the organization',
    dataType: 'string',
    context: 'common',
    exampleValue: 'SmartSapp Education',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_workspace_name',
    name: 'workspace_name',
    label: 'Workspace Name',
    description: 'Name of the current workspace',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Admissions 2025',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_user_name',
    name: 'user_name',
    label: 'User Name',
    description: 'Name of the logged-in user sending the message',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Alex Johnson',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_current_date',
    name: 'current_date',
    label: 'Current Date',
    description: 'Today\'s date',
    dataType: 'date',
    context: 'common',
    exampleValue: '2025-06-15',
    isDynamic: false,
    isComputed: true,
    computeExpression: 'new Date().toLocaleDateString()',
  },
  {
    id: 'common_current_time',
    name: 'current_time',
    label: 'Current Time',
    description: 'Current time of day',
    dataType: 'string',
    context: 'common',
    exampleValue: '10:30 AM',
    isDynamic: false,
    isComputed: true,
    computeExpression: 'new Date().toLocaleTimeString()',
  },
  {
    id: 'common_current_year',
    name: 'current_year',
    label: 'Current Year',
    description: 'The current calendar year',
    dataType: 'number',
    context: 'common',
    exampleValue: '2025',
    isDynamic: false,
    isComputed: true,
    computeExpression: 'new Date().getFullYear()',
  },

  // ── Meeting ──────────────────────────────────────────────────────────────
  {
    id: 'meeting_link',
    name: 'meeting_link',
    label: 'Meeting Link',
    description: 'URL to join the meeting',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://meet.example.com/abc123',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_time',
    name: 'meeting_time',
    label: 'Meeting Time',
    description: 'Scheduled time of the meeting',
    dataType: 'date',
    context: 'meeting',
    exampleValue: '2025-06-20 09:00 AM',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_title',
    name: 'meeting_title',
    label: 'Meeting Title',
    description: 'Title or name of the meeting',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'Kickoff Meeting',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_type',
    name: 'meeting_type',
    label: 'Meeting Type',
    description: 'Type/category of the meeting',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'Webinar',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_organizer_name',
    name: 'organizer_name',
    label: 'Organizer Name',
    description: 'Name of the meeting organizer',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'Sarah Williams',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_attendee_names',
    name: 'attendee_names',
    label: 'Attendee Names',
    description: 'Comma-separated list of attendee names',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'John Smith, Mary Jones',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_date',
    name: 'meeting_date',
    label: 'Meeting Date',
    description: 'Date of the meeting',
    dataType: 'date',
    context: 'meeting',
    exampleValue: '2025-06-20',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_duration',
    name: 'meeting_duration',
    label: 'Meeting Duration',
    description: 'Duration of the meeting',
    dataType: 'string',
    context: 'meeting',
    exampleValue: '60 minutes',
    isDynamic: false,
    isComputed: false,
  },

  // ── Form ─────────────────────────────────────────────────────────────────
  {
    id: 'form_form_name',
    name: 'form_name',
    label: 'Form Name',
    description: 'Name of the form',
    dataType: 'string',
    context: 'form',
    exampleValue: 'Enrollment Application',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'form_form_link',
    name: 'form_link',
    label: 'Form Link',
    description: 'URL to access the form',
    dataType: 'url',
    context: 'form',
    exampleValue: 'https://app.example.com/forms/enrollment',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'form_submission_deadline',
    name: 'submission_deadline',
    label: 'Submission Deadline',
    description: 'Deadline for form submission',
    dataType: 'date',
    context: 'form',
    exampleValue: '2025-07-01',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'form_respondent_name',
    name: 'respondent_name',
    label: 'Respondent Name',
    description: 'Name of the person filling out the form',
    dataType: 'string',
    context: 'form',
    exampleValue: 'Michael Brown',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'form_submission_date',
    name: 'submission_date',
    label: 'Submission Date',
    description: 'Date the form was submitted',
    dataType: 'date',
    context: 'form',
    exampleValue: '2025-06-18',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'form_days_remaining',
    name: 'days_remaining',
    label: 'Days Remaining',
    description: 'Number of days until the submission deadline',
    dataType: 'number',
    context: 'form',
    exampleValue: '7',
    isDynamic: false,
    isComputed: true,
  },
  {
    id: 'form_deadline',
    name: 'deadline',
    label: 'Deadline',
    description: 'Deadline date for form submission',
    dataType: 'date',
    context: 'form',
    exampleValue: '2025-07-01',
    isDynamic: false,
    isComputed: false,
  },

  // ── Survey ───────────────────────────────────────────────────────────────
  {
    id: 'survey_survey_title',
    name: 'survey_title',
    label: 'Survey Title',
    description: 'Title of the survey',
    dataType: 'string',
    context: 'survey',
    exampleValue: 'Parent Satisfaction Survey',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'survey_survey_link',
    name: 'survey_link',
    label: 'Survey Link',
    description: 'URL to access the survey',
    dataType: 'url',
    context: 'survey',
    exampleValue: 'https://app.example.com/surveys/satisfaction',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'survey_completion_status',
    name: 'completion_status',
    label: 'Completion Status',
    description: 'Whether the survey has been completed',
    dataType: 'string',
    context: 'survey',
    exampleValue: 'Completed',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'survey_score',
    name: 'score',
    label: 'Score',
    description: 'Score achieved on the survey',
    dataType: 'number',
    context: 'survey',
    exampleValue: '85',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'survey_result_message',
    name: 'result_message',
    label: 'Result Message',
    description: 'Message based on survey result/score',
    dataType: 'string',
    context: 'survey',
    exampleValue: 'Excellent performance!',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'survey_completion_date',
    name: 'completion_date',
    label: 'Completion Date',
    description: 'Date the survey was completed',
    dataType: 'date',
    context: 'survey',
    exampleValue: '2025-06-18',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'survey_days_remaining',
    name: 'days_remaining',
    label: 'Days Remaining',
    description: 'Number of days until the survey deadline',
    dataType: 'number',
    context: 'survey',
    exampleValue: '3',
    isDynamic: false,
    isComputed: true,
  },

  // ── Agreement ────────────────────────────────────────────────────────────
  {
    id: 'agreement_contract_name',
    name: 'contract_name',
    label: 'Contract Name',
    description: 'Name of the contract or agreement',
    dataType: 'string',
    context: 'agreement',
    exampleValue: 'Service Agreement 2025',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'agreement_contract_link',
    name: 'contract_link',
    label: 'Contract Link',
    description: 'URL to view or sign the contract',
    dataType: 'url',
    context: 'agreement',
    exampleValue: 'https://app.example.com/contracts/sa2025',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'agreement_signatory_name',
    name: 'signatory_name',
    label: 'Signatory Name',
    description: 'Name of the person who signs the contract',
    dataType: 'string',
    context: 'agreement',
    exampleValue: 'David Lee',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'agreement_deadline',
    name: 'deadline',
    label: 'Deadline',
    description: 'Deadline for signing the contract',
    dataType: 'date',
    context: 'agreement',
    exampleValue: '2025-07-15',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'agreement_contract_status',
    name: 'contract_status',
    label: 'Contract Status',
    description: 'Current status of the contract',
    dataType: 'string',
    context: 'agreement',
    exampleValue: 'Pending Signature',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'agreement_signing_date',
    name: 'signing_date',
    label: 'Signing Date',
    description: 'Date the contract was signed',
    dataType: 'date',
    context: 'agreement',
    exampleValue: '2025-06-20',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'agreement_days_remaining',
    name: 'days_remaining',
    label: 'Days Remaining',
    description: 'Number of days until the signing deadline',
    dataType: 'number',
    context: 'agreement',
    exampleValue: '10',
    isDynamic: false,
    isComputed: true,
  },

  // ── Entity ───────────────────────────────────────────────────────────────
  {
    id: 'entity_entity_name',
    name: 'entity_name',
    label: 'Entity Name',
    description: 'Name of the entity',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Greenwood Academy',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'entity_old_stage',
    name: 'old_stage',
    label: 'Old Stage',
    description: 'Previous pipeline stage of the entity',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Prospect',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'entity_new_stage',
    name: 'new_stage',
    label: 'New Stage',
    description: 'New pipeline stage of the entity',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Onboarding',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'entity_assigned_to',
    name: 'assigned_to',
    label: 'Assigned To',
    description: 'Name of the user assigned to this entity',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Chris Taylor',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'entity_assigner_name',
    name: 'assigner_name',
    label: 'Assigner Name',
    description: 'Name of the user who made the assignment',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Sarah Williams',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'entity_old_status',
    name: 'old_status',
    label: 'Old Status',
    description: 'Previous status of the entity',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Inactive',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'entity_new_status',
    name: 'new_status',
    label: 'New Status',
    description: 'New status of the entity',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Active',
    isDynamic: false,
    isComputed: false,
  },
];
