/**
 * @fileOverview Static template variable definitions
 * 
 * This file contains the static variable definitions used by the template system.
 * It's separated from the registry to avoid 'use server' constraints.
 */

import type { TemplateVariable } from './types';

/**
 * Static variable definitions for all template contexts.
 * These are the built-in variables available in templates.
 */
export const STATIC_VARIABLES: TemplateVariable[] = [
  // ── Common (available in all contexts) ──────────────────────────────────
  {
    id: 'common_contact_name',
    name: 'contact_name',
    label: 'Contact Name',
    description: 'Full name of the primary contact',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Jane Doe',
    isDynamic: false,
    isComputed: false,
    fallbackValue: 'there',
  },
  {
    id: 'common_contact_email',
    name: 'contact_email',
    label: 'Contact Email',
    description: 'Email address of the primary contact',
    dataType: 'string',
    context: 'common',
    exampleValue: 'jane.doe@example.com',
    isDynamic: false,
    isComputed: false,
    fallbackValue: 'info@domain.com',
  },
  {
    id: 'common_contact_phone',
    name: 'contact_phone',
    label: 'Contact Phone',
    description: 'Phone number of the primary contact',
    dataType: 'string',
    context: 'common',
    exampleValue: '+233 24 123 4567',
    isDynamic: false,
    isComputed: false,
    fallbackValue: 'our contact number',
  },
  {
    id: 'common_entity_name',
    name: 'entity_name',
    label: 'Entity Name',
    description: 'Name of the entity (school, family, or person)',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Greenwood Academy',
    isDynamic: false,
    isComputed: false,
    fallbackValue: 'our institution',
  },
  {
    id: 'common_organization_name',
    name: 'organization_name',
    label: 'Organization Name',
    description: 'Name of the organization',
    dataType: 'string',
    context: 'common',
    exampleValue: 'SmartSapp Education',
    isDynamic: false,
    isComputed: false,
    fallbackValue: 'our organization',
  },
  {
    id: 'common_workspace_name',
    name: 'workspace_name',
    label: 'Workspace Name',
    description: 'Name of the current workspace',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Admissions 2025',
    isDynamic: false,
    isComputed: false,
    fallbackValue: 'our workspace',
  },
  {
    id: 'common_user_name',
    name: 'user_name',
    label: 'User Name',
    description: 'Name of the logged-in user sending the message',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Alex Johnson',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_current_date',
    name: 'current_date',
    label: 'Current Date',
    description: 'Today\'s date',
    dataType: 'date',
    context: 'common',
    exampleValue: '2025-06-15',
    isDynamic: false,
    isComputed: true,
    computeExpression: 'new Date().toLocaleDateString()',
  },
  {
    id: 'common_current_time',
    name: 'current_time',
    label: 'Current Time',
    description: 'Current time of day',
    dataType: 'string',
    context: 'common',
    exampleValue: '10:30 AM',
    isDynamic: false,
    isComputed: true,
    computeExpression: 'new Date().toLocaleTimeString()',
  },
  {
    id: 'common_current_year',
    name: 'current_year',
    label: 'Current Year',
    description: 'The current calendar year',
    dataType: 'number',
    context: 'common',
    exampleValue: '2025',
    isDynamic: false,
    isComputed: true,
    computeExpression: 'new Date().getFullYear()',
  },
  // ── Sender Variables ──────────────────────────────────────────────────────
  {
    id: 'common_sender_name',
    name: 'sender_name',
    label: 'Sender Name',
    description: 'Name of the agent or sender',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Alex Johnson',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_sender_email',
    name: 'sender_email',
    label: 'Sender Email',
    description: 'Email address of the agent or sender',
    dataType: 'string',
    context: 'common',
    exampleValue: 'alex@organization.com',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_sender_phone',
    name: 'sender_phone',
    label: 'Sender Phone',
    description: 'Phone number of the agent or sender',
    dataType: 'string',
    context: 'common',
    exampleValue: '+1 555 1234',
    isDynamic: false,
    isComputed: false,
  },
  // ── Recipient-Aware Variables ─────────────────────────────────────────────
  {
    id: 'common_recipient_name',
    name: 'recipient_name',
    label: 'Recipient Name',
    description: 'Name of the specific contact receiving the message',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Jane Smith',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_recipient_email',
    name: 'recipient_email',
    label: 'Recipient Email',
    description: 'Email of the specific contact receiving the message',
    dataType: 'string',
    context: 'common',
    exampleValue: 'jane.smith@example.com',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_recipient_phone',
    name: 'recipient_phone',
    label: 'Recipient Phone',
    description: 'Phone number of the specific contact receiving the message',
    dataType: 'string',
    context: 'common',
    exampleValue: '+1 555 0198',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_recipient_role',
    name: 'recipient_role',
    label: 'Recipient Role',
    description: 'Role/Type of the specific contact receiving the message',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Billing Officer',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_recipient_first_name',
    name: 'recipient_first_name',
    label: 'Recipient First Name',
    description: 'First name of the specific contact receiving the message',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Jane',
    isDynamic: false,
    isComputed: false,
  },
  // ── Org Branding & Compliance Variables ───────────────────────────────────
  {
    id: 'common_org_name',
    name: 'org_name',
    label: 'Organization Name',
    description: 'Name of the organization',
    dataType: 'string',
    context: 'common',
    exampleValue: 'SmartSapp Inc.',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_org_logo_url',
    name: 'org_logo_url',
    label: 'Organization Logo URL',
    description: 'URL of the organization\'s logo',
    dataType: 'url',
    context: 'common',
    exampleValue: 'https://example.com/logo.png',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_org_email',
    name: 'org_email',
    label: 'Organization Email',
    description: 'Public contact email of the organization',
    dataType: 'string',
    context: 'common',
    exampleValue: 'hello@organization.com',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_org_phone',
    name: 'org_phone',
    label: 'Organization Phone',
    description: 'Public contact phone of the organization',
    dataType: 'string',
    context: 'common',
    exampleValue: '+1 800 555 1234',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_org_address',
    name: 'org_address',
    label: 'Organization Address',
    description: 'Physical or mailing address of the organization',
    dataType: 'string',
    context: 'common',
    exampleValue: '123 Business Rd, Suite 100, City',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_org_website',
    name: 'org_website',
    label: 'Organization Website',
    description: 'Website URL of the organization',
    dataType: 'url',
    context: 'common',
    exampleValue: 'https://www.organization.com',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'common_unsubscribe_link',
    name: 'unsubscribe_link',
    label: 'Unsubscribe Link',
    description: 'Auto-generated link to allow recipients to opt out',
    dataType: 'url',
    context: 'common',
    exampleValue: 'https://app.example.com/unsubscribe/12345',
    isDynamic: false,
    isComputed: true, // Computed at send-time
  },
  {
    id: 'common_dashboard_link',
    name: 'dashboard_link',
    label: 'Dashboard Link',
    description: 'Auto-generated link to access the meeting or survey dashboard',
    dataType: 'url',
    context: 'common',
    exampleValue: 'https://app.example.com/admin/surveys/123',
    isDynamic: false,
    isComputed: true,
  },


  // ── Meeting ──────────────────────────────────────────────────────────────
  {
    id: 'meeting_link',
    name: 'meeting_link',
    label: 'Meeting Link',
    description: 'URL to join the meeting',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://meet.example.com/abc123',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_calendar_link',
    name: 'calendar_link',
    label: 'Calendar Link',
    description: 'URL to add the meeting to calendar',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://calendar.google.com/...',
    isDynamic: false,
    isComputed: true,
  },
  {
    id: 'meeting_recording_link',
    name: 'recording_link',
    label: 'Recording Link',
    description: 'URL to access the concluded meeting recording',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://meet.example.com/recording/123',
    isDynamic: false,
    isComputed: true,
  },
  {
    id: 'meeting_resource_link',
    name: 'resource_link',
    label: 'Resource Link',
    description: 'URL to access resources for the meeting',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://meet.example.com/resources/123',
    isDynamic: false,
    isComputed: true,
  },
  {
    id: 'meeting_feedback_form_link',
    name: 'feedback_form_link',
    label: 'Feedback Form Link',
    description: 'URL to provide feedback for the meeting',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://meet.example.com/feedback/123',
    isDynamic: false,
    isComputed: true,
  },
  {
    id: 'meeting_time',
    name: 'meeting_time',
    label: 'Meeting Time',
    description: 'Scheduled time of the meeting',
    dataType: 'date',
    context: 'meeting',
    exampleValue: '2025-06-20 09:00 AM',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_title',
    name: 'meeting_title',
    label: 'Meeting Title',
    description: 'Title or name of the meeting',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'Kickoff Meeting',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_type',
    name: 'meeting_type',
    label: 'Meeting Type',
    description: 'Type/category of the meeting',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'Webinar',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_organizer_name',
    name: 'organizer_name',
    label: 'Organizer Name',
    description: 'Name of the meeting organizer',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'Sarah Williams',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_attendee_names',
    name: 'attendee_names',
    label: 'Attendee Names',
    description: 'Comma-separated list of attendee names',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'John Smith, Mary Jones',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_date',
    name: 'meeting_date',
    label: 'Meeting Date',
    description: 'Date of the meeting',
    dataType: 'date',
    context: 'meeting',
    exampleValue: '2025-06-20',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_duration',
    name: 'meeting_duration',
    label: 'Meeting Duration',
    description: 'Duration of the meeting',
    dataType: 'string',
    context: 'meeting',
    exampleValue: '60 minutes',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_timezone',
    name: 'meeting_timezone',
    label: 'Meeting Timezone',
    description: 'Timezone of the scheduled meeting',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'Africa/Accra',
    isDynamic: false,
    isComputed: false,
  },

  // ── Meeting: Registrant Variables ────────────────────────────────────────
  {
    id: 'meeting_registrant_name',
    name: 'registrant_name',
    label: 'Registrant Name',
    description: 'Full name of the meeting registrant',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'Jane Doe',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_registrant_email',
    name: 'registrant_email',
    label: 'Registrant Email',
    description: 'Email address of the meeting registrant',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'jane.doe@example.com',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_registrant_phone',
    name: 'registrant_phone',
    label: 'Registrant Phone',
    description: 'Phone number of the meeting registrant',
    dataType: 'string',
    context: 'meeting',
    exampleValue: '+233 24 123 4567',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_registrant_join_link',
    name: 'registrant_join_link',
    label: 'Registrant Join Link',
    description: 'Unique personalized joining URL for this registrant',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://app.example.com/meetings/webinar/q3-kickoff/join?token=abc123',
    isDynamic: false,
    isComputed: true,
  },
  {
    id: 'meeting_registrant_one_click_link',
    name: 'meeting_registrant_one_click_link',
    label: 'One-Click RSVP Link',
    description: 'Unique one-click registration or RSVP selection URL for this registrant',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://app.example.com/meetings/webinar/q3-kickoff?token=abc123',
    isDynamic: false,
    isComputed: true,
  },
  {
    id: 'rsvp_going_url',
    name: 'rsvp_going_url',
    label: 'RSVP Going URL',
    description: 'Direct URL to accept the meeting invitation',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://app.example.com/meetings/webinar/q3-kickoff/respond?token=abc123&response=going',
    isDynamic: false,
    isComputed: true,
  },
  {
    id: 'rsvp_declined_url',
    name: 'rsvp_declined_url',
    label: 'RSVP Declined URL',
    description: 'Direct URL to decline the meeting invitation',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://app.example.com/meetings/webinar/q3-kickoff/respond?token=abc123&response=not_going',
    isDynamic: false,
    isComputed: true,
  },
  {
    id: 'rsvp_later_url',
    name: 'rsvp_later_url',
    label: 'RSVP Deciding Later URL',
    description: 'Direct URL to choose to decide availability later',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://app.example.com/meetings/webinar/q3-kickoff/respond?token=abc123&response=later',
    isDynamic: false,
    isComputed: true,
  },
  {
    id: 'meeting_registration_status',
    name: 'registration_status',
    label: 'Registration Status',
    description: 'Current registration status (approved, waitlisted, registered)',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'approved',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_registrant_count',
    name: 'registrant_count',
    label: 'Registrant Count',
    description: 'Total number of registered attendees for this meeting',
    dataType: 'string',
    context: 'meeting',
    exampleValue: '47',
    isDynamic: false,
    isComputed: true,
  },

  // ── Meeting: Facilitator Variables ───────────────────────────────────────
  {
    id: 'meeting_facilitator_name',
    name: 'facilitator_name',
    label: 'Facilitator Name',
    description: 'Name of the facilitator receiving this message',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'Dr. Sarah Williams',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_facilitator_email',
    name: 'facilitator_email',
    label: 'Facilitator Email',
    description: 'Email address of the facilitator',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'sarah@example.com',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_facilitator_phone',
    name: 'facilitator_phone',
    label: 'Facilitator Phone',
    description: 'Phone number of the facilitator',
    dataType: 'string',
    context: 'meeting',
    exampleValue: '+233 50 987 6543',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_facilitator_role',
    name: 'facilitator_role',
    label: 'Facilitator Role',
    description: 'Role or title of the facilitator (e.g. Keynote Speaker, Lead Trainer)',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'Keynote Speaker',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_facilitator_bio',
    name: 'facilitator_bio',
    label: 'Facilitator Bio',
    description: 'Short biography of the facilitator',
    dataType: 'string',
    context: 'meeting',
    exampleValue: 'Dr. Williams is a leading expert in educational technology...',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_facilitator_join_link',
    name: 'facilitator_join_link',
    label: 'Facilitator Join Link',
    description: 'Unique host/presenter joining URL for this facilitator',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://meet.google.com/abc-def?authuser=host',
    isDynamic: false,
    isComputed: false,
  },

  // ── Meeting: Asset Variables ─────────────────────────────────────────────
  {
    id: 'meeting_recording_url',
    name: 'recording_url',
    label: 'Recording URL',
    description: 'Link to the meeting recording (YouTube or other)',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://youtu.be/abc123',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_brochure_url',
    name: 'brochure_url',
    label: 'Brochure URL',
    description: 'Link to the meeting brochure or flyer',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://app.example.com/brochures/q3-kickoff.pdf',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_feedback_form_url',
    name: 'feedback_form_url',
    label: 'Feedback Form URL',
    description: 'Link to the post-event feedback or survey form',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://app.example.com/surveys/feedback-q3',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'meeting_resource_url',
    name: 'resource_url',
    label: 'Resource URL',
    description: 'Link to additional meeting resources or materials',
    dataType: 'url',
    context: 'meeting',
    exampleValue: 'https://drive.google.com/folder/resources',
    isDynamic: false,
    isComputed: false,
  },

  // ── Form ─────────────────────────────────────────────────────────────────
  {
    id: 'form_form_name',
    name: 'form_name',
    label: 'Form Name',
    description: 'Name of the form',
    dataType: 'string',
    context: 'form',
    exampleValue: 'Enrollment Application',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'form_form_link',
    name: 'form_link',
    label: 'Form Link',
    description: 'URL to access the form',
    dataType: 'url',
    context: 'form',
    exampleValue: 'https://app.example.com/forms/enrollment',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'form_submission_deadline',
    name: 'submission_deadline',
    label: 'Submission Deadline',
    description: 'Deadline for form submission',
    dataType: 'date',
    context: 'form',
    exampleValue: '2025-07-01',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'form_respondent_name',
    name: 'respondent_name',
    label: 'Respondent Name',
    description: 'Name of the person filling out the form',
    dataType: 'string',
    context: 'form',
    exampleValue: 'Michael Brown',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'form_submission_date',
    name: 'submission_date',
    label: 'Submission Date',
    description: 'Date the form was submitted',
    dataType: 'date',
    context: 'form',
    exampleValue: '2025-06-18',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'form_days_remaining',
    name: 'days_remaining',
    label: 'Days Remaining',
    description: 'Number of days until the submission deadline',
    dataType: 'number',
    context: 'form',
    exampleValue: '7',
    isDynamic: false,
    isComputed: true,
  },
  {
    id: 'form_deadline',
    name: 'deadline',
    label: 'Deadline',
    description: 'Deadline date for form submission',
    dataType: 'date',
    context: 'form',
    exampleValue: '2025-07-01',
    isDynamic: false,
    isComputed: false,
  },

  // ── Survey ───────────────────────────────────────────────────────────────
  {
    id: 'survey_survey_title',
    name: 'survey_title',
    label: 'Survey Title',
    description: 'Title of the survey',
    dataType: 'string',
    context: 'survey',
    exampleValue: 'Parent Satisfaction Survey',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'survey_survey_link',
    name: 'survey_link',
    label: 'Survey Link',
    description: 'URL to access the survey',
    dataType: 'url',
    context: 'survey',
    exampleValue: 'https://app.example.com/surveys/satisfaction',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'survey_completion_status',
    name: 'completion_status',
    label: 'Completion Status',
    description: 'Whether the survey has been completed',
    dataType: 'string',
    context: 'survey',
    exampleValue: 'Completed',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'survey_score',
    name: 'score',
    label: 'Score',
    description: 'Score achieved on the survey',
    dataType: 'number',
    context: 'survey',
    exampleValue: '85',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'survey_result_message',
    name: 'result_message',
    label: 'Result Message',
    description: 'Message based on survey result/score',
    dataType: 'string',
    context: 'survey',
    exampleValue: 'Excellent performance!',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'survey_completion_date',
    name: 'completion_date',
    label: 'Completion Date',
    description: 'Date the survey was completed',
    dataType: 'date',
    context: 'survey',
    exampleValue: '2025-06-18',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'survey_days_remaining',
    name: 'days_remaining',
    label: 'Days Remaining',
    description: 'Number of days until the survey deadline',
    dataType: 'number',
    context: 'survey',
    exampleValue: '3',
    isDynamic: false,
    isComputed: true,
  },
  {
    id: 'survey_result_url',
    name: 'result_url',
    label: 'Survey Result Link',
    description: 'URL to access the submitted survey results page',
    dataType: 'url',
    context: 'survey',
    exampleValue: 'https://app.example.com/surveys/satisfaction/result/response-123',
    isDynamic: false,
    isComputed: true,
  },
  {
    id: 'survey_results_link',
    name: 'survey_results_link',
    label: 'Survey Results Link (Alias)',
    description: 'Personalized URL to view completed survey results (alias)',
    dataType: 'url',
    context: 'survey',
    exampleValue: 'https://app.example.com/surveys/satisfaction/result/response-123',
    isDynamic: false,
    isComputed: true,
  },

  // ── Agreement ────────────────────────────────────────────────────────────
  {
    id: 'agreement_contract_name',
    name: 'contract_name',
    label: 'Contract Name',
    description: 'Name of the contract or agreement',
    dataType: 'string',
    context: 'agreement',
    exampleValue: 'Service Agreement 2025',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'agreement_contract_link',
    name: 'contract_link',
    label: 'Contract Link',
    description: 'URL to view or sign the contract',
    dataType: 'url',
    context: 'agreement',
    exampleValue: 'https://app.example.com/contracts/sa2025',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'agreement_signatory_name',
    name: 'signatory_name',
    label: 'Signatory Name',
    description: 'Name of the person who signs the contract',
    dataType: 'string',
    context: 'agreement',
    exampleValue: 'David Lee',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'agreement_deadline',
    name: 'deadline',
    label: 'Deadline',
    description: 'Deadline for signing the contract',
    dataType: 'date',
    context: 'agreement',
    exampleValue: '2025-07-15',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'agreement_contract_status',
    name: 'contract_status',
    label: 'Contract Status',
    description: 'Current status of the contract',
    dataType: 'string',
    context: 'agreement',
    exampleValue: 'Pending Signature',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'agreement_signing_date',
    name: 'signing_date',
    label: 'Signing Date',
    description: 'Date the contract was signed',
    dataType: 'date',
    context: 'agreement',
    exampleValue: '2025-06-20',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'agreement_days_remaining',
    name: 'days_remaining',
    label: 'Days Remaining',
    description: 'Number of days until the signing deadline',
    dataType: 'number',
    context: 'agreement',
    exampleValue: '10',
    isDynamic: false,
    isComputed: true,
  },

  // ── Entity ───────────────────────────────────────────────────────────────
  {
    id: 'entity_entity_name',
    name: 'entity_name',
    label: 'Entity Name',
    description: 'Name of the entity',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Greenwood Academy',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'entity_old_stage',
    name: 'old_stage',
    label: 'Old Stage',
    description: 'Previous pipeline stage of the entity',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Prospect',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'entity_new_stage',
    name: 'new_stage',
    label: 'New Stage',
    description: 'New pipeline stage of the entity',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Onboarding',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'entity_assigned_to',
    name: 'assigned_to',
    label: 'Assigned To',
    description: 'Name of the user assigned to this entity',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Chris Taylor',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'entity_assigner_name',
    name: 'assigner_name',
    label: 'Assigner Name',
    description: 'Name of the user who made the assignment',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Sarah Williams',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'entity_old_status',
    name: 'old_status',
    label: 'Old Status',
    description: 'Previous status of the entity',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Inactive',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'entity_new_status',
    name: 'new_status',
    label: 'New Status',
    description: 'New status of the entity',
    dataType: 'string',
    context: 'entity',
    exampleValue: 'Active',
    isDynamic: false,
    isComputed: false,
  },

  // ── Users ──────────────────────────────────────────────────────────────────
  {
    id: 'users_user_name',
    name: 'user_name',
    label: 'User Name',
    description: 'Name of the user invited or updated',
    dataType: 'string',
    context: 'users',
    exampleValue: 'John Doe',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'users_user_email',
    name: 'user_email',
    label: 'User Email',
    description: 'Email address of the user',
    dataType: 'string',
    context: 'users',
    exampleValue: 'john.doe@example.com',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'users_temp_password',
    name: 'temp_password',
    label: 'Temporary Password',
    description: 'Temporary login password for the user',
    dataType: 'string',
    context: 'users',
    exampleValue: 'tEmpPa$$w0rd',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'users_login_link',
    name: 'login_link',
    label: 'Login Link',
    description: 'URL to log in or access the application',
    dataType: 'url',
    context: 'users',
    exampleValue: 'https://app.example.com/login',
    isDynamic: false,
    isComputed: false,
  },
  // ── Deal ──────────────────────────────────────────────────────────────────
  {
    id: 'deal_deal_name',
    name: 'deal_name',
    label: 'Deal Name',
    description: 'Name of the deal opportunity',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Lincoln Academy Expansion 2026',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'deal_deal_value',
    name: 'deal_value',
    label: 'Deal Value',
    description: 'Financial value of the deal',
    dataType: 'number',
    context: 'common',
    exampleValue: '15000',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'deal_deal_status',
    name: 'deal_status',
    label: 'Deal Status',
    description: 'Status of the deal (open, won, lost)',
    dataType: 'string',
    context: 'common',
    exampleValue: 'open',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'deal_deal_lost_reason',
    name: 'deal_lost_reason',
    label: 'Deal Lost Reason',
    description: 'Reason why the deal was closed lost',
    dataType: 'string',
    context: 'common',
    exampleValue: 'Price sensitivity',
    isDynamic: false,
    isComputed: false,
  },
  {
    id: 'deal_deal_expected_close_date',
    name: 'deal_deal_expected_close_date',
    label: 'Deal Expected Close Date',
    description: 'Estimated closing date of the deal',
    dataType: 'date',
    context: 'common',
    exampleValue: '2026-06-30',
    isDynamic: false,
    isComputed: false,
  },
];
