/**
 * @fileOverview CompanyBrain 2.0 Phase 10: Multi-Tenant Enterprise Security, Autonomous Intelligence & Continuous Self-Healing Governance
 *
 * ARCHITECTURAL GUIDELINES & CAUTION FOR MAINTAINERS (Rule 10):
 * 1. Apex Milestone of CompanyBrain 2.0:
 *    - Unifies all previous phases (Phases 1 to 9) into continuous, proactive organizational intelligence.
 * 2. Strict Zero-`any` & Zero-`unknown` Invariant (Rule 4):
 *    - All observation signals, recommendations, self-healing items, compliance audits, and federated
 *      benchmarks must be strictly typed using inferred module types, `McpPayloadValue`, or concrete interfaces.
 * 3. Human Authorization Invariant (Rule 1 / PRD Invariant 4):
 *    - Autonomous intelligence recommendations NEVER perform unsolicited external mutations.
 *    - Actions either require user adjudication or dispatch through Phase 9's ApprovalGateNode.
 * 4. Non-Destructive Self-Healing Invariant:
 *    - Memory health audits and drift repairs are reversible and non-destructive. Raw notes are never destroyed.
 * 5. Cryptographic Deletion Compliance:
 *    - Right-to-be-forgotten deletion cascades across Firestore, Qdrant vectors, and Graph edges, producing
 *      an immutable SHA-256 signed deletion certificate.
 *
 * @testability Covered in `src/lib/intelligence/__tests__/autonomous-intelligence.test.ts`.
 */

import type { McpPayloadValue } from '@/lib/mcp/types';

/**
 * Signal types extracted during autonomous observation sweeps.
 */
export type ObservationSignalType =
  | 'deal_stall'
  | 'sla_risk'
  | 'sentiment_dip'
  | 'champion_churn'
  | 'deal_acceleration'
  | 'cross_sell_signal'
  | 'knowledge_gap'
  | 'anomaly'
  | 'growth';

/**
 * Severity / Priority classification.
 */
export type IntelligenceSeverity = 'low' | 'medium' | 'high' | 'urgent';

/**
 * Lifecycle status of a proactive recommendation.
 */
export type RecommendationStatus = 'active' | 'dismissed' | 'acted_upon' | 'scheduled' | 'accepted';

/**
 * Recommendation categories.
 */
export type RecommendationType = 'risk' | 'opportunity' | 'governance' | 'trend';

/**
 * Atomic observation signal extracted from workspace activity.
 */
export interface ObservationFinding {
  id: string;
  type: ObservationSignalType;
  severity: IntelligenceSeverity;
  title: string;
  summary: string;
  description?: string;
  detectedAt: string;
  relatedEntityIds?: string[];
  relatedDealIds?: string[];
  affectedEntities?: string[];
  evidence?: string[];
}

/**
 * Macro organizational trend aggregated across a rolling time window.
 */
export interface ObservationTrend {
  id: string;
  topic: string;
  direction: 'increasing' | 'stable' | 'decreasing';
  velocityScore: number; // -1.0 to 1.0
  timeHorizonDays: 7 | 14 | 30 | 90;
  insights: string[];
}

/**
 * Action proposed for an autonomous recommendation.
 */
export interface RecommendedAction {
  actionType:
    | 'launch_workflow'
    | 'create_task'
    | 'schedule_review'
    | 'archive_memory'
    | 'notify_owner';
  workflowBlueprintId?: string;
  label: string;
  payloadTemplate?: Record<string, McpPayloadValue>;
}

/**
 * Proactive recommendation generated by the observation engine.
 */
export interface ProactiveRecommendation {
  id: string;
  workspaceId: string;
  organizationId: string;
  type: RecommendationType;
  priority: IntelligenceSeverity;
  severity?: IntelligenceSeverity;
  urgency?: string;
  title: string;
  description: string;
  reasoning: string;
  status: RecommendationStatus;
  recommendedAction: RecommendedAction;
  actionTrigger?: {
    type: string;
    target?: string;
  };
  confidence: number; // 0.0 to 1.0
  impactScore: number; // 1 to 10
  targetEntityId?: string;
  targetDealId?: string;
  createdAt: string;
  adjudicatedAt?: string;
  adjudicatedBy?: string;
  adjudicationNotes?: string;
  rejectionReason?: string;
}

/**
 * High-level executive intelligence summary for the workspace.
 */
export interface ExecutiveIntelligenceSummary {
  workspaceId?: string;
  overallHealthScore?: number; // 0 to 100
  healthScore?: number;
  knowledgeFreshnessRating?: number; // 0 to 100
  freshnessScore?: number;
  graphIntegrityScore?: number; // 0 to 100
  activeRiskCount?: number;
  activeRisksCount?: number;
  activeOpportunityCount?: number;
  emergingOpportunitiesCount?: number;
  staleMemoriesCount?: number;
  pendingConflictsCount?: number;
  pipelineVelocityTrend?: 'accelerating' | 'stable' | 'decelerating';
  agentEfficiencyIndex?: number; // 0 to 100
  agentEfficiencyRating?: number;
  lastObservationScanAt?: string;
  lastObservationScan?: string;
  emergingTrends?: ObservationTrend[];
}

/**
 * Specific action item within a self-healing memory maintenance plan.
 */
export interface SelfHealingActionItem {
  id: string;
  actionType:
    | 'archive_stale_memory'
    | 'reconcile_orphan_relation'
    | 'prune_orphan_edge'
    | 'reindex_vector'
    | 'resync_vector_embedding'
    | 'auto_resolve_conflict'
    | 'resolve_stale_conflict';
  targetId: string;
  title: string;
  rationale: string;
  severity: 'routine' | 'warning' | 'urgent';
  status: 'pending' | 'executed' | 'skipped';
  reversible: boolean;
  executedAt?: string;
}

/**
 * Durable record of a self-healing health audit stored in `/brain_health_audits`.
 */
export interface BrainHealthAudit {
  id: string;
  workspaceId: string;
  organizationId: string;
  healthScore: number;
  scannedMemoriesCount: number;
  staleMemoriesFound: number;
  orphanRelationsFound: number;
  unindexedVectorsFound: number;
  actionsProposed: SelfHealingActionItem[];
  pendingActions: SelfHealingActionItem[];
  actionsExecuted: number;
  createdAt: string;
  executedBy: string;
  metrics: {
    memoryFreshnessRating: number;
    graphIntegrityRating: number;
    vectorAlignmentRating: number;
    conflictResolutionRating: number;
  };
}

/**
 * SOC2 / GDPR verifiable compliance audit snapshot report.
 */
export interface ComplianceAuditReport {
  id: string;
  workspaceId: string;
  organizationId: string;
  subjectId?: string;
  subjectType?: string;
  totalMemoriesAudited: number;
  totalMemoriesEvaluated: number;
  totalVectorPointsAudited: number;
  totalGraphRelationsAudited: number;
  totalToolRunsAudited: number;
  tenantIsolationConfirmed: boolean;
  exportTimestamp: string;
  hashDigest: string;
  reportHash: string;
  scope: string;
  generatedBy: string;
  dataSummary: {
    memories: Array<{ id: string; contentPreview: string; category?: string }>;
    graphRelations: Array<{ id: string; relationType: string; sourceId: string; targetId: string }>;
    activeConflicts: Array<{ id: string; reason?: string; status: string }>;
  };
}

/**
 * Immutable cryptographic deletion certificate for GDPR Article 17 / CCPA erasure.
 */
export interface CryptographicDeletionCertificate {
  certificateId: string;
  workspaceId: string;
  organizationId: string;
  targetSubjectId: string;
  subjectId: string;
  targetSubjectType: string;
  subjectType: string;
  deletedMemoriesCount: number;
  deletedVectorsCount: number;
  deletedRelationsCount: number;
  sha256Digest: string;
  certificateHash: string;
  certifiedAt: string;
  operatorUserId: string;
  jurisdiction: 'GDPR_ARTICLE_17' | 'CCPA' | 'SOC2_DATA_RETENTION' | string;
  legalBasis: string;
  eradicationSummary: {
    memoriesDeleted: number;
    graphNodesRemoved: number;
    graphEdgesRemoved: number;
    vectorPointsDeleted: number;
  };
}

/**
 * Privacy-preserving federated benchmark metric comparing workspace metrics across cohorts.
 */
export interface FederatedBenchmarkMetric {
  metricKey: string;
  metricId: string;
  label: string;
  metricName: string;
  cohortIndustry: string;
  workspaceValue: number;
  tenantValue: number;
  cohortPercentile: number; // 0 to 100
  tenantPercentile: number;
  cohortMedian: number;
  industryAverage: number;
  cohortSampleCount: number;
  kAnonymityCount: number;
  privacyPreserved: boolean;
  privacyGuaranteed: boolean;
  unit: string;
}

/**
 * Request payload for triggering an observation scan.
 */
export interface ObservationScanRequest {
  workspaceId: string;
  organizationId: string;
  actorId?: string;
  forceFresh?: boolean;
  slidingWindowDays?: number;
}
