export const scratchTemplates = [
  // ── 0. Meeting Invitations (Series) ────────────────────────────────────
  {
    name: 'Initial Invitation (Email)', category: 'meetings', templateType: 'meeting_invitation_initial', channel: 'email',
    recipientType: 'external_alert',
    subject: 'You\'re Invited: {{meeting_title}} — {{meeting_date}}',
    body: `Dear {{contact_name}},\n\nWe would like to invite you to an upcoming session that has been organized for your benefit.\n\n📋 What: {{meeting_title}}\n📅 Date: {{meeting_date}}\n⏰ Time: {{meeting_time}} ({{meeting_timezone}})\n📍 Format: {{meeting_type}}\n\nThis session is designed to keep you informed about key developments and provide an opportunity for meaningful engagement. Your participation will make a difference.\n\n🔗 Register Now: [Click Here to Register]({{meeting_registrant_one_click_link}})\n📆 Add to Calendar: [Add to Calendar]({{calendar_link}})\n\nPlease confirm your attendance at your earliest convenience.\n\nWe look forward to welcoming you.\n\nBest regards,\n{{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['contact_name', 'meeting_title', 'meeting_date', 'meeting_time', 'meeting_timezone', 'meeting_type', 'meeting_registrant_one_click_link', 'calendar_link', 'org_name'],
  },
  {
    name: 'Initial Invitation (SMS)', category: 'meetings', templateType: 'meeting_invitation_initial', channel: 'sms',
    recipientType: 'external_alert',
    body: `Hi {{contact_name}}, you're invited to {{meeting_title}} on {{meeting_date}} at {{meeting_time}} ({{meeting_timezone}}). Register: {{meeting_registrant_one_click_link}} — {{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['contact_name', 'meeting_title', 'meeting_date', 'meeting_time', 'meeting_timezone', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: '1 Month Before Invitation (Email)', category: 'meetings', templateType: 'meeting_invitation_1_month', channel: 'email',
    recipientType: 'external_alert',
    subject: 'Upcoming in 1 Month: {{meeting_title}}',
    body: `Dear {{contact_name}},\n\nJust a quick heads up that {{meeting_title}} is coming up in one month on {{meeting_date}}.\n\n🔗 Secure Your Spot: [Click Here to Register]({{meeting_registrant_one_click_link}})\n\n{{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['contact_name', 'meeting_title', 'meeting_date', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: '1 Month Before Invitation (SMS)', category: 'meetings', templateType: 'meeting_invitation_1_month', channel: 'sms',
    recipientType: 'external_alert',
    body: `Hi {{contact_name}}, {{meeting_title}} is coming up in a month on {{meeting_date}}. Secure your spot: {{meeting_registrant_one_click_link}} — {{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['contact_name', 'meeting_title', 'meeting_date', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: '1 Week Before Invitation (Email)', category: 'meetings', templateType: 'meeting_invitation_1_week', channel: 'email',
    recipientType: 'external_alert',
    subject: 'Next Week: {{meeting_title}}',
    body: `Dear {{contact_name}},\n\n{{meeting_title}} is happening next week!\n\nIf you haven't yet, please confirm your attendance.\n\n🔗 Register Now: [Click Here to Register]({{meeting_registrant_one_click_link}})\n\n{{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['contact_name', 'meeting_title', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: '1 Week Before Invitation (SMS)', category: 'meetings', templateType: 'meeting_invitation_1_week', channel: 'sms',
    recipientType: 'external_alert',
    body: `Next week: {{meeting_title}}. Don't miss out, register today: {{meeting_registrant_one_click_link}} — {{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['meeting_title', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: '5 Days Before Invitation (Email)', category: 'meetings', templateType: 'meeting_invitation_5_days', channel: 'email',
    recipientType: 'external_alert',
    subject: 'Only 5 Days Away: {{meeting_title}}',
    body: `Dear {{contact_name}},\n\nWe are just 5 days away from {{meeting_title}}.\n\n🔗 Claim Your Spot: [Register Here]({{meeting_registrant_one_click_link}})\n\n{{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['contact_name', 'meeting_title', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: '5 Days Before Invitation (SMS)', category: 'meetings', templateType: 'meeting_invitation_5_days', channel: 'sms',
    recipientType: 'external_alert',
    body: `Only 5 days until {{meeting_title}}! Register now: {{meeting_registrant_one_click_link}} — {{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['meeting_title', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: '3 Days Before Invitation (Email)', category: 'meetings', templateType: 'meeting_invitation_3_days', channel: 'email',
    recipientType: 'external_alert',
    subject: 'Don\'t Miss Out: {{meeting_title}} in 3 Days',
    body: `Dear {{contact_name}},\n\n{{meeting_title}} is approaching quickly.\n\n🔗 Please Register: [Register Here]({{meeting_registrant_one_click_link}})\n\n{{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['contact_name', 'meeting_title', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: '3 Days Before Invitation (SMS)', category: 'meetings', templateType: 'meeting_invitation_3_days', channel: 'sms',
    recipientType: 'external_alert',
    body: `3 days left until {{meeting_title}}! Register today: {{meeting_registrant_one_click_link}} — {{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['meeting_title', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: '2 Days Before Invitation (Email)', category: 'meetings', templateType: 'meeting_invitation_2_days', channel: 'email',
    recipientType: 'external_alert',
    subject: 'Approaching: {{meeting_title}} in 2 Days',
    body: `Dear {{contact_name}},\n\nWe noticed you haven't RSVP'd to {{meeting_title}} yet.\n\n🔗 Register Now: [Register Here]({{meeting_registrant_one_click_link}})\n\n{{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['contact_name', 'meeting_title', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: '2 Days Before Invitation (SMS)', category: 'meetings', templateType: 'meeting_invitation_2_days', channel: 'sms',
    recipientType: 'external_alert',
    body: `{{meeting_title}} is in 2 days. Secure your spot: {{meeting_registrant_one_click_link}} — {{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['meeting_title', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: '1 Day Before Invitation (Email)', category: 'meetings', templateType: 'meeting_invitation_1_day', channel: 'email',
    recipientType: 'external_alert',
    subject: 'Tomorrow: {{meeting_title}}',
    body: `Dear {{contact_name}},\n\n{{meeting_title}} is happening tomorrow!\n\n🔗 Register Now: [Register Here]({{meeting_registrant_one_click_link}})\n\n{{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['contact_name', 'meeting_title', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: '1 Day Before Invitation (SMS)', category: 'meetings', templateType: 'meeting_invitation_1_day', channel: 'sms',
    recipientType: 'external_alert',
    body: `Tomorrow: {{meeting_title}}. Register now: {{meeting_registrant_one_click_link}} — {{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['meeting_title', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: 'Happening Today Invitation (Email)', category: 'meetings', templateType: 'meeting_invitation_today', channel: 'email',
    recipientType: 'external_alert',
    subject: 'Today: {{meeting_title}}',
    body: `Dear {{contact_name}},\n\n{{meeting_title}} is happening today at {{meeting_time}}!\n\n🔗 Register to join us: [Register Here]({{meeting_registrant_one_click_link}})\n\n{{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['contact_name', 'meeting_title', 'meeting_time', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: 'Happening Today Invitation (SMS)', category: 'meetings', templateType: 'meeting_invitation_today', channel: 'sms',
    recipientType: 'external_alert',
    body: `{{meeting_title}} is today at {{meeting_time}}. Register to join: {{meeting_registrant_one_click_link}} — {{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['meeting_title', 'meeting_time', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: 'Last Chance Invitation (Email)', category: 'meetings', templateType: 'meeting_invitation_last_chance', channel: 'email',
    recipientType: 'external_alert',
    subject: 'Last Chance to Join: {{meeting_title}}',
    body: `Dear {{contact_name}},\n\nThis is your last chance to register for {{meeting_title}}, starting very soon.\n\n🔗 Register Now: [Register Here]({{meeting_registrant_one_click_link}})\n\n{{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['contact_name', 'meeting_title', 'meeting_registrant_one_click_link', 'org_name'],
  },
  {
    name: 'Last Chance Invitation (SMS)', category: 'meetings', templateType: 'meeting_invitation_last_chance', channel: 'sms',
    recipientType: 'external_alert',
    body: `Last chance to join {{meeting_title}}! Register here: {{meeting_registrant_one_click_link}} — {{org_name}}`,
    variableContext: 'meeting', declaredVariables: ['meeting_title', 'meeting_registrant_one_click_link', 'org_name'],
  },
];
