'use client';

/**
 * @fileoverview Deal AI Intelligence & Next-Best-Action Panel
 *
 * ARCHITECTURAL POINTER (AI Co-Pilot Workspace):
 * Provides AI-driven revenue intelligence directly within the Deal Workspace:
 * - Executive summary & strategic synthesis.
 * - Win Probability scoring & driver analysis.
 * - Identified risk factor breakdown.
 * - 3 prioritized next-best-actions with 1-click Task Creation.
 *
 * CAUTION FOR FUTURE MAINTAINERS:
 * - Next best actions must convert seamlessly to workspace tasks.
 * - Zero 'any' or 'any[]' in types.
 *
 * TESTABILITY POINTER:
 * Verify generating insights displays summary and clicking 'Add as Task' calls createTaskAction.
 */

import * as React from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  Sparkles, 
  TrendingUp, 
  AlertTriangle, 
  CheckCircle2, 
  Loader2, 
  Bot, 
  ListPlus, 
  Plus 
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { useUser } from '@/firebase';
import { useWorkspace } from '@/context/WorkspaceContext';
import { generateDealAiInsightsAction, type DealAiInsightsResult } from '@/app/actions/deal-ai-actions';
import { createTaskAction } from '@/lib/task-server-actions';
import type { Deal } from '@/lib/types';

interface DealAiIntelligencePanelProps {
  deal: Deal;
  onTaskCreated?: () => void;
}

export default function DealAiIntelligencePanel({ deal, onTaskCreated }: DealAiIntelligencePanelProps) {
  const { user } = useUser();
  const { activeWorkspaceId } = useWorkspace();
  const { toast } = useToast();

  const [isLoading, setIsLoading] = React.useState(false);
  const [insights, setInsights] = React.useState<DealAiInsightsResult['insights'] | null>(null);
  const [creatingTaskIndex, setCreatingTaskIndex] = React.useState<number | null>(null);

  const handleGenerateInsights = async () => {
    if (!deal.id || !activeWorkspaceId) return;
    setIsLoading(true);

    try {
      const res = await generateDealAiInsightsAction(deal.id, activeWorkspaceId, user?.uid);
      if (res.success && res.insights) {
        setInsights(res.insights);
        toast({
          title: 'Intelligence Generated',
          description: 'Deal analysis and recommended actions updated.',
        });
      } else {
        throw new Error(res.error || 'Failed to generate intelligence');
      }
    } catch (e: unknown) {
      const error = e instanceof Error ? e.message : 'Unknown error';
      toast({ variant: 'destructive', title: 'AI Analysis Failed', description: error });
    } finally {
      setIsLoading(false);
    }
  };

  const handleCreateTaskFromAction = async (action: { title: string; rationale: string; priority: 'high' | 'medium' | 'low' }, index: number) => {
    if (!deal.id || !activeWorkspaceId) return;
    setCreatingTaskIndex(index);

    try {
      const dueDate = new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString();
      const res = await createTaskAction({
        workspaceId: activeWorkspaceId,
        organizationId: deal.organizationId,
        title: action.title,
        description: `Generated by AI Deal Intelligence for deal "${deal.name}":\n\nRationale: ${action.rationale}`,
        priority: action.priority,
        status: 'todo',
        category: 'general',
        dueDate,
        entityId: deal.entityId,
        assignedTo: deal.assignedTo?.userId || user?.uid || '',
        relatedEntityType: 'Deal',
        relatedEntityId: deal.id,
        reminders: [],
        reminderSent: false,
      }, user?.uid || 'system');

      if (res.success) {
        toast({
          title: 'Task Created',
          description: `"${action.title}" added to your workspace tasks.`,
        });
        if (onTaskCreated) onTaskCreated();
      } else {
        throw new Error(res.error || 'Failed to create task');
      }
    } catch (e: unknown) {
      const error = e instanceof Error ? e.message : 'Unknown error';
      toast({ variant: 'destructive', title: 'Task Creation Failed', description: error });
    } finally {
      setCreatingTaskIndex(null);
    }
  };

  return (
    <Card className="border-border/50 rounded-2xl bg-card shadow-sm overflow-hidden">
      <CardHeader className="border-b bg-gradient-to-r from-primary/10 via-card to-background pb-4 px-6 pt-5 flex flex-row items-center justify-between">
        <div className="space-y-0.5">
          <CardTitle className="text-sm font-bold flex items-center gap-2 text-foreground">
            <Bot className="h-4 w-4 text-primary" />
            <span>AI Deal Intelligence & Next Best Actions</span>
          </CardTitle>
          <p className="text-xs text-muted-foreground">
            Machine intelligence evaluating deal velocity, stakeholder notes, and closing probability.
          </p>
        </div>

        <Button
          type="button"
          onClick={handleGenerateInsights}
          disabled={isLoading}
          className="h-9 rounded-xl font-bold text-xs bg-primary text-primary-foreground shadow-sm gap-1.5 shrink-0"
        >
          {isLoading ? (
            <>
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
              <span>Analyzing Deal...</span>
            </>
          ) : (
            <>
              <Sparkles className="h-3.5 w-3.5" />
              <span>{insights ? 'Refresh Insights' : 'Analyze Deal'}</span>
            </>
          )}
        </Button>
      </CardHeader>

      <CardContent className="p-6">
        {insights ? (
          <div className="space-y-6">
            {/* Executive Summary */}
            <div className="p-4 rounded-2xl bg-primary/5 border border-primary/20 space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-xs font-black uppercase tracking-wider text-primary flex items-center gap-1.5">
                  <Sparkles className="h-3.5 w-3.5" />
                  Executive Synthesis
                </span>
                <Badge variant="outline" className="text-[10px] font-bold capitalize">
                  {insights.dealHealthAssessment} Health
                </Badge>
              </div>
              <p className="text-xs text-foreground/90 leading-relaxed">
                {insights.executiveSummary}
              </p>
            </div>

            {/* Win Probability & Risk Factors Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Win Drivers */}
              <div className="p-4 rounded-2xl bg-emerald-500/5 border border-emerald-500/20 space-y-2.5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-emerald-600 dark:text-emerald-400 flex items-center gap-1.5">
                    <TrendingUp className="h-3.5 w-3.5" />
                    Win Probability: {insights.winProbability}%
                  </span>
                </div>
                <ul className="space-y-1.5 text-xs text-muted-foreground">
                  {insights.winDrivers.map((driver, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500 shrink-0 mt-0.5" />
                      <span>{driver}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Risk Factors */}
              <div className="p-4 rounded-2xl bg-amber-500/5 border border-amber-500/20 space-y-2.5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-amber-600 dark:text-amber-400 flex items-center gap-1.5">
                    <AlertTriangle className="h-3.5 w-3.5" />
                    Identified Risk Factors
                  </span>
                </div>
                <ul className="space-y-1.5 text-xs text-muted-foreground">
                  {insights.riskFactors.map((risk, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="h-1.5 w-1.5 rounded-full bg-amber-500 shrink-0 mt-1.5" />
                      <span>{risk}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Next Best Actions */}
            <div className="space-y-3">
              <h4 className="text-xs font-black uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                <ListPlus className="h-4 w-4 text-primary" />
                Recommended Next-Best Actions ({insights.nextBestActions.length})
              </h4>

              <div className="space-y-2.5">
                {insights.nextBestActions.map((action, i) => (
                  <div 
                    key={i}
                    className="p-4 rounded-2xl bg-muted/20 border border-border/60 hover:border-primary/30 transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-3"
                  >
                    <div className="space-y-1 min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-xs text-foreground">{action.title}</span>
                        <Badge variant="outline" className="text-[9px] font-bold uppercase px-1.5 py-0 h-4">
                          {action.priority} Priority
                        </Badge>
                      </div>
                      <p className="text-[11px] text-muted-foreground leading-relaxed">
                        {action.rationale}
                      </p>
                    </div>

                    <Button
                      type="button"
                      size="sm"
                      variant="outline"
                      onClick={() => handleCreateTaskFromAction(action, i)}
                      disabled={creatingTaskIndex === i}
                      className="h-8 rounded-xl font-bold text-[11px] border-primary/30 text-primary hover:bg-primary/10 shrink-0 gap-1.5"
                    >
                      {creatingTaskIndex === i ? (
                        <Loader2 className="h-3 w-3 animate-spin" />
                      ) : (
                        <Plus className="h-3 w-3" />
                      )}
                      Add as Task
                    </Button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : (
          <div className="text-center py-10 bg-muted/10 rounded-2xl border border-dashed flex flex-col items-center justify-center gap-3">
            <Bot className="h-10 w-10 text-muted-foreground/30" />
            <div className="space-y-1">
              <p className="text-xs font-bold text-foreground">AI Intelligence Ready</p>
              <p className="text-[11px] text-muted-foreground max-w-sm">
                Click &quot;Analyze Deal&quot; to generate grounded win drivers, risk factors, and recommended next-best actions.
              </p>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
