'use client';

/**
 * @fileoverview Deal AI Intelligence & Next-Best-Action Panel
 *
 * ARCHITECTURAL POINTER (AI Co-Pilot Workspace):
 * Provides AI-driven revenue intelligence directly within the Deal Workspace:
 * - Executive summary & strategic synthesis.
 * - Win Probability scoring & driver analysis.
 * - Identified risk factor breakdown.
 * - 3 prioritized next-best-actions with 1-click Task Creation.
 *
 * CAUTION FOR FUTURE MAINTAINERS:
 * - Next best actions must convert seamlessly to workspace tasks.
 * - Zero 'any' or 'any[]' in types.
 *
 * TESTABILITY POINTER:
 * Verify generating insights displays summary and clicking 'Add as Task' calls createTaskAction.
 */

import * as React from 'react';
import Link from 'next/link';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  Sparkles, 
  TrendingUp, 
  AlertTriangle, 
  CheckCircle2, 
  Loader2, 
  Bot, 
  ListPlus, 
  Plus,
  Compass,
  Workflow,
  LayoutDashboard,
  MoreHorizontal,
  ArrowUpRight
} from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { CardInfoTooltip } from '@/components/shared/CardInfoTooltip';
import { useToast } from '@/hooks/use-toast';
import { useUser } from '@/firebase';
import { useWorkspace } from '@/context/WorkspaceContext';
import { generateDealAiInsightsAction, type DealAiInsightsResult } from '@/app/actions/deal-ai-actions';
import { getDealIntelligenceAction, type CrmActionResult } from '@/app/actions/crm-agent-actions';
import { DealIntelligenceCard } from '@/components/crm/intelligence';
import type { DealIntelligence } from '@/platform/agents/crm/intelligence/crm-intelligence-types';
import { createTaskAction } from '@/lib/task-server-actions';
import type { Deal } from '@/lib/types';

interface DealAiIntelligencePanelProps {
  deal: Deal;
  onTaskCreated?: () => void;
}

export default function DealAiIntelligencePanel({ deal, onTaskCreated }: DealAiIntelligencePanelProps) {
  const { user } = useUser();
  const { activeWorkspaceId } = useWorkspace();
  const { toast } = useToast();

  const [isLoading, setIsLoading] = React.useState(false);
  const [insights, setInsights] = React.useState<DealAiInsightsResult['insights'] | null>(null);
  const [phase9Intel, setPhase9Intel] = React.useState<DealIntelligence | null>(null);
  const [creatingTaskIndex, setCreatingTaskIndex] = React.useState<number | null>(null);

  const handleGenerateInsights = async () => {
    if (!deal.id || !activeWorkspaceId) return;
    setIsLoading(true);

    try {
      const p9Promise: Promise<CrmActionResult<DealIntelligence>> = deal.entityId
        ? getDealIntelligenceAction({ workspaceId: activeWorkspaceId, entityId: deal.entityId, dealId: deal.id })
        : Promise.resolve({ success: false, error: { code: 'NO_ENTITY_ID', message: 'No entity ID' } });

      const [res, p9Res] = await Promise.all([
        generateDealAiInsightsAction(deal.id, activeWorkspaceId, user?.uid),
        p9Promise,
      ]);

      if (p9Res.success && p9Res.data) {
        setPhase9Intel(p9Res.data);
      }

      if (res.success && res.insights) {
        setInsights(res.insights);
        toast({
          title: 'Intelligence Generated',
          description: 'Deal analysis and recommended actions updated.',
        });
      } else if (!p9Res.success) {
        throw new Error(res.error || 'Failed to generate intelligence');
      }
    } catch (e: unknown) {
      const error = e instanceof Error ? e.message : 'Unknown error';
      toast({ variant: 'destructive', title: 'AI Analysis Failed', description: error });
    } finally {
      setIsLoading(false);
    }
  };

  const handleCreateTaskFromAction = async (action: { title: string; rationale: string; priority: 'high' | 'medium' | 'low' }, index: number) => {
    if (!deal.id || !activeWorkspaceId) return;
    setCreatingTaskIndex(index);

    try {
      const dueDate = new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString();
      const res = await createTaskAction({
        workspaceId: activeWorkspaceId,
        organizationId: deal.organizationId,
        title: action.title,
        description: `Generated by AI Deal Intelligence for deal "${deal.name}":\n\nRationale: ${action.rationale}`,
        priority: action.priority,
        status: 'todo',
        category: 'general',
        dueDate,
        entityId: deal.entityId,
        assignedTo: deal.assignedTo?.userId || user?.uid || '',
        relatedEntityType: 'Deal',
        relatedEntityId: deal.id,
        reminders: [],
        reminderSent: false,
      });

      if (res.success) {
        toast({
          title: 'Task Created',
          description: `"${action.title}" added to your workspace tasks.`,
        });
        if (onTaskCreated) onTaskCreated();
      } else {
        throw new Error(res.error || 'Failed to create task');
      }
    } catch (e: unknown) {
      const error = e instanceof Error ? e.message : 'Unknown error';
      toast({ variant: 'destructive', title: 'Task Creation Failed', description: error });
    } finally {
      setCreatingTaskIndex(null);
    }
  };

  return (
    <Card className="border-border/50 rounded-2xl bg-card shadow-sm overflow-hidden">
      <CardHeader className="bg-muted/30 border-b h-[60px] min-h-[60px] px-6 py-0 flex flex-row items-center justify-between gap-3">
        <div className="flex items-center gap-3 min-w-0">
          <div className="p-1.5 bg-primary/10 rounded-lg shrink-0">
            <Bot className="h-4 w-4 text-primary" />
          </div>
          <CardTitle className="text-sm sm:text-base font-semibold tracking-tight flex items-center gap-2 text-foreground truncate">
            <span>AI Deal Intelligence & Next Best Actions</span>
            <CardInfoTooltip text="Machine intelligence evaluating deal velocity, stakeholder notes, and closing probability." />
          </CardTitle>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          {/* Exactly One Hero Action Button */}
          <Button
            type="button"
            size="sm"
            onClick={handleGenerateInsights}
            disabled={isLoading}
            className="h-9 px-3.5 rounded-xl font-bold text-xs bg-primary text-primary-foreground shadow-sm gap-1.5 shrink-0 active:scale-[0.97] transition-all cursor-pointer"
          >
            {isLoading ? (
              <>
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
                <span>Analyzing Deal...</span>
              </>
            ) : (
              <>
                <Sparkles className="h-3.5 w-3.5" />
                <span>{insights ? 'Refresh Insights' : 'Analyze Deal'}</span>
              </>
            )}
          </Button>

          {/* Doughnut Menu for Secondary Commands */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                type="button"
                variant="outline"
                size="icon"
                className="h-9 w-9 rounded-xl border border-border/80 hover:bg-muted/50 text-muted-foreground hover:text-foreground active:scale-[0.97] transition-all cursor-pointer"
                title="More intelligence actions"
                aria-label="More intelligence actions"
              >
                <MoreHorizontal className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-56 rounded-xl p-1 shadow-xl">
              <DropdownMenuItem asChild className="p-2 rounded-lg cursor-pointer text-xs font-semibold">
                <Link href="/admin/revenue-forecasting" className="flex items-center justify-between w-full">
                  <div className="flex items-center gap-2">
                    <TrendingUp className="h-3.5 w-3.5 text-emerald-600 dark:text-emerald-400" />
                    <span>Forecast Cockpit</span>
                  </div>
                  <ArrowUpRight className="h-3.5 w-3.5 opacity-60" />
                </Link>
              </DropdownMenuItem>
              <DropdownMenuItem asChild className="p-2 rounded-lg cursor-pointer text-xs font-semibold">
                <Link href="/admin/deal-intelligence" className="flex items-center justify-between w-full">
                  <div className="flex items-center gap-2">
                    <Compass className="h-3.5 w-3.5 text-primary" />
                    <span>Deal Intelligence</span>
                  </div>
                  <ArrowUpRight className="h-3.5 w-3.5 opacity-60" />
                </Link>
              </DropdownMenuItem>
              <DropdownMenuItem asChild className="p-2 rounded-lg cursor-pointer text-xs font-semibold">
                <Link href="/admin/sales-orchestration" className="flex items-center justify-between w-full">
                  <div className="flex items-center gap-2">
                    <Workflow className="h-3.5 w-3.5 text-indigo-500" />
                    <span>Sales Plays</span>
                  </div>
                  <ArrowUpRight className="h-3.5 w-3.5 opacity-60" />
                </Link>
              </DropdownMenuItem>
              <DropdownMenuItem asChild className="p-2 rounded-lg cursor-pointer text-xs font-semibold">
                <Link href="/admin/revenue-operating-system" className="flex items-center justify-between w-full">
                  <div className="flex items-center gap-2">
                    <LayoutDashboard className="h-3.5 w-3.5 text-amber-500" />
                    <span>Revenue OS</span>
                  </div>
                  <ArrowUpRight className="h-3.5 w-3.5 opacity-60" />
                </Link>
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </CardHeader>

      <CardContent className="p-6 space-y-6">
        {phase9Intel && (
          <DealIntelligenceCard dealIntelligence={phase9Intel} />
        )}
        {insights ? (
          <div className="space-y-6">
            {/* Executive Summary */}
            <div className="p-4 rounded-2xl bg-primary/5 border border-primary/20 space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-xs font-black uppercase tracking-wider text-primary flex items-center gap-1.5">
                  <Sparkles className="h-3.5 w-3.5" />
                  Executive Synthesis
                </span>
                <Badge variant="outline" className="text-[10px] font-bold capitalize">
                  {insights.dealHealthAssessment} Health
                </Badge>
              </div>
              <p className="text-xs text-foreground/90 leading-relaxed">
                {insights.executiveSummary}
              </p>
            </div>

            {/* Win Probability & Risk Factors Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Win Drivers */}
              <div className="p-4 rounded-2xl bg-emerald-500/5 border border-emerald-500/20 space-y-2.5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-emerald-600 dark:text-emerald-400 flex items-center gap-1.5">
                    <TrendingUp className="h-3.5 w-3.5" />
                    Win Probability: {insights.winProbability}%
                  </span>
                </div>
                <ul className="space-y-1.5 text-xs text-muted-foreground">
                  {insights.winDrivers.map((driver, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500 shrink-0 mt-0.5" />
                      <span>{driver}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Risk Factors */}
              <div className="p-4 rounded-2xl bg-amber-500/5 border border-amber-500/20 space-y-2.5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-amber-600 dark:text-amber-400 flex items-center gap-1.5">
                    <AlertTriangle className="h-3.5 w-3.5" />
                    Identified Risk Factors
                  </span>
                </div>
                <ul className="space-y-1.5 text-xs text-muted-foreground">
                  {insights.riskFactors.map((risk, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="h-1.5 w-1.5 rounded-full bg-amber-500 shrink-0 mt-1.5" />
                      <span>{risk}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Pricing Health & Commercial Recommendation Cards */}
            {insights.pricingHealth && (
              <div className="p-4 rounded-2xl bg-card border border-border/70 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-foreground flex items-center gap-1.5">
                    <Sparkles className="h-3.5 w-3.5 text-primary" />
                    Commercial Margin & Pricing Assessment
                  </span>
                  <Badge 
                    variant="outline" 
                    className={`text-[9px] font-black uppercase px-2 py-0.5 ${
                      insights.pricingHealth.marginRating === 'optimal' 
                        ? 'border-emerald-500/30 text-emerald-600 bg-emerald-500/10'
                        : insights.pricingHealth.marginRating === 'discount_heavy'
                        ? 'border-amber-500/30 text-amber-600 bg-amber-500/10'
                        : 'border-blue-500/30 text-blue-600 bg-blue-500/10'
                    }`}
                  >
                    {insights.pricingHealth.marginRating.replace('_', ' ')}
                  </Badge>
                </div>
                <p className="text-[11px] text-muted-foreground leading-relaxed">
                  {insights.pricingHealth.assessmentNotes}
                </p>
              </div>
            )}

            {/* Recommended Products & Upsells */}
            {insights.recommendedProducts && insights.recommendedProducts.length > 0 && (
              <div className="space-y-3">
                <h4 className="text-xs font-black uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                  <Sparkles className="h-4 w-4 text-primary" />
                  Recommended Catalog Offerings ({insights.recommendedProducts.length})
                </h4>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {insights.recommendedProducts.map((prod, idx) => (
                    <div key={idx} className="p-3.5 rounded-2xl bg-muted/20 border border-border/60 space-y-1.5">
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-xs text-foreground">{prod.name}</span>
                        <Badge variant="outline" className="text-[9px] font-bold">Qty: {prod.suggestedQuantity}</Badge>
                      </div>
                      <p className="text-[11px] text-muted-foreground leading-relaxed">
                        {prod.rationale}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Next Best Actions */}
            <div className="space-y-3">
              <h4 className="text-xs font-black uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                <ListPlus className="h-4 w-4 text-primary" />
                Recommended Next-Best Actions ({insights.nextBestActions.length})
              </h4>

              <div className="space-y-2.5">
                {insights.nextBestActions.map((action, i) => (
                  <div 
                    key={i}
                    className="p-4 rounded-2xl bg-muted/20 border border-border/60 hover:border-primary/30 transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-3"
                  >
                    <div className="space-y-1 min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-xs text-foreground">{action.title}</span>
                        <Badge variant="outline" className="text-[9px] font-bold uppercase px-1.5 py-0 h-4">
                          {action.priority} Priority
                        </Badge>
                      </div>
                      <p className="text-[11px] text-muted-foreground leading-relaxed">
                        {action.rationale}
                      </p>
                    </div>

                    <Button
                      type="button"
                      size="sm"
                      variant="outline"
                      onClick={() => handleCreateTaskFromAction(action, i)}
                      disabled={creatingTaskIndex === i}
                      className="h-8 rounded-xl font-bold text-[11px] border-primary/30 text-primary hover:bg-primary/10 shrink-0 gap-1.5"
                    >
                      {creatingTaskIndex === i ? (
                        <Loader2 className="h-3 w-3 animate-spin" />
                      ) : (
                        <Plus className="h-3 w-3" />
                      )}
                      Add as Task
                    </Button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : !phase9Intel ? (
          <div className="text-center py-10 bg-muted/10 rounded-2xl border border-dashed flex flex-col items-center justify-center gap-3">
            <Bot className="h-10 w-10 text-muted-foreground/30" />
            <div className="space-y-1">
              <p className="text-xs font-bold text-foreground">AI Intelligence Ready</p>
              <p className="text-[11px] text-muted-foreground max-w-sm">
                Click &quot;Analyze Deal&quot; to generate grounded win drivers, risk factors, and recommended next-best actions.
              </p>
            </div>
          </div>
        ) : null}
      </CardContent>
    </Card>
  );
}
