'use client';

/**
 * @fileOverview AI Recommendations Feed Component (Phase 8)
 *
 * Renders actionable recommendations generated by AI Role & Access Advisors
 * with empirical evidence, risk deltas, and 1-click execution triggers.
 *
 * ARCHITECTURAL GUIDANCE FOR MAINTAINERS:
 * - Employs Radix Accordion / Cards and Emil Kowalski spring easing on actions.
 * - Zero `any` or `any[]` typing.
 */

import * as React from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Sparkles,
  ShieldAlert,
  CheckCircle2,
  XCircle,
  Loader2,
  TrendingDown,
  ArrowRight,
  Info,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import type { AiWorkforceRecommendation, AiRecommendationPriority } from '@/lib/types';

interface AiRecommendationsFeedProps {
  recommendations: AiWorkforceRecommendation[];
  isLoading: boolean;
  onApply: (rec: AiWorkforceRecommendation) => Promise<void>;
  onDismiss: (rec: AiWorkforceRecommendation) => Promise<void>;
}

export function AiRecommendationsFeed({
  recommendations,
  isLoading,
  onApply,
  onDismiss,
}: AiRecommendationsFeedProps) {
  const [applyingId, setApplyingId] = React.useState<string | null>(null);
  const [dismissingId, setDismissingId] = React.useState<string | null>(null);

  const handleApply = async (rec: AiWorkforceRecommendation) => {
    setApplyingId(rec.id);
    try {
      await onApply(rec);
    } finally {
      setApplyingId(null);
    }
  };

  const handleDismiss = async (rec: AiWorkforceRecommendation) => {
    setDismissingId(rec.id);
    try {
      await onDismiss(rec);
    } finally {
      setDismissingId(null);
    }
  };

  const priorityBadge = (prio: AiRecommendationPriority) => {
    switch (prio) {
      case 'critical':
        return <Badge variant="destructive" className="text-[9px] uppercase tracking-wider font-bold">Critical</Badge>;
      case 'high':
        return <Badge variant="outline" className="text-[9px] uppercase tracking-wider font-bold bg-rose-500/10 text-rose-600 border-rose-500/30">High</Badge>;
      case 'medium':
        return <Badge variant="outline" className="text-[9px] uppercase tracking-wider font-bold bg-amber-500/10 text-amber-600 border-amber-500/30">Medium</Badge>;
      case 'low':
        return <Badge variant="outline" className="text-[9px] uppercase tracking-wider font-bold bg-blue-500/10 text-blue-600 border-blue-500/30">Low</Badge>;
    }
  };

  return (
    <Card className="border bg-card shadow-xs overflow-hidden">
      <CardHeader className="p-4 pb-3 border-b bg-muted/20 flex flex-row items-center justify-between">
        <div className="flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-primary" />
          <div>
            <CardTitle className="text-sm font-bold">AI Access & Role Advisor</CardTitle>
            <CardDescription className="text-xs">
              Actionable least-privilege pruning, SoD conflict remediation, and portfolio balancing
            </CardDescription>
          </div>
        </div>
      </CardHeader>

      <div className="divide-y divide-border/60">
        {isLoading ? (
          Array.from({ length: 3 }).map((_, i) => (
            <div key={i} className="p-4 space-y-2">
              <div className="h-4 bg-muted/40 animate-pulse rounded-md w-1/3" />
              <div className="h-3 bg-muted/30 animate-pulse rounded-md w-2/3" />
            </div>
          ))
        ) : recommendations.length > 0 ? (
          recommendations.map((rec) => (
            <div key={rec.id} className="p-4 hover:bg-muted/10 transition-colors space-y-3">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div className="flex items-center gap-2 flex-wrap">
                  {priorityBadge(rec.priority)}
                  <h4 className="text-xs font-bold text-foreground">{rec.title}</h4>
                </div>

                <Badge variant="secondary" className="text-[10px] w-fit font-semibold text-emerald-600 dark:text-emerald-400 bg-emerald-500/10 border-emerald-500/20">
                  <TrendingDown className="w-3 h-3 mr-1 inline" /> Risk Delta: {rec.riskDelta} pts
                </Badge>
              </div>

              <p className="text-xs text-muted-foreground">{rec.explanation}</p>

              {/* Evidence Pills */}
              <div className="p-2.5 bg-muted/30 border rounded-lg space-y-1">
                <span className="text-[10px] uppercase font-bold text-muted-foreground flex items-center gap-1">
                  <Info className="w-3 h-3 text-primary" /> Empirical Evidence (90-Day Telemetry)
                </span>
                <ul className="text-[11px] text-foreground space-y-0.5 list-disc list-inside">
                  {rec.evidence.map((ev, i) => (
                    <li key={i}>{ev}</li>
                  ))}
                </ul>
              </div>

              {/* Action Buttons */}
              <div className="flex items-center justify-end gap-2 pt-1">
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={() => handleDismiss(rec)}
                  disabled={Boolean(dismissingId || applyingId)}
                  className="text-xs h-8 px-3 text-muted-foreground active:scale-[0.97]"
                >
                  {dismissingId === rec.id ? (
                    <Loader2 className="w-3 h-3 mr-1 animate-spin" />
                  ) : (
                    <XCircle className="w-3 h-3 mr-1 text-muted-foreground" />
                  )}
                  Dismiss
                </Button>

                <Button
                  type="button"
                  size="sm"
                  onClick={() => handleApply(rec)}
                  disabled={Boolean(dismissingId || applyingId)}
                  className="text-xs h-8 px-3.5 font-semibold active:scale-[0.97]"
                >
                  {applyingId === rec.id ? (
                    <>
                      <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" /> Applying...
                    </>
                  ) : (
                    <>
                      <CheckCircle2 className="w-3.5 h-3.5 mr-1.5" /> Apply Recommendation
                    </>
                  )}
                </Button>
              </div>
            </div>
          ))
        ) : (
          <div className="p-8 text-center text-xs text-muted-foreground space-y-1">
            <CheckCircle2 className="w-6 h-6 text-emerald-500 mx-auto mb-2" />
            <p className="font-semibold text-foreground">Zero Active Risk Recommendations</p>
            <p>Workforce access profiles and role assignments are least-privilege compliant.</p>
          </div>
        )}
      </div>
    </Card>
  );
}

export default AiRecommendationsFeed;
