'use client';

/**
 * @fileOverview CompanyBrain 2.0: Explain Connection AI Dialog
 *
 * ARCHITECTURAL GUIDELINES & CAUTION FOR MAINTAINERS (Rule 10):
 * 1. Deep Grounded Relationship Attribution (PRD Section 25 & UI Section 25):
 *    - Answers "Explain why these nodes are connected" by displaying verified multi-hop paths
 *      and a natural language narrative generated by Gemini 2.5 Flash.
 * 2. Emil Kowalski Micro-Interactions & A11y (Rule 1 & Rule 7):
 *    - Tactile buttons with `active:scale-[0.97]` and mobile touch targets >= 44px.
 * 3. Zero-`any` Standard:
 *    - Fully typed with TypeScript interfaces.
 */

import * as React from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Sparkles,
  ArrowRight,
  Calendar,
  Layers,
  AlertCircle,
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { useWorkspace } from '@/context/WorkspaceContext';
import { useUser } from '@/firebase';
import { explainGraphConnectionAction } from '@/lib/memory/actions/graph-actions';
import type { ExplainGraphConnectionOutput } from '@/ai/flows/explain-graph-connection-flow';
import type { GraphNode } from '@/lib/quick-notes-types';

interface ExplainConnectionDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  startNode: GraphNode | null;
  targetNode: GraphNode | null;
}

export function ExplainConnectionDialog({
  open,
  onOpenChange,
  startNode,
  targetNode,
}: ExplainConnectionDialogProps) {
  const { toast } = useToast();
  const { activeWorkspaceId } = useWorkspace();
  const { user } = useUser();

  const [explanation, setExplanation] = React.useState<ExplainGraphConnectionOutput | null>(null);
  const [isLoading, setIsLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  React.useEffect(() => {
    if (!open || !startNode || !targetNode || !activeWorkspaceId || !user) {
      setExplanation(null);
      setError(null);
      return;
    }

    let isMounted = true;
    setIsLoading(true);
    setError(null);

    explainGraphConnectionAction({
      workspaceId: activeWorkspaceId,
      userId: user.uid,
      startNodeId: startNode.id,
      targetNodeId: targetNode.id,
    })
      .then((res) => {
        if (!isMounted) return;
        if (res.success && res.data) {
          setExplanation(res.data);
        } else {
          setError(res.error || 'Could not explain relationship between selected nodes.');
        }
      })
      .catch((err) => {
        if (!isMounted) return;
        setError(err instanceof Error ? err.message : 'Unknown connection explanation error');
      })
      .finally(() => {
        if (isMounted) setIsLoading(false);
      });

    return () => {
      isMounted = false;
    };
  }, [open, startNode, targetNode, activeWorkspaceId, user, toast]);

  if (!startNode || !targetNode) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="w-full sm:max-w-lg p-5 sm:p-6 space-y-4 font-figtree">
        <DialogHeader className="space-y-1.5 text-left border-b border-border/60 pb-3">
          <div className="flex items-center gap-2 text-primary font-bold text-xs uppercase tracking-wider">
            <Sparkles className="h-3.5 w-3.5" />
            <span>Graph Relationship Reasoning</span>
          </div>
          <DialogTitle className="text-base sm:text-lg font-bold text-foreground">
            Why are these items connected?
          </DialogTitle>
          <DialogDescription className="text-xs text-muted-foreground">
            AI analysis of verified multi-hop connections, meetings, and deals in the knowledge graph.
          </DialogDescription>
        </DialogHeader>

        {/* Node Pair Header */}
        <div className="flex items-center justify-between gap-2 rounded-xl border border-border bg-muted/30 p-3 text-xs">
          <div className="flex items-center gap-1.5 min-w-0">
            <Badge variant="outline" className="text-[10px] uppercase font-bold shrink-0">
              {startNode.type}
            </Badge>
            <span className="font-semibold text-foreground truncate">{startNode.label}</span>
          </div>

          <ArrowRight className="h-4 w-4 text-muted-foreground shrink-0" />

          <div className="flex items-center gap-1.5 min-w-0 justify-end">
            <span className="font-semibold text-foreground truncate">{targetNode.label}</span>
            <Badge variant="outline" className="text-[10px] uppercase font-bold shrink-0">
              {targetNode.type}
            </Badge>
          </div>
        </div>

        {/* Content Body */}
        {isLoading ? (
          <div className="space-y-3 py-2">
            <Skeleton className="h-16 w-full rounded-xl" />
            <Skeleton className="h-10 w-3/4 rounded-lg" />
          </div>
        ) : error ? (
          <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-xs text-amber-900 dark:text-amber-200 flex items-start gap-2">
            <AlertCircle className="h-4 w-4 text-amber-600 shrink-0 mt-0.5" />
            <p>{error}</p>
          </div>
        ) : explanation ? (
          <div className="space-y-3">
            {/* Narrative Box */}
            <div className="rounded-xl border border-indigo-200 dark:border-indigo-900/60 bg-indigo-50/50 dark:bg-indigo-950/20 p-4 text-xs text-indigo-950 dark:text-indigo-200 leading-relaxed space-y-1.5">
              <span className="font-bold text-[11px] uppercase tracking-wider text-indigo-700 dark:text-indigo-400 block">
                Relationship Narrative:
              </span>
              <p>{explanation.narrative}</p>
            </div>

            {/* Events Cited */}
            {explanation.eventsCited && explanation.eventsCited.length > 0 && (
              <div className="space-y-1.5 pt-1">
                <span className="text-[11px] font-bold uppercase tracking-wider text-muted-foreground flex items-center gap-1">
                  <Calendar className="h-3 w-3" />
                  Connecting Evidence:
                </span>
                <div className="flex flex-wrap gap-1.5">
                  {explanation.eventsCited.map((event, i) => (
                    <span
                      key={i}
                      className="inline-flex items-center gap-1 rounded-md bg-secondary/80 px-2 py-0.5 text-[11px] font-medium text-secondary-foreground"
                    >
                      <Layers className="h-2.5 w-2.5 text-muted-foreground" />
                      {event}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        ) : null}

        <DialogFooter className="border-t border-border/60 pt-3">
          <Button
            type="button"
            variant="outline"
            onClick={() => onOpenChange(false)}
            className="w-full sm:w-auto min-h-[44px] sm:min-h-[36px] text-xs font-semibold active:scale-[0.97]"
          >
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
