'use client';

import * as React from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { 
    Dialog, 
    DialogContent, 
    DialogHeader, 
    DialogTitle, 
    DialogDescription,
    DialogFooter
} from '@/components/ui/dialog';
import {
    Form,
    FormControl,
    FormField,
    FormItem,
    FormLabel,
    FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { MultiSelect } from '@/components/ui/multi-select';
import { Checkbox } from '@/components/ui/checkbox';
import { inviteUserAction } from '@/lib/user-invite-actions';
import { useToast } from '@/hooks/use-toast';
import { useTenant } from '@/context/TenantContext';
import { UserPlus, Mail, Phone, Loader2, Sparkles, Eye, Building2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';

const inviteSchema = z.object({
    fullName: z.string().min(2, 'Name is too short'),
    email: z.string().email('Invalid email address'),
    phone: z.string().optional(),
    roles: z.array(z.string()).min(1, 'Select at least one role'),
    sendMethods: z.array(z.string()).min(1, 'Select at least one delivery method'),
});

type InviteFormData = z.infer<typeof inviteSchema>;

interface InviteUserModalProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    roles: { id: string; name: string }[];
}

export default function InviteUserModal({ open, onOpenChange, roles }: InviteUserModalProps) {
    const { toast } = useToast();
    const { activeOrganizationId, activeOrganization, activeWorkspaceId, activeWorkspace } = useTenant();
    const [isSubmitting, setIsSubmitting] = React.useState(false);
    const [previewMode, setPreviewMode] = React.useState(false);

    const form = useForm<InviteFormData>({
        resolver: zodResolver(inviteSchema),
        defaultValues: {
            fullName: '',
            email: '',
            phone: '',
            roles: activeOrganization?.defaultRoleId ? [activeOrganization.defaultRoleId] : [],
            sendMethods: ['email'],
        }
    });

    // Sync default role if it changes or loads after mount
    React.useEffect(() => {
        if (activeOrganization?.defaultRoleId && form.getValues('roles').length === 0) {
            form.setValue('roles', [activeOrganization.defaultRoleId]);
        }
    }, [activeOrganization?.defaultRoleId, form]);

    const onSubmit = async (data: InviteFormData) => {
        if (!activeOrganizationId || !activeWorkspaceId) return;
        setIsSubmitting(true);
        try {
            // Map the selected roles to the active workspace
            const workspaceRoles: Record<string, string[]> = {
                [activeWorkspaceId]: data.roles,
            };

            const result = await inviteUserAction({
                fullName: data.fullName,
                email: data.email,
                phone: data.phone,
                workspaceRoles,
                organizationId: activeOrganizationId,
                sendMethods: data.sendMethods as ('email' | 'sms')[],
            });

            if (result.success) {
                toast({ title: 'Invitation Dispatched', description: result.message });
                onOpenChange(false);
                form.reset();
            } else {
                throw new Error(result.error);
            }
        } catch (error: any) {
            toast({ variant: 'destructive', title: 'Invitation Failed', description: error.message });
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-[600px] rounded-[2rem] border-none shadow-2xl p-0 overflow-hidden bg-background/80 backdrop-blur-xl ring-1 ring-border">
                <DialogHeader className="p-8 pb-4 bg-primary/5 border-b border-border/50">
                    <div className="flex items-center gap-4 mb-2">
                        <div className="p-3 bg-primary/10 text-primary rounded-2xl">
                            <UserPlus className="h-6 w-6" />
                        </div>
                        <div>
                            <DialogTitle className="text-2xl font-black tracking-tight">Expand the Identity Hub</DialogTitle>
                            <DialogDescription className="font-medium">
                                Invite new institutional members with secure autogenerated credentials.
                            </DialogDescription>
                        </div>
                    </div>
                </DialogHeader>

                <div className="p-8 max-h-[70vh] overflow-y-auto">
                    <Form {...form}>
                        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <FormField
                                    control={form.control}
                                    name="fullName"
                                    render={({ field }) => (
                                        <FormItem>
                                            <FormLabel>Full Legal Name</FormLabel>
                                            <FormControl>
                                                <Input placeholder="e.g. John Doe" className="rounded-xl h-11 bg-muted/20" {...field} />
                                            </FormControl>
                                            <FormMessage />
                                        </FormItem>
                                    )}
                                />
                                <FormField
                                    control={form.control}
                                    name="email"
                                    render={({ field }) => (
                                        <FormItem>
                                            <FormLabel>Corporate Email</FormLabel>
                                            <FormControl>
                                                <Input type="email" placeholder="john@org.com" className="rounded-xl h-11 bg-muted/20" {...field} />
                                            </FormControl>
                                            <FormMessage />
                                        </FormItem>
                                    )}
                                />
                            </div>

                            <FormField
                                control={form.control}
                                name="phone"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Phone Number (Optional for SMS)</FormLabel>
                                        <FormControl>
                                            <Input type="tel" placeholder="e.g. 0244123456" className="rounded-xl h-11 bg-muted/20" {...field} />
                                        </FormControl>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />

                            <FormField
                                control={form.control}
                                name="roles"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel className="flex items-center gap-2">
                                            Assigned Role Architecture
                                            {activeWorkspace && (
                                                <Badge variant="outline" className="text-[10px] font-bold px-2 py-0 bg-indigo-50 text-indigo-700 border-indigo-200">
                                                    <Building2 className="h-3 w-3 mr-1" />
                                                    {activeWorkspace.name}
                                                </Badge>
                                            )}
                                        </FormLabel>
                                        <MultiSelect
                                            options={roles.map(r => ({ label: r.name, value: r.id }))}
                                            value={field.value}
                                            onChange={field.onChange}
                                            placeholder="Select roles for this workspace..."
                                            className="rounded-xl border-dashed bg-muted/10 min-h-11"
                                        />
                                        <p className="text-[11px] text-muted-foreground mt-1.5">
                                            Roles will be assigned to <span className="font-semibold text-foreground">{activeWorkspace?.name || 'the current workspace'}</span>. You can add more workspaces after invitation.
                                        </p>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />

                            <Separator className="opacity-50" />

                            <div className="space-y-4">
                                <FormLabel className="text-sm font-bold flex items-center gap-2">
                                    <Sparkles className="h-3 w-3 text-primary" /> Delivery Channels
                                </FormLabel>
                                <div className="grid grid-cols-2 gap-4">
                                    <FormField
                                        control={form.control}
                                        name="sendMethods"
                                        render={({ field }) => (
                                            <FormItem className="flex items-center space-x-3 space-y-0 p-4 rounded-2xl border border-border bg-muted/20 cursor-pointer hover:bg-muted/30 transition-colors">
                                                <FormControl>
                                                    <Checkbox 
                                                        checked={field.value.includes('email')}
                                                        onCheckedChange={(checked) => {
                                                            const val = checked ? [...field.value, 'email'] : field.value.filter(v => v !== 'email');
                                                            field.onChange(val);
                                                        }}
                                                    />
                                                </FormControl>
                                                <div className="flex items-center gap-2">
                                                    <Mail className="h-4 w-4 text-muted-foreground" />
                                                    <span className="text-xs font-bold">Email Notification</span>
                                                </div>
                                            </FormItem>
                                        )}
                                    />
                                    <FormField
                                        control={form.control}
                                        name="sendMethods"
                                        render={({ field }) => (
                                            <FormItem className="flex items-center space-x-3 space-y-0 p-4 rounded-2xl border border-border bg-muted/20 cursor-pointer hover:bg-muted/30 transition-colors">
                                                <FormControl>
                                                    <Checkbox 
                                                        checked={field.value.includes('sms')}
                                                        disabled={!form.watch('phone')}
                                                        onCheckedChange={(checked) => {
                                                            const val = checked ? [...field.value, 'sms'] : field.value.filter(v => v !== 'sms');
                                                            field.onChange(val);
                                                        }}
                                                    />
                                                </FormControl>
                                                <div className="flex items-center gap-2">
                                                    <Phone className="h-4 w-4 text-muted-foreground" />
                                                    <span className="text-xs font-bold">SMS Alert</span>
                                                </div>
                                            </FormItem>
                                        )}
                                    />
                                </div>
                            </div>
                        </form>
                    </Form>
                </div>

                <DialogFooter className="p-8 bg-muted/10 border-t border-border/50 gap-4">
                    <Button variant="ghost" className="rounded-xl px-6" onClick={() => onOpenChange(false)} disabled={isSubmitting}>
                        Cancel
                    </Button>
                    <Button 
                        onClick={form.handleSubmit(onSubmit)} 
                        className="rounded-xl px-8 font-bold shadow-lg shadow-primary/20 transition-all hover:scale-[1.02] active:scale-95" 
                        disabled={isSubmitting}
                    >
                        {isSubmitting ? (
                            <>
                                <Loader2 className="h-4 w-4 animate-spin mr-2" /> Dispatching...
                            </>
                        ) : (
                            <>
                                <Sparkles className="h-4 w-4 mr-2" /> Launch Invitation
                            </>
                        )}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
