'use client';

/**
 * @fileOverview CompanyBrain 2.0 Phase 7: Supervisor Executive Result Card
 *
 * ARCHITECTURAL GUIDELINES & CAUTION FOR MAINTAINERS (Rule 10):
 * 1. Executive Briefing & Grounded Intelligence:
 *    - Renders natural-language executive summary in clean markdown format.
 *    - Displays structured findings and interactive action proposals.
 * 2. Mobile Accessibility:
 *    - Touch targets >= 44px (`min-h-[44px]`).
 * 3. Emil Kowalski Micro-Interactions:
 *    - Tactile buttons with `active:scale-[0.97]`.
 * 4. Strict Zero-`any` & Zero-`unknown` Standard.
 */

import * as React from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Sparkles,
  Play,
  Loader2,
  Check,
} from 'lucide-react';
import type { AgentResult, AgentActionProposal } from '@/lib/supervisor/types';

export interface SupervisorResultCardProps {
  result: AgentResult;
  onExecuteAction: (action: AgentActionProposal) => Promise<void>;
  isExecutingAction: boolean;
}

export function SupervisorResultCard({
  result,
  onExecuteAction,
  isExecutingAction,
}: SupervisorResultCardProps) {
  const [executingActionId, setExecutingActionId] = React.useState<string | null>(null);
  const [executedActionIds, setExecutedActionIds] = React.useState<Set<string>>(new Set());

  const handleActionClick = async (action: AgentActionProposal) => {
    const actionId = action.id || action.title;
    setExecutingActionId(actionId);
    try {
      await onExecuteAction(action);
      setExecutedActionIds((prev) => new Set([...prev, actionId]));
    } finally {
      setExecutingActionId(null);
    }
  };

  const getCategoryBadge = (category: string) => {
    switch (category) {
      case 'risk':
        return <Badge variant="outline" className="border-rose-200 bg-rose-50 text-rose-700 text-[10px]">RISK</Badge>;
      case 'opportunity':
        return <Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-700 text-[10px]">OPPORTUNITY</Badge>;
      case 'contradiction':
        return <Badge variant="outline" className="border-amber-200 bg-amber-50 text-amber-800 text-[10px]">CONTRADICTION</Badge>;
      case 'trend':
        return <Badge variant="outline" className="border-blue-200 bg-blue-50 text-blue-700 text-[10px]">TREND</Badge>;
      default:
        return <Badge variant="outline" className="border-indigo-200 bg-indigo-50 text-indigo-700 text-[10px]">INSIGHT</Badge>;
    }
  };

  return (
    <Card className="border-border shadow-sm overflow-hidden space-y-6">
      <CardHeader className="bg-slate-50/60 border-b border-slate-100 pb-4">
        <div className="flex items-center justify-between">
          <div className="space-y-1">
            <CardTitle className="text-base font-bold text-slate-900 flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-indigo-600" />
              <span>Executive Mission Briefing</span>
            </CardTitle>
            <p className="text-xs text-slate-500">
              Grounded synthesis and recommendations generated by the Supervisor Agent.
            </p>
          </div>
          <Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-700 text-xs font-semibold">
            MISSION COMPLETED
          </Badge>
        </div>
      </CardHeader>

      <CardContent className="p-4 sm:p-6 space-y-6">
        {/* Executive Summary Markdown */}
        <div className="prose prose-sm max-w-none text-slate-800 space-y-2 text-xs sm:text-sm leading-relaxed whitespace-pre-line">
          {result.answer || 'No narrative briefing generated.'}
        </div>

        {/* Structured Findings */}
        {result.findings && result.findings.length > 0 && (
          <div className="space-y-3 pt-2 border-t border-slate-100">
            <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block">
              Discovered Findings ({result.findings.length})
            </span>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {result.findings.map((f) => (
                <div
                  key={f.id}
                  className="p-3.5 bg-slate-50 border border-slate-200 rounded-xl space-y-1.5 transition-all hover:border-slate-300"
                >
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-xs font-bold text-slate-900 leading-tight">
                      {f.title}
                    </span>
                    {getCategoryBadge(f.category)}
                  </div>
                  <p className="text-[11px] text-slate-600 leading-relaxed">
                    {f.description}
                  </p>
                  <div className="flex items-center justify-between pt-1 text-[10px] text-slate-400 font-mono">
                    <span>Confidence: {Math.round(f.confidence * 100)}%</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Action Proposals */}
        {result.actions && result.actions.length > 0 && (
          <div className="space-y-3 pt-2 border-t border-slate-100">
            <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block">
              Recommended Next Actions ({result.actions.length})
            </span>
            <div className="space-y-2.5">
              {result.actions.map((act, idx) => {
                const actId = act.id || `action_${idx}_${act.title}`;
                const isExecuted = executedActionIds.has(actId);
                const isRunning = executingActionId === actId;

                return (
                  <div
                    key={actId}
                    className="p-3.5 sm:p-4 bg-white border border-slate-200 rounded-xl flex flex-col sm:flex-row sm:items-center justify-between gap-3 shadow-xs hover:border-slate-300 transition-all"
                  >
                    <div className="space-y-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="text-xs font-bold text-slate-900">{act.title}</span>
                        <Badge variant="outline" className="font-mono text-[10px] bg-slate-50">
                          {act.toolName}
                        </Badge>
                        {act.requiresApproval && (
                          <Badge variant="outline" className="border-amber-200 bg-amber-50 text-amber-800 text-[10px]">
                            Requires Review
                          </Badge>
                        )}
                      </div>
                      <p className="text-[11px] text-slate-600 leading-relaxed">
                        {act.description}
                      </p>
                    </div>

                    <div className="self-end sm:self-center shrink-0">
                      {isExecuted ? (
                        <span className="text-xs font-semibold text-emerald-600 flex items-center gap-1 min-h-[44px] px-3">
                          <Check className="w-4 h-4" /> Executed
                        </span>
                      ) : (
                        <Button
                          size="sm"
                          onClick={() => handleActionClick({ ...act, id: actId })}
                          disabled={isRunning || isExecutingAction}
                          className="min-h-[44px] px-4 bg-slate-900 hover:bg-slate-800 text-white text-xs font-semibold rounded-xl active:scale-[0.97] transition-all gap-1.5 shadow-sm"
                        >
                          {isRunning ? (
                            <>
                              <Loader2 className="w-3.5 h-3.5 animate-spin" />
                              <span>Executing...</span>
                            </>
                          ) : (
                            <>
                              <Play className="w-3.5 h-3.5" />
                              <span>Execute Action</span>
                            </>
                          )}
                        </Button>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
