/**
 * @fileOverview CompanyBrain 2.0 Phase 9: Turnkey Production Workflow Blueprints
 *
 * ARCHITECTURAL GUIDELINES & CAUTION FOR MAINTAINERS (Rule 10):
 * 1. PRD Section 4100 / Section 124 Alignment:
 *    - Implements the 3 canonical production workflows:
 *      1. Deal Rescue Blueprint
 *      2. Lead Activation Blueprint
 *      3. Meeting Follow-up Blueprint
 * 2. Strict Zero-`any` & Zero-`unknown` Invariant:
 *    - All mock payloads, arguments, and templates use `McpPayloadValue`.
 * 3. Non-Destructive Mutations:
 *    - High-impact CRM stage changes or customer outreach sequences are gated by mandatory
 *      `ApprovalGateNode` configurations conforming to PRD Invariant 4.
 *
 * @testability Covered in `src/lib/workflows/__tests__/workflow-engine.test.ts`.
 */

import type { WorkflowBlueprint } from '../types';

/**
 * 1. Deal Rescue Blueprint
 * Detects deal stall -> Analyzes commercial risk -> Checks compliance -> Human approval -> Advances stage.
 */
export const DEAL_RESCUE_BLUEPRINT: WorkflowBlueprint = {
  id: 'bp_deal_rescue',
  title: 'Deal Rescue & Pipeline Acceleration',
  category: 'revenue',
  description:
    'Automatically detects stalled high-value deals in proposal or negotiation stages, conducts deep commercial and compliance analysis, and generates an executive rescue plan with mandatory approval.',
  iconName: 'ShieldAlert',
  triggerDescription: 'Triggered when a deal remains in stage for more than 14 days or is flagged as stalled.',
  trigger: {
    type: 'event',
    eventType: 'crm.deal.stalled',
    filterCriteria: [
      { field: 'stage', operator: 'eq', value: 'proposal' },
    ],
  },
  benefits: [
    'Recovers stalled revenue opportunities with multi-perspective analysis',
    'Ensures legal and compliance verification before contract acceleration',
    'Enforces executive approval gate before advancing pipeline stages',
  ],
  nodes: [
    {
      id: 'node_trigger',
      title: 'Stalled Deal Event Ingestion',
      description: 'Ingests deal parameters from CRM event trigger',
      nodeType: 'trigger',
      nextNodeIds: ['node_revenue_analysis'],
      position: { x: 50, y: 150 },
    },
    {
      id: 'node_revenue_analysis',
      title: 'Revenue & Economic Audit',
      description: 'Evaluates deal velocity, pricing consistency, and close probability',
      nodeType: 'specialist',
      specialistId: 'revenue_specialist',
      nextNodeIds: ['node_governance_audit'],
      position: { x: 250, y: 150 },
    },
    {
      id: 'node_governance_audit',
      title: 'Governance & Compliance Verification',
      description: 'Audits prerequisites, contracts, and regulatory constraints',
      nodeType: 'specialist',
      specialistId: 'governance_specialist',
      nextNodeIds: ['node_decision_risk'],
      position: { x: 450, y: 150 },
    },
    {
      id: 'node_decision_risk',
      title: 'Risk-Tiered Branching Decision',
      description: 'Evaluates if high-touch executive intervention is required',
      nodeType: 'decision',
      decisionRules: [
        {
          condition: { field: 'riskLevel', operator: 'eq', value: 'high' },
          targetNodeId: 'node_approval_gate',
          label: 'Elevated Risk (Requires Approval)',
        },
      ],
      defaultNextNodeId: 'node_approval_gate',
      nextNodeIds: ['node_approval_gate'],
      position: { x: 650, y: 150 },
    },
    {
      id: 'node_approval_gate',
      title: 'Executive Sponsor Sign-Off Gate',
      description: 'Pauses execution for sales management approval of rescue actions',
      nodeType: 'approval_gate',
      approvalConfig: {
        prompt: 'Review Deal Rescue plan and authorize pipeline acceleration steps.',
        requiredRole: 'manager',
        timeoutHours: 48,
        onTimeout: 'escalate',
      },
      nextNodeIds: ['node_dispatch_task'],
      position: { x: 850, y: 150 },
    },
    {
      id: 'node_dispatch_task',
      title: 'Dispatch Executive Rescue Action Item',
      description: 'Creates priority follow-up task assigned to deal owner',
      nodeType: 'action',
      actionConfig: {
        actionType: 'create_task',
        payloadTemplate: {
          title: 'Execute Deal Rescue Plan for Strategic Account',
          priority: 'urgent',
          description: 'Automated rescue plan generated by CompanyBrain Swarm. Review compliance findings.',
        },
      },
      nextNodeIds: [],
      position: { x: 1050, y: 150 },
    },
  ],
};

/**
 * 2. Lead Activation Blueprint
 * Ingests inbound lead -> Qualifies ICP -> Assembles context dossier -> Drafts outreach -> Approves.
 */
export const LEAD_ACTIVATION_BLUEPRINT: WorkflowBlueprint = {
  id: 'bp_lead_activation',
  title: 'Lead Activation & Prospect Enrichment',
  category: 'prospecting',
  description:
    'Enriches new inbound prospects with institutional lore, scores ICP fit, builds a 4-tier context dossier, and drafts personalized discovery angles for SDR review.',
  iconName: 'UserCheck',
  triggerDescription: 'Triggered when a new prospect account or lead is created.',
  trigger: {
    type: 'event',
    eventType: 'crm.lead.created',
  },
  benefits: [
    'Cuts SDR prospect research time by 80% with automated dossiers',
    'Standardizes ICP scoring and objection prediction',
    'Enforces human review before outbound dispatch (PRD Invariant 4)',
  ],
  nodes: [
    {
      id: 'node_lead_trigger',
      title: 'New Lead Created Ingestion',
      description: 'Ingests new prospect account record',
      nodeType: 'trigger',
      nextNodeIds: ['node_sdr_qualification'],
      position: { x: 50, y: 150 },
    },
    {
      id: 'node_sdr_qualification',
      title: 'SDR ICP Qualification & Pain Point Analysis',
      description: 'Scores account fit and extracts operational challenges',
      nodeType: 'specialist',
      specialistId: 'sdr_specialist',
      nextNodeIds: ['node_context_dossier'],
      position: { x: 250, y: 150 },
    },
    {
      id: 'node_context_dossier',
      title: 'Unified Context Dossier Assembly',
      description: 'Assembles 4-tier token budgeted intelligence dossier',
      nodeType: 'context',
      contextConfig: {
        targetSubjectType: 'lead',
        subjectIdBindingField: 'leadId',
        maxTokens: 3000,
        tiers: [1, 2, 3],
        includeGraph: true,
      },
      nextNodeIds: ['node_lead_approval'],
      position: { x: 450, y: 150 },
    },
    {
      id: 'node_lead_approval',
      title: 'SDR Outreach Review Gate',
      description: 'Human SDR reviews discovery message and outreach strategy',
      nodeType: 'approval_gate',
      approvalConfig: {
        prompt: 'Review personalized SDR outreach proposal and approve dispatch.',
        requiredRole: 'operator',
        timeoutHours: 24,
        onTimeout: 'auto_cancel',
      },
      nextNodeIds: ['node_create_lead_task'],
      position: { x: 650, y: 150 },
    },
    {
      id: 'node_create_lead_task',
      title: 'Schedule Outreach Task',
      description: 'Logs outreach schedule and task in CRM',
      nodeType: 'action',
      actionConfig: {
        actionType: 'create_task',
        payloadTemplate: {
          title: 'Execute Personalized Outbound Sequence',
          priority: 'high',
          description: 'Grounded outreach drafted via CompanyBrain SDR Specialist & Context Builder.',
        },
      },
      nextNodeIds: [],
      position: { x: 850, y: 150 },
    },
  ],
};

/**
 * 3. Meeting Follow-up Blueprint
 * Meeting completed -> Extracts commitments -> Operations checklist -> Task dispatch.
 */
export const MEETING_FOLLOWUP_BLUEPRINT: WorkflowBlueprint = {
  id: 'bp_meeting_followup',
  title: 'Meeting Follow-up & Commitment Capture',
  category: 'meetings',
  description:
    'Extracts attendee commitments, stakeholder positions, and decisions from completed meetings, coordinates operational follow-up tasks, and drafts follow-up notes.',
  iconName: 'CalendarCheck',
  triggerDescription: 'Triggered when an executive meeting is completed or transcript is ready.',
  trigger: {
    type: 'event',
    eventType: 'meeting.completed',
  },
  benefits: [
    'Zero forgotten meeting commitments or unassigned action items',
    'Direct coordination between Meeting and Operations Specialists',
    'Eliminates manual post-meeting administrative burden',
  ],
  nodes: [
    {
      id: 'node_meeting_trigger',
      title: 'Meeting Completed Ingestion',
      description: 'Ingests meeting transcript and participant metadata',
      nodeType: 'trigger',
      nextNodeIds: ['node_meeting_intelligence'],
      position: { x: 50, y: 150 },
    },
    {
      id: 'node_meeting_intelligence',
      title: 'Commitment & Decision Extraction',
      description: 'Meeting Specialist extracts verbal promises and decisions',
      nodeType: 'specialist',
      specialistId: 'meeting_specialist',
      nextNodeIds: ['node_operations_orchestration'],
      position: { x: 250, y: 150 },
    },
    {
      id: 'node_operations_orchestration',
      title: 'Operations Task Structuring',
      description: 'Operations Specialist organizes milestone tasks and deadlines',
      nodeType: 'specialist',
      specialistId: 'operations_specialist',
      nextNodeIds: ['node_meeting_review_gate'],
      position: { x: 450, y: 150 },
    },
    {
      id: 'node_meeting_review_gate',
      title: 'Meeting Host Verification Gate',
      description: 'Meeting host reviews extracted commitments before task dispatch',
      nodeType: 'approval_gate',
      approvalConfig: {
        prompt: 'Verify meeting action items and approved assignee distribution.',
        requiredRole: 'any',
        timeoutHours: 48,
        onTimeout: 'continue_fallback',
      },
      nextNodeIds: ['node_dispatch_meeting_tasks'],
      position: { x: 650, y: 150 },
    },
    {
      id: 'node_dispatch_meeting_tasks',
      title: 'Dispatch Assignee Milestone Tasks',
      description: 'Creates verified action items for meeting participants',
      nodeType: 'action',
      actionConfig: {
        actionType: 'create_task',
        payloadTemplate: {
          title: 'Post-Meeting Follow-up Action Item',
          priority: 'medium',
          description: 'Extracted from meeting transcript by CompanyBrain Meeting Specialist.',
        },
      },
      nextNodeIds: [],
      position: { x: 850, y: 150 },
    },
  ],
};

/**
 * Canonical registry of turnkey blueprints.
 */
export const TURNKEY_WORKFLOW_BLUEPRINTS: WorkflowBlueprint[] = [
  DEAL_RESCUE_BLUEPRINT,
  LEAD_ACTIVATION_BLUEPRINT,
  MEETING_FOLLOWUP_BLUEPRINT,
];
