import { addDays } from 'date-fns';
import { adminDb } from '../../firebase-admin';
import { createTaskFromAutomation } from '../../task-server-actions';
import type { TaskCategory, TaskPriority, TaskStatus } from '../../types';
import type { ExecutionContext } from '../execution-types';

export async function handleCreateTask(
  config: Record<string, unknown>,
  context: ExecutionContext
): Promise<{ id: string }> {
  const dueDate = addDays(new Date(), (config.dueOffsetDays as number) || 3).toISOString();
  const organizationId =
    (context.payload.organizationId as string) ||
    (await adminDb.collection('workspaces').doc(context.workspaceId).get()).data()
      ?.organizationId ||
    '';

  const assignedToPayload = context.payload.assignedTo as { userId?: string } | undefined;

  const taskId = await createTaskFromAutomation(
    {
      title: (config.title as string) || 'Automated Task',
      description: (config.description as string) || 'Generated by protocol engine.',
      priority: ((config.priority as string) || 'medium') as TaskPriority,
      status: 'todo' as TaskStatus,
      category: ((config.category as string) || 'general') as TaskCategory,
      workspaceId: context.workspaceId,
      entityId: context.entityId,
      entityType: context.entityType,
      assignedTo:
        config.assignedTo === 'auto'
          ? assignedToPayload?.userId || ''
          : (config.assignedTo as string),
      dueDate,
      source: 'automation',
      automationId: context.automationId,
      reminders: [],
      reminderSent: false,
    },
    organizationId
  );

  return { id: taskId };
}

export async function handleUpdateTask(
  config: Record<string, unknown>,
  context: ExecutionContext
): Promise<void> {
  const taskId =
    (config.taskId as string) ||
    (config.useTriggerTaskId ? (context.payload.taskId as string) : undefined);
  if (!taskId) throw new Error('Update task action missing taskId.');

  const updates: Record<string, unknown> = { updatedAt: new Date().toISOString() };
  if (config.status) updates.status = config.status;
  if (config.assignedTo) updates.assignedTo = config.assignedTo;
  if (config.priority) updates.priority = config.priority;

  await adminDb.collection('tasks').doc(taskId).update(updates);
}
