import { addDays } from 'date-fns';
import { adminDb } from '../../firebase-admin';
// Automation engine runs session-less: it uses the task core directly (system actor).
import { createTaskFromAutomation, updateTaskCore } from '../../tasks/task-core';
import type { Task, TaskCategory, TaskPriority, TaskStatus } from '../../types';
import type { ExecutionContext } from '../execution-types';

export async function handleCreateTask(
  config: Record<string, unknown>,
  context: ExecutionContext
): Promise<{ id: string }> {
  const dueDate = addDays(new Date(), (config.dueOffsetDays as number) || 3).toISOString();
  const organizationId =
    (context.payload.organizationId as string) ||
    (await adminDb.collection('workspaces').doc(context.workspaceId).get()).data()
      ?.organizationId ||
    '';

  const assignedToPayload = context.payload.assignedTo as { userId?: string } | undefined;

  const taskId = await createTaskFromAutomation(
    {
      title: (config.title as string) || 'Automated Task',
      description: (config.description as string) || 'Generated by protocol engine.',
      priority: ((config.priority as string) || 'medium') as TaskPriority,
      status: 'todo' as TaskStatus,
      category: ((config.category as string) || 'general') as TaskCategory,
      workspaceId: context.workspaceId,
      entityId: context.entityId,
      entityType: context.entityType,
      assignedTo:
        config.assignedTo === 'auto'
          ? assignedToPayload?.userId || ''
          : (config.assignedTo as string),
      dueDate,
      source: 'automation',
      automationId: context.automationId,
      reminders: [],
      reminderSent: false,
    },
    organizationId
  );

  return { id: taskId };
}

export async function handleUpdateTask(
  config: Record<string, unknown>,
  context: ExecutionContext
): Promise<void> {
  const taskId =
    (config.taskId as string) ||
    (config.useTriggerTaskId ? (context.payload.taskId as string) : undefined);
  if (!taskId) throw new Error('Update task action missing taskId.');

  const updates: Partial<Task> = {};
  if (config.status) updates.status = config.status as TaskStatus;
  if (config.assignedTo) updates.assignedTo = config.assignedTo as string;
  if (config.priority) updates.priority = config.priority as TaskPriority;
  if (config.title) updates.title = config.title as string;
  if (config.description) updates.description = config.description as string;
  if (config.dueDate) updates.dueDate = config.dueDate as string;

  const result = await updateTaskCore(
    taskId,
    updates,
    { kind: 'system', source: 'automation' },
    context.workspaceId
  );

  if (!result.success) {
    throw new Error(result.error || 'Failed to update task via automation.');
  }
}
