'use client';

/**
 * @fileoverview Next Best Actions & AI Recommendations Tab Component (Phase 9).
 *
 * ARCHITECTURAL POINTER:
 * Fulfills SmartSapp Sales Performance & Intelligence 2.0 UX Screen 2 (AI Recommendations):
 * - Prioritized Next-Best-Action queue with confidence meters and explainable "Why" rationales.
 * - Entity links directly to deals, contacts, and meetings.
 * - 1-click Execute Action directly updates status, writes execution telemetry, and awards +10 effort points.
 * - Mobile-first touch targets (min-h-[44px], active:scale-[0.97]).
 *
 * CAUTION FOR FUTURE MAINTAINERS:
 * - 100% strict typing enforced. Zero use of 'any' or 'any[]'.
 * - No raw HTML tags in UI.
 */

import * as React from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import {
  Sparkles,
  CheckCircle2,
  XCircle,
  Search,
  Filter,
  ArrowRight,
  TrendingUp,
  Building2,
  Clock,
  Zap,
} from 'lucide-react';
import type {
  AiSalesRecommendation,
  AiRecommendationPriority,
} from '@/lib/ai-sales-workforce/types';
import { executeAiRecommendationAction } from '@/app/actions/ai-sales-workforce-actions';
import { useToast } from '@/hooks/use-toast';

interface RecommendationsTabProps {
  recommendations: AiSalesRecommendation[];
  workspaceId: string;
  organizationId: string;
  actorId: string;
  actorName: string;
  onRefresh: () => void;
}

export function RecommendationsTab({
  recommendations,
  workspaceId,
  organizationId,
  actorId,
  actorName,
  onRefresh,
}: RecommendationsTabProps) {
  const { toast } = useToast();
  const [searchQuery, setSearchQuery] = React.useState('');
  const [priorityFilter, setPriorityFilter] = React.useState<string>('all');
  const [executingId, setExecutingId] = React.useState<string | null>(null);

  const filteredRecs = recommendations.filter((rec) => {
    const matchesSearch =
      rec.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      rec.entityName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      rec.description.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesPriority = priorityFilter === 'all' || rec.priority === priorityFilter;
    return matchesSearch && matchesPriority;
  });

  const getPriorityBadge = (priority: AiRecommendationPriority) => {
    switch (priority) {
      case 'critical':
        return <Badge className="bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20 font-bold">Critical</Badge>;
      case 'high':
        return <Badge className="bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20 font-semibold">High Priority</Badge>;
      case 'medium':
        return <Badge className="bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/20 font-semibold">Medium</Badge>;
      case 'low':
        return <Badge variant="secondary">Low</Badge>;
    }
  };

  const handleExecute = async (rec: AiSalesRecommendation) => {
    try {
      setExecutingId(rec.id);
      const res = await executeAiRecommendationAction({
        workspaceId,
        organizationId,
        actorId,
        actorName,
        recommendationId: rec.id,
      });

      if (res.success) {
        toast({
          title: 'Action Executed',
          description: `Executed "${rec.suggestedAction.label}". +${res.pointsAwarded ?? 10} effort points recorded!`,
        });
        onRefresh();
      } else {
        toast({
          title: 'Execution Failed',
          description: res.error || 'Could not execute recommendation.',
          variant: 'destructive',
        });
      }
    } catch (err) {
      toast({
        title: 'Error',
        description: err instanceof Error ? err.message : 'Failed to execute recommendation.',
        variant: 'destructive',
      });
    } finally {
      setExecutingId(null);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header & Filter Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h2 className="text-lg font-bold text-foreground flex items-center gap-2">
            <Zap className="h-5 w-5 text-amber-500" />
            Prioritized Next-Best Actions ({filteredRecs.length})
          </h2>
          <p className="text-xs text-muted-foreground mt-0.5">
            Real-time recommendations generated by the AI agent swarm with grounded commercial rationale.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <div className="relative w-full sm:w-64">
            <Search className="h-3.5 w-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
            <Input
              type="text"
              placeholder="Filter actions or deals..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-8 h-10 rounded-xl text-xs min-h-[44px]"
            />
          </div>

          <div className="flex items-center gap-1">
            {(['all', 'critical', 'high', 'medium'] as const).map((p) => (
              <Button
                key={p}
                type="button"
                variant={priorityFilter === p ? 'default' : 'outline'}
                size="sm"
                onClick={() => setPriorityFilter(p)}
                className="h-10 rounded-xl text-2xs capitalize min-h-[44px] active:scale-[0.97]"
              >
                {p}
              </Button>
            ))}
          </div>
        </div>
      </div>

      {/* Recommendations List */}
      {filteredRecs.length === 0 ? (
        <Card className="border-border/70 rounded-2xl bg-card p-10 text-center shadow-xs">
          <CheckCircle2 className="h-10 w-10 text-emerald-500 mx-auto mb-3" />
          <h3 className="text-sm font-bold text-foreground">Action Queue Clear</h3>
          <p className="text-xs text-muted-foreground mt-1 max-w-sm mx-auto">
            All prioritized AI recommendations have been completed or scheduled.
          </p>
        </Card>
      ) : (
        <div className="space-y-3">
          {filteredRecs.map((rec) => (
            <Card
              key={rec.id}
              className="border-border/70 rounded-2xl bg-card shadow-xs hover:border-border transition-colors"
            >
              <CardContent className="p-5 flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div className="space-y-2 flex-grow">
                  <div className="flex items-center gap-2 flex-wrap">
                    {getPriorityBadge(rec.priority)}
                    <Badge variant="outline" className="text-2xs gap-1 font-mono">
                      <Sparkles className="h-2.5 w-2.5 text-primary" />
                      {rec.agentName}
                    </Badge>
                    <Badge className="bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20 text-2xs font-semibold">
                      {rec.confidenceScore}% Confidence
                    </Badge>
                    <span className="text-xs font-bold text-foreground flex items-center gap-1">
                      <Building2 className="h-3 w-3 text-muted-foreground" />
                      {rec.entityName}
                    </span>
                  </div>

                  <h3 className="text-sm font-bold text-foreground">
                    {rec.title}
                  </h3>

                  <p className="text-xs text-muted-foreground leading-relaxed">
                    {rec.description}
                  </p>

                  <div className="p-3 rounded-xl bg-muted/40 border border-border/40 text-xs">
                    <span className="font-semibold text-foreground">Why: </span>
                    <span className="text-muted-foreground">{rec.rationale}</span>
                  </div>
                </div>

                <div className="flex items-center gap-2 shrink-0 self-end md:self-center">
                  <Button
                    type="button"
                    size="sm"
                    onClick={() => handleExecute(rec)}
                    disabled={executingId === rec.id}
                    className="h-10 rounded-xl text-xs font-semibold px-4 min-h-[44px] active:scale-[0.97] transition-transform gap-1.5 shadow-xs"
                  >
                    <Zap className={`h-3.5 w-3.5 ${executingId === rec.id ? 'animate-spin' : ''}`} />
                    <span>{executingId === rec.id ? 'Executing...' : rec.suggestedAction.label}</span>
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
