'use client';

import * as React from 'react';
import { doc, getDoc, setDoc } from 'firebase/firestore';
import { useFirestore } from '@/firebase';
import { useTenant } from '@/context/TenantContext';
import { useToast } from '@/hooks/use-toast';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Sparkles, Save, Loader2, RefreshCw } from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import type { BrandVoiceProfile } from '@/lib/types';

export default function BrandVoiceSettings() {
  const db = useFirestore();
  const { activeWorkspaceId, activeOrganizationId } = useTenant();
  const { toast } = useToast();

  const [isLoading, setIsLoading] = React.useState(true);
  const [isSaving, setIsSaving] = React.useState(false);
  const [isAnalyzing, setIsAnalyzing] = React.useState(false);

  // Form State
  const [tone, setTone] = React.useState<'professional' | 'casual' | 'inspiring' | 'bold' | 'educational' | 'witty'>('professional');
  const [emojiDensity, setEmojiDensity] = React.useState<'none' | 'low' | 'medium' | 'high'>('medium');
  const [averageLength, setAverageLength] = React.useState<'short' | 'medium' | 'long'>('medium');
  const [targetAudience, setTargetAudience] = React.useState('');
  const [productDescriptions, setProductDescriptions] = React.useState('');
  const [missionStatement, setMissionStatement] = React.useState('');
  const [forbiddenWordsStr, setForbiddenWordsStr] = React.useState('');
  const [mandatoryKeywordsStr, setMandatoryKeywordsStr] = React.useState('');
  const [automationMode, setAutomationMode] = React.useState<'manual' | 'suggest' | 'autopilot'>('manual');

  // 1. Fetch existing Brand Voice Profile for the active workspace
  React.useEffect(() => {
    async function loadProfile() {
      if (!db || !activeWorkspaceId) return;
      setIsLoading(true);
      try {
        const docRef = doc(db, 'brandVoiceProfiles', activeWorkspaceId);
        const docSnap = await getDoc(docRef);

        if (docSnap.exists()) {
          const profile = docSnap.data() as BrandVoiceProfile;
          setTone(profile.tone || 'professional');
          setEmojiDensity(profile.emojiDensity || 'medium');
          setAverageLength(profile.averageLength || 'medium');
          setTargetAudience(profile.targetAudience || '');
          setProductDescriptions(profile.productDescriptions || '');
          setMissionStatement(profile.missionStatement || '');
          setForbiddenWordsStr((profile.forbiddenWords || []).join(', '));
          setMandatoryKeywordsStr((profile.mandatoryKeywords || []).join(', '));
          setAutomationMode(profile.automationMode || 'manual');
        }
      } catch (err: unknown) {
        console.error('[BRAND_VOICE:LOAD] Error:', err);
      } finally {
        setIsLoading(false);
      }
    }

    loadProfile();
  }, [db, activeWorkspaceId]);

  // Save Settings
  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!db || !activeWorkspaceId) return;

    setIsSaving(true);
    try {
      const forbiddenWords = forbiddenWordsStr
        .split(',')
        .map((w) => w.trim())
        .filter((w) => w.length > 0);

      const mandatoryKeywords = mandatoryKeywordsStr
        .split(',')
        .map((w) => w.trim())
        .filter((w) => w.length > 0);

      const docRef = doc(db, 'brandVoiceProfiles', activeWorkspaceId);
      const payload: BrandVoiceProfile = {
        id: activeWorkspaceId,
        orgId: activeOrganizationId,
        workspaceId: activeWorkspaceId,
        name: 'Default Brand Voice',
        isDefault: true,
        description: 'Autogenerated style guideline settings',
        tone,
        emojiDensity,
        averageLength,
        forbiddenWords,
        mandatoryKeywords,
        targetAudience,
        productDescriptions,
        missionStatement,
        automationMode,
        extractedStyleTokens: [],
        samplePosts: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      await setDoc(docRef, payload);
      toast({
        title: 'Voice Profile Saved',
        description: 'Your brand voice guidelines have been successfully synchronized.',
      });
    } catch (err: unknown) {
      console.error('[BRAND_VOICE:SAVE] Error:', err);
      const msg = err instanceof Error ? err.message : 'Failed to write voice profile';
      toast({
        title: 'Save Failed',
        description: msg,
        variant: 'destructive',
      });
    } finally {
      setIsSaving(false);
    }
  };

  // Simulated content analytics style extractor
  const handleExtractStyle = async () => {
    setIsAnalyzing(true);
    // Simulate analyzing past top posts
    await new Promise((resolve) => setTimeout(resolve, 1500));
    
    setTone('educational');
    setEmojiDensity('low');
    setAverageLength('medium');
    setTargetAudience('Parents seeking values-based, rigorous education for preschool and elementary school children.');
    setMandatoryKeywordsStr('holistic development, academic excellence, registration open');
    
    setIsAnalyzing(false);
    toast({
      title: 'Historical Analysis Complete',
      description: 'Extracted tone, target audience, and key phrases from your top performing historical communications.',
    });
  };

  if (isLoading) {
    return (
      <Card className="border border-border/30 rounded-3xl bg-card/40 backdrop-blur-md">
        <CardHeader className="space-y-2">
          <Skeleton className="h-6 w-48" />
          <Skeleton className="h-4 w-72" />
        </CardHeader>
        <CardContent className="space-y-4">
          <Skeleton className="h-10 w-full" />
          <Skeleton className="h-20 w-full" />
          <Skeleton className="h-20 w-full" />
        </CardContent>
      </Card>
    );
  }

  return (
    <form onSubmit={handleSave}>
      <Card className="border border-border/30 rounded-3xl bg-card/40 backdrop-blur-md overflow-hidden relative">
        <div className="absolute inset-0 bg-gradient-to-br from-emerald-500/5 to-transparent pointer-events-none" />

        <CardHeader className="border-b border-border/20 pb-4 relative z-10">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <CardTitle className="text-lg font-bold tracking-tight text-foreground flex items-center gap-2">
                <Sparkles className="h-5 w-5 text-emerald-500" /> AI Brand Voice Guide
              </CardTitle>
              <CardDescription className="text-xs">
                Configure guidelines that prompt the AI Composer to replicate your organization's exact messaging style.
              </CardDescription>
            </div>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={handleExtractStyle}
              disabled={isAnalyzing}
              className="text-xs shrink-0 gap-1.5 rounded-xl h-9 hover:bg-emerald-500/10 font-bold active:scale-[0.97] transition-all border-emerald-500/20"
            >
              {isAnalyzing ? (
                <>
                  <Loader2 className="h-3.5 w-3.5 animate-spin" /> Analyzing posts...
                </>
              ) : (
                <>
                  <RefreshCw className="h-3.5 w-3.5" /> Analyze Past Posts
                </>
              )}
            </Button>
          </div>
        </CardHeader>

        <CardContent className="space-y-6 pt-6 relative z-10">
          {/* Tone & Length parameters */}
          <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
            <div className="space-y-2">
              <Label htmlFor="tone-select" className="text-xs font-bold text-muted-foreground uppercase">Writing Tone</Label>
              <Select value={tone} onValueChange={(val: 'professional' | 'casual' | 'inspiring' | 'bold' | 'educational' | 'witty') => setTone(val)}>
                <SelectTrigger id="tone-select" className="rounded-xl border-border/30 h-10 bg-background/50 text-xs">
                  <SelectValue placeholder="Select tone" />
                </SelectTrigger>
                <SelectContent className="rounded-xl">
                  <SelectItem value="professional">Professional / Authoritative</SelectItem>
                  <SelectItem value="casual">Casual / Friendly</SelectItem>
                  <SelectItem value="inspiring">Inspiring / Visionary</SelectItem>
                  <SelectItem value="bold">Bold / Disruptive</SelectItem>
                  <SelectItem value="educational">Educational / Informative</SelectItem>
                  <SelectItem value="witty">Witty / Clever</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="emoji-select" className="text-xs font-bold text-muted-foreground uppercase">Emoji Density</Label>
              <Select value={emojiDensity} onValueChange={(val: 'none' | 'low' | 'medium' | 'high') => setEmojiDensity(val)}>
                <SelectTrigger id="emoji-select" className="rounded-xl border-border/30 h-10 bg-background/50 text-xs">
                  <SelectValue placeholder="Select emoji density" />
                </SelectTrigger>
                <SelectContent className="rounded-xl">
                  <SelectItem value="none">None (0%)</SelectItem>
                  <SelectItem value="low">Low (1-2 per post)</SelectItem>
                  <SelectItem value="medium">Medium (Standard)</SelectItem>
                  <SelectItem value="high">High (Expressive)</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="length-select" className="text-xs font-bold text-muted-foreground uppercase">Average Length</Label>
              <Select value={averageLength} onValueChange={(val: 'short' | 'medium' | 'long') => setAverageLength(val)}>
                <SelectTrigger id="length-select" className="rounded-xl border-border/30 h-10 bg-background/50 text-xs">
                  <SelectValue placeholder="Select length" />
                </SelectTrigger>
                <SelectContent className="rounded-xl">
                  <SelectItem value="short">Short (&lt; 150 chars)</SelectItem>
                  <SelectItem value="medium">Medium (Standard)</SelectItem>
                  <SelectItem value="long">Long (&gt; 400 chars)</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="automation-select" className="text-xs font-bold text-muted-foreground uppercase">AI Inbox Mode</Label>
              <Select value={automationMode} onValueChange={(val: 'manual' | 'suggest' | 'autopilot') => setAutomationMode(val)}>
                <SelectTrigger id="automation-select" className="rounded-xl border-border/30 h-10 bg-background/50 text-xs">
                  <SelectValue placeholder="Select automation mode" />
                </SelectTrigger>
                <SelectContent className="rounded-xl font-medium text-xs">
                  <SelectItem value="manual">Manual (On-Demand)</SelectItem>
                  <SelectItem value="suggest">Suggestive (Bubbles)</SelectItem>
                  <SelectItem value="autopilot">Autopilot (Auto-Send)</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Context Areas */}
          <div className="space-y-2">
            <Label htmlFor="audience-textarea" className="text-xs font-bold text-muted-foreground uppercase">Target Audience</Label>
            <Textarea
              id="audience-textarea"
              placeholder="e.g., Local parents of children aged 3-10 looking for holistic preschool and elementary education."
              value={targetAudience}
              onChange={(e) => setTargetAudience(e.target.value)}
              className="min-h-16 rounded-xl border-border/30 bg-background/50 text-xs"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="products-textarea" className="text-xs font-bold text-muted-foreground uppercase">Product or Program Descriptions</Label>
            <Textarea
              id="products-textarea"
              placeholder="e.g., SmartSapp Prep Academy: holistic child-centered learning, robotics club, advanced algebra prep, and competitive swimming."
              value={productDescriptions}
              onChange={(e) => setProductDescriptions(e.target.value)}
              className="min-h-16 rounded-xl border-border/30 bg-background/50 text-xs"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="mission-textarea" className="text-xs font-bold text-muted-foreground uppercase">Mission Statement & Core Values</Label>
            <Textarea
              id="mission-textarea"
              placeholder="e.g., We foster cognitive resilience, creative problem solving, and global stewardship in students within a diverse academic setting."
              value={missionStatement}
              onChange={(e) => setMissionStatement(e.target.value)}
              className="min-h-16 rounded-xl border-border/30 bg-background/50 text-xs"
            />
          </div>

          {/* Words filter lists */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="mandatory-input" className="text-xs font-bold text-muted-foreground uppercase">Mandatory Keywords</Label>
              <Input
                id="mandatory-input"
                placeholder="holistic, enrollment, excellence (comma separated)"
                value={mandatoryKeywordsStr}
                onChange={(e) => setMandatoryKeywordsStr(e.target.value)}
                className="rounded-xl border-border/30 h-10 bg-background/50 text-xs"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="forbidden-input" className="text-xs font-bold text-muted-foreground uppercase">Forbidden Words</Label>
              <Input
                id="forbidden-input"
                placeholder="cheap, guaranteed, low-cost (comma separated)"
                value={forbiddenWordsStr}
                onChange={(e) => setForbiddenWordsStr(e.target.value)}
                className="rounded-xl border-border/30 h-10 bg-background/50 text-xs"
              />
            </div>
          </div>
        </CardContent>

        <CardFooter className="border-t border-border/20 pt-4 pb-4 flex justify-end relative z-10">
          <Button
            type="submit"
            disabled={isSaving}
            className="rounded-xl h-10 px-6 bg-emerald-600 hover:bg-emerald-700 text-white font-semibold text-xs tracking-wider uppercase gap-2 shadow-lg shadow-emerald-500/10 active:scale-[0.97] transition-all"
          >
            {isSaving ? (
              <>
                <Loader2 className="h-3.5 w-3.5 animate-spin" /> Saving...
              </>
            ) : (
              <>
                <Save className="h-3.5 w-3.5" /> Save Guidelines
              </>
            )}
          </Button>
        </CardFooter>
      </Card>
    </form>
  );
}
