/**
 * @fileOverview Canonical Permission Registry & Dependency Resolution (Authorization 2.0)
 *
 * Central source of truth for all fine-grained platform permissions, risk classifications,
 * and Directed Acyclic Graph (DAG) dependency resolution across all 4 operational sections:
 * Operations, Finance, Studios, and Management.
 *
 * ARCHITECTURAL GUIDANCE FOR MAINTAINERS:
 * - Why this exists: Enforces permission consistency and prevents runtime UI crashes caused
 *   by enabling mutate actions (create, edit, delete) without view permissions.
 * - Zero `any` or `any[]` typing.
 * - Always run `resolveDependencies()` on any user-provided schema prior to persistence.
 *
 * @testability Covered in `authorization-services.test.ts`.
 */

import type {
  PermissionsSchema,
  PermissionDefinition,
} from '@/lib/types';

/**
 * 100+ Fine-grained canonical platform permissions with risk classifications and dependency chains.
 */
export const CANONICAL_PERMISSIONS_CATALOG: PermissionDefinition[] = [
  // ============================================================================
  // SECTION 1: OPERATIONS (Campuses, Pipelines, Deals, Tasks, Meetings, etc.)
  // ============================================================================
  {
    id: 'operations.dashboard.view',
    name: 'View Operations Dashboard',
    section: 'operations',
    feature: 'dashboard',
    action: 'view',
    description: 'View operational metrics, daily task ribbons, and performance KPIs.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'dashboard_view',
  },
  {
    id: 'operations.campuses.view',
    name: 'View Campuses / Entities',
    section: 'operations',
    feature: 'campuses',
    action: 'view',
    description: 'View campus and organization operational entity profiles.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'schools_view',
  },
  {
    id: 'operations.campuses.create',
    name: 'Create Campuses / Entities',
    section: 'operations',
    feature: 'campuses',
    action: 'create',
    description: 'Provision new campus locations or business entity units.',
    riskLevel: 'medium',
    dependencies: ['operations.campuses.view'],
  },
  {
    id: 'operations.campuses.edit',
    name: 'Edit Campuses / Entities',
    section: 'operations',
    feature: 'campuses',
    action: 'edit',
    description: 'Update campus attributes, branding, and contact points.',
    riskLevel: 'medium',
    dependencies: ['operations.campuses.view'],
    legacyPermissionId: 'schools_edit',
  },
  {
    id: 'operations.campuses.delete',
    name: 'Delete Campuses / Entities',
    section: 'operations',
    feature: 'campuses',
    action: 'delete',
    description: 'Permanently remove campus locations or business units.',
    riskLevel: 'critical',
    dependencies: ['operations.campuses.view'],
    legacyPermissionId: 'schools_delete',
  },
  {
    id: 'operations.pipeline.view',
    name: 'View Pipeline & Deals',
    section: 'operations',
    feature: 'pipeline',
    action: 'view',
    description: 'Inspect visual Kanban board, deal stages, and prospect summaries.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'prospects_view',
  },
  {
    id: 'operations.pipeline.create',
    name: 'Create Pipeline Deals',
    section: 'operations',
    feature: 'pipeline',
    action: 'create',
    description: 'Create new prospect deals and pipeline opportunities.',
    riskLevel: 'medium',
    dependencies: ['operations.pipeline.view'],
    legacyPermissionId: 'prospects_create',
  },
  {
    id: 'operations.pipeline.edit',
    name: 'Edit Pipeline Deals',
    section: 'operations',
    feature: 'pipeline',
    action: 'edit',
    description: 'Advance deal stages, update deal value, and reassign owners.',
    riskLevel: 'medium',
    dependencies: ['operations.pipeline.view'],
    legacyPermissionId: 'prospects_edit',
  },
  {
    id: 'operations.pipeline.delete',
    name: 'Delete Pipeline Deals',
    section: 'operations',
    feature: 'pipeline',
    action: 'delete',
    description: 'Permanently purge deal opportunities from CRM pipelines.',
    riskLevel: 'high',
    dependencies: ['operations.pipeline.view'],
    legacyPermissionId: 'prospects_delete',
  },
  {
    id: 'operations.tasks.view',
    name: 'View Daily Tasks',
    section: 'operations',
    feature: 'tasks',
    action: 'view',
    description: 'View assigned operational tasks and team checklists.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'tasks_view',
  },
  {
    id: 'operations.tasks.create',
    name: 'Create Tasks',
    section: 'operations',
    feature: 'tasks',
    action: 'create',
    description: 'Create task cards and assign follow-ups to team members.',
    riskLevel: 'low',
    dependencies: ['operations.tasks.view'],
    legacyPermissionId: 'tasks_create',
  },
  {
    id: 'operations.tasks.edit',
    name: 'Edit Tasks',
    section: 'operations',
    feature: 'tasks',
    action: 'edit',
    description: 'Update task status, due dates, priority, and assignees.',
    riskLevel: 'low',
    dependencies: ['operations.tasks.view'],
    legacyPermissionId: 'tasks_edit',
  },
  {
    id: 'operations.tasks.delete',
    name: 'Delete Tasks',
    section: 'operations',
    feature: 'tasks',
    action: 'delete',
    description: 'Delete task records.',
    riskLevel: 'medium',
    dependencies: ['operations.tasks.view'],
    legacyPermissionId: 'tasks_delete',
  },
  {
    id: 'operations.meetings.view',
    name: 'View Meetings & Calendars',
    section: 'operations',
    feature: 'meetings',
    action: 'view',
    description: 'View upcoming Zoom sessions, calendars, and webinar schedules.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'meetings_view',
  },
  {
    id: 'operations.meetings.create',
    name: 'Create & Schedule Meetings',
    section: 'operations',
    feature: 'meetings',
    action: 'create',
    description: 'Schedule webinars, client calls, and automated meeting links.',
    riskLevel: 'medium',
    dependencies: ['operations.meetings.view'],
    legacyPermissionId: 'meetings_create',
  },
  {
    id: 'operations.meetings.edit',
    name: 'Edit Meetings',
    section: 'operations',
    feature: 'meetings',
    action: 'edit',
    description: 'Reschedule meetings, change hosts, and update attendee lists.',
    riskLevel: 'medium',
    dependencies: ['operations.meetings.view'],
    legacyPermissionId: 'meetings_edit',
  },
  {
    id: 'operations.meetings.delete',
    name: 'Cancel & Delete Meetings',
    section: 'operations',
    feature: 'meetings',
    action: 'delete',
    description: 'Cancel scheduled Zoom sessions and purge meeting recordings.',
    riskLevel: 'high',
    dependencies: ['operations.meetings.view'],
    legacyPermissionId: 'meetings_delete',
  },
  {
    id: 'operations.automations.view',
    name: 'View Workflow Automations',
    section: 'operations',
    feature: 'automations',
    action: 'view',
    description: 'Inspect event triggers, webhook nodes, and drip sequences.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'automations_view',
  },
  {
    id: 'operations.automations.create',
    name: 'Create Automations',
    section: 'operations',
    feature: 'automations',
    action: 'create',
    description: 'Author new event-driven workflow automation blueprints.',
    riskLevel: 'high',
    dependencies: ['operations.automations.view'],
    legacyPermissionId: 'automations_create',
  },
  {
    id: 'operations.automations.edit',
    name: 'Edit Automations',
    section: 'operations',
    feature: 'automations',
    action: 'edit',
    description: 'Modify automation action nodes, triggers, delays, and conditions.',
    riskLevel: 'high',
    dependencies: ['operations.automations.view'],
    legacyPermissionId: 'automations_edit',
  },
  {
    id: 'operations.automations.delete',
    name: 'Delete Automations',
    section: 'operations',
    feature: 'automations',
    action: 'delete',
    description: 'Deactivate and delete automation workflows.',
    riskLevel: 'critical',
    dependencies: ['operations.automations.view'],
    legacyPermissionId: 'automations_delete',
  },
  {
    id: 'operations.quickNotes.view',
    name: 'View Company Brain',
    section: 'operations',
    feature: 'quickNotes',
    action: 'view',
    description: 'Read shared workspace knowledge, notes, and ideas.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'quick_notes_view',
  },
  {
    id: 'operations.quickNotes.create',
    name: 'Create in Company Brain',
    section: 'operations',
    feature: 'quickNotes',
    action: 'create',
    description: 'Author new knowledge objects, ideas, notes, and decisions.',
    riskLevel: 'low',
    dependencies: ['operations.quickNotes.view'],
    legacyPermissionId: 'quick_notes_create',
  },
  {
    id: 'operations.quickNotes.edit',
    name: 'Edit Company Brain',
    section: 'operations',
    feature: 'quickNotes',
    action: 'edit',
    description: 'Edit existing knowledge objects, ideas, and decisions.',
    riskLevel: 'low',
    dependencies: ['operations.quickNotes.view'],
    legacyPermissionId: 'quick_notes_edit',
  },
  {
    id: 'operations.quickNotes.delete',
    name: 'Delete from Company Brain',
    section: 'operations',
    feature: 'quickNotes',
    action: 'delete',
    description: 'Delete knowledge objects and ideas.',
    riskLevel: 'low',
    dependencies: ['operations.quickNotes.view'],
    legacyPermissionId: 'quick_notes_delete',
  },
  {
    id: 'operations.intelligence.view',
    name: 'View Operational Intelligence',
    section: 'operations',
    feature: 'intelligence',
    action: 'view',
    description: 'Access AI insights, conversion funnels, and executive reports.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'reports_view',
  },
  {
    id: 'operations.leadIntelligence.view',
    name: 'View Lead Intelligence',
    section: 'operations',
    feature: 'leadIntelligence',
    action: 'view',
    description: 'Inspect lead scores, conversion velocity, and prospect heatmaps.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'operations.salesEffort.view',
    name: 'View Sales Effort Analytics',
    section: 'operations',
    feature: 'salesEffort',
    action: 'view',
    description: 'Inspect outbound rep call activity, touchpoint frequency, and sales cadence.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'operations.knowledgeGraph.view',
    name: 'View Knowledge Graph',
    section: 'operations',
    feature: 'knowledgeGraph',
    action: 'view',
    description: 'Explore visual graph of connected organizational knowledge and entities.',
    riskLevel: 'low',
    dependencies: [],
  },

  // ============================================================================
  // SECTION 2: FINANCE HUB (Invoices, Agreements, Packages, Cycles, Setup)
  // ============================================================================
  {
    id: 'finance.agreements.view',
    name: 'View Contracts & Agreements',
    section: 'finance',
    feature: 'agreements',
    action: 'view',
    description: 'Inspect student/client contracts, agreements, and payment terms.',
    riskLevel: 'medium',
    dependencies: [],
    legacyPermissionId: 'agreements_view',
  },
  {
    id: 'finance.agreements.create',
    name: 'Create Agreements',
    section: 'finance',
    feature: 'agreements',
    action: 'create',
    description: 'Generate new contract agreements for clients and prospects.',
    riskLevel: 'high',
    dependencies: ['finance.agreements.view'],
    legacyPermissionId: 'agreements_create',
  },
  {
    id: 'finance.agreements.edit',
    name: 'Edit Agreements',
    section: 'finance',
    feature: 'agreements',
    action: 'edit',
    description: 'Modify agreement clauses, payment schedules, and terms.',
    riskLevel: 'high',
    dependencies: ['finance.agreements.view'],
    legacyPermissionId: 'agreements_edit',
  },
  {
    id: 'finance.agreements.delete',
    name: 'Void & Delete Agreements',
    section: 'finance',
    feature: 'agreements',
    action: 'delete',
    description: 'Void signed agreements and delete draft contracts.',
    riskLevel: 'critical',
    dependencies: ['finance.agreements.view'],
    legacyPermissionId: 'agreements_delete',
  },
  {
    id: 'finance.invoices.view',
    name: 'View Invoices',
    section: 'finance',
    feature: 'invoices',
    action: 'view',
    description: 'View customer invoices, payment status, and balance receipts.',
    riskLevel: 'medium',
    dependencies: [],
    legacyPermissionId: 'invoices_view',
  },
  {
    id: 'finance.invoices.create',
    name: 'Generate Invoices',
    section: 'finance',
    feature: 'invoices',
    action: 'create',
    description: 'Issue new invoices, charge cards, and request payments.',
    riskLevel: 'high',
    dependencies: ['finance.invoices.view'],
    legacyPermissionId: 'invoices_create',
  },
  {
    id: 'finance.invoices.edit',
    name: 'Edit Invoices',
    section: 'finance',
    feature: 'invoices',
    action: 'edit',
    description: 'Apply discounts, change line items, and adjust tax rates.',
    riskLevel: 'high',
    dependencies: ['finance.invoices.view'],
    legacyPermissionId: 'invoices_edit',
  },
  {
    id: 'finance.invoices.delete',
    name: 'Void & Delete Invoices',
    section: 'finance',
    feature: 'invoices',
    action: 'delete',
    description: 'Void issued invoices and delete financial ledger entries.',
    riskLevel: 'critical',
    dependencies: ['finance.invoices.view'],
    legacyPermissionId: 'invoices_delete',
  },
  {
    id: 'finance.packages.view',
    name: 'View Pricing Packages',
    section: 'finance',
    feature: 'packages',
    action: 'view',
    description: 'View pricing tiers, curriculum packages, and service offerings.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'packages_view',
  },
  {
    id: 'finance.packages.create',
    name: 'Create Packages',
    section: 'finance',
    feature: 'packages',
    action: 'create',
    description: 'Create new billable packages and curriculum tiers.',
    riskLevel: 'medium',
    dependencies: ['finance.packages.view'],
    legacyPermissionId: 'packages_create',
  },
  {
    id: 'finance.packages.edit',
    name: 'Edit Packages',
    section: 'finance',
    feature: 'packages',
    action: 'edit',
    description: 'Update package fees, descriptions, and feature inclusions.',
    riskLevel: 'medium',
    dependencies: ['finance.packages.view'],
    legacyPermissionId: 'packages_edit',
  },
  {
    id: 'finance.packages.delete',
    name: 'Delete Packages',
    section: 'finance',
    feature: 'packages',
    action: 'delete',
    description: 'Remove pricing packages from active catalog.',
    riskLevel: 'high',
    dependencies: ['finance.packages.view'],
    legacyPermissionId: 'packages_delete',
  },
  {
    id: 'finance.cycles.view',
    name: 'View Billing Cycles',
    section: 'finance',
    feature: 'cycles',
    action: 'view',
    description: 'View academic terms, billing periods, and recurring cycle cadences.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'billing_periods_view',
  },
  {
    id: 'finance.cycles.create',
    name: 'Create Billing Cycles',
    section: 'finance',
    feature: 'cycles',
    action: 'create',
    description: 'Define new billing periods and collection milestones.',
    riskLevel: 'medium',
    dependencies: ['finance.cycles.view'],
    legacyPermissionId: 'billing_periods_create',
  },
  {
    id: 'finance.cycles.edit',
    name: 'Edit Billing Cycles',
    section: 'finance',
    feature: 'cycles',
    action: 'edit',
    description: 'Adjust billing cycle date ranges and collection cutoffs.',
    riskLevel: 'medium',
    dependencies: ['finance.cycles.view'],
    legacyPermissionId: 'billing_periods_edit',
  },
  {
    id: 'finance.cycles.delete',
    name: 'Delete Billing Cycles',
    section: 'finance',
    feature: 'cycles',
    action: 'delete',
    description: 'Delete billing periods.',
    riskLevel: 'high',
    dependencies: ['finance.cycles.view'],
    legacyPermissionId: 'billing_periods_delete',
  },
  {
    id: 'finance.billingSetup.view',
    name: 'View Payment Gateways & Banking',
    section: 'finance',
    feature: 'billingSetup',
    action: 'view',
    description: 'Inspect connected Paystack, Stripe, and MoMo merchant accounts.',
    riskLevel: 'high',
    dependencies: [],
    legacyPermissionId: 'billing_setup_view',
  },
  {
    id: 'finance.billingSetup.edit',
    name: 'Configure Payment Gateways',
    section: 'finance',
    feature: 'billingSetup',
    action: 'edit',
    description: 'Update bank payout details, API keys, and payment webhooks.',
    riskLevel: 'critical',
    dependencies: ['finance.billingSetup.view'],
    legacyPermissionId: 'billing_setup_manage',
  },

  // ============================================================================
  // SECTION 3: STUDIOS (Messaging, Portals, Media, Surveys, Forms, Tags, etc.)
  // ============================================================================
  {
    id: 'studios.publicPortals.view',
    name: 'View Public Portals',
    section: 'studios',
    feature: 'publicPortals',
    action: 'view',
    description: 'View public applicant portals and hosted community hubs.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'portals_view',
  },
  {
    id: 'studios.publicPortals.create',
    name: 'Create Public Portals',
    section: 'studios',
    feature: 'publicPortals',
    action: 'create',
    description: 'Launch new public customer portals.',
    riskLevel: 'medium',
    dependencies: ['studios.publicPortals.view'],
    legacyPermissionId: 'portals_create',
  },
  {
    id: 'studios.publicPortals.edit',
    name: 'Edit Public Portals',
    section: 'studios',
    feature: 'publicPortals',
    action: 'edit',
    description: 'Customize public portal themes, branding, and widgets.',
    riskLevel: 'medium',
    dependencies: ['studios.publicPortals.view'],
    legacyPermissionId: 'portals_edit',
  },
  {
    id: 'studios.publicPortals.delete',
    name: 'Delete Public Portals',
    section: 'studios',
    feature: 'publicPortals',
    action: 'delete',
    description: 'Unpublish and take down portals.',
    riskLevel: 'high',
    dependencies: ['studios.publicPortals.view'],
    legacyPermissionId: 'portals_delete',
  },
  {
    id: 'studios.messaging.view',
    name: 'View Messaging Studio',
    section: 'studios',
    feature: 'messaging',
    action: 'view',
    description: 'View WhatsApp, Email, and SMS templates and broadcast histories.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'messaging_view',
  },
  {
    id: 'studios.messaging.create',
    name: 'Create & Send Broadcasts',
    section: 'studios',
    feature: 'messaging',
    action: 'create',
    description: 'Compose message templates and trigger multi-channel campaigns.',
    riskLevel: 'high',
    dependencies: ['studios.messaging.view'],
    legacyPermissionId: 'messaging_create',
  },
  {
    id: 'studios.messaging.edit',
    name: 'Edit Message Templates',
    section: 'studios',
    feature: 'messaging',
    action: 'edit',
    description: 'Edit broadcast templates and dynamic double-brace variables.',
    riskLevel: 'medium',
    dependencies: ['studios.messaging.view'],
    legacyPermissionId: 'messaging_edit',
  },
  {
    id: 'studios.messaging.delete',
    name: 'Delete Message Templates',
    section: 'studios',
    feature: 'messaging',
    action: 'delete',
    description: 'Delete messaging templates.',
    riskLevel: 'medium',
    dependencies: ['studios.messaging.view'],
    legacyPermissionId: 'messaging_delete',
  },
  {
    /**
     * ARCHITECTURAL GUIDANCE FOR MAINTAINERS (Rule 10):
     * Call Centre permissions (Authorization 2.0).
     * Configured as view for all profiles for now, and full access for superadmin.
     */
    id: 'studios.callCentre.view',
    name: 'View Call Centre',
    section: 'studios',
    feature: 'callCentre',
    action: 'view',
    description: 'View outbound call campaigns, queues, scripts, and dialer analytics.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'call_centre_view',
  },
  {
    id: 'studios.callCentre.create',
    name: 'Create Call Campaigns & Scripts',
    section: 'studios',
    feature: 'callCentre',
    action: 'create',
    description: 'Design interactive call scripts and provision dialer campaigns.',
    riskLevel: 'high',
    dependencies: ['studios.callCentre.view'],
    legacyPermissionId: 'call_centre_manage',
  },
  {
    id: 'studios.callCentre.edit',
    name: 'Edit Call Campaigns & Scripts',
    section: 'studios',
    feature: 'callCentre',
    action: 'edit',
    description: 'Update call scripts, dialogue nodes, and campaign configurations.',
    riskLevel: 'medium',
    dependencies: ['studios.callCentre.view'],
    legacyPermissionId: 'call_centre_manage',
  },
  {
    id: 'studios.callCentre.delete',
    name: 'Delete Call Campaigns & Scripts',
    section: 'studios',
    feature: 'callCentre',
    action: 'delete',
    description: 'Permanently remove call scripts and purge dialer queue items.',
    riskLevel: 'high',
    dependencies: ['studios.callCentre.view'],
    legacyPermissionId: 'call_centre_manage',
  },
  {
    id: 'studios.forms.view',
    name: 'View Form Studio',
    section: 'studios',
    feature: 'forms',
    action: 'view',
    description: 'View public intake forms and survey questionnaires.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'forms_view',
  },
  {
    id: 'studios.forms.create',
    name: 'Create Forms',
    section: 'studios',
    feature: 'forms',
    action: 'create',
    description: 'Build new lead intake and onboarding forms.',
    riskLevel: 'medium',
    dependencies: ['studios.forms.view'],
    legacyPermissionId: 'forms_create',
  },
  {
    id: 'studios.forms.edit',
    name: 'Edit Forms',
    section: 'studios',
    feature: 'forms',
    action: 'edit',
    description: 'Modify form fields, conditional logic, and submission triggers.',
    riskLevel: 'medium',
    dependencies: ['studios.forms.view'],
    legacyPermissionId: 'forms_edit',
  },
  {
    id: 'studios.forms.delete',
    name: 'Delete Forms',
    section: 'studios',
    feature: 'forms',
    action: 'delete',
    description: 'Delete intake forms.',
    riskLevel: 'high',
    dependencies: ['studios.forms.view'],
    legacyPermissionId: 'forms_delete',
  },
  {
    id: 'studios.tags.view',
    name: 'View Workspace Tags',
    section: 'studios',
    feature: 'tags',
    action: 'view',
    description: 'Inspect workspace segmentation tag library.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'tags_view',
  },
  {
    id: 'studios.tags.create',
    name: 'Create Tags',
    section: 'studios',
    feature: 'tags',
    action: 'create',
    description: 'Create new taxonomy tags for contact segmentation.',
    riskLevel: 'low',
    dependencies: ['studios.tags.view'],
    legacyPermissionId: 'tags_create',
  },
  {
    id: 'studios.tags.edit',
    name: 'Edit Tags',
    section: 'studios',
    feature: 'tags',
    action: 'edit',
    description: 'Rename tags and update color codes.',
    riskLevel: 'low',
    dependencies: ['studios.tags.view'],
    legacyPermissionId: 'tags_edit',
  },
  {
    id: 'studios.tags.delete',
    name: 'Delete Tags',
    section: 'studios',
    feature: 'tags',
    action: 'delete',
    description: 'Delete tags from workspace taxonomy.',
    riskLevel: 'medium',
    dependencies: ['studios.tags.view'],
    legacyPermissionId: 'tags_delete',
  },
  {
    id: 'studios.media.view',
    name: 'View Media Asset Library',
    section: 'studios',
    feature: 'media',
    action: 'view',
    description: 'Browse uploaded videos, banners, logos, and audio assets.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'media_view',
  },
  {
    id: 'studios.media.create',
    name: 'Upload Media',
    section: 'studios',
    feature: 'media',
    action: 'create',
    description: 'Upload media files to CDN storage.',
    riskLevel: 'medium',
    dependencies: ['studios.media.view'],
    legacyPermissionId: 'media_create',
  },
  {
    id: 'studios.media.delete',
    name: 'Delete Media',
    section: 'studios',
    feature: 'media',
    action: 'delete',
    description: 'Delete files from cloud media storage.',
    riskLevel: 'high',
    dependencies: ['studios.media.view'],
    legacyPermissionId: 'media_delete',
  },
  {
    id: 'studios.qrStudio.view',
    name: 'View QR Code Studio',
    section: 'studios',
    feature: 'qrStudio',
    action: 'view',
    description: 'View dynamic QR campaigns and scan analytics.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'qr_studio_view',
  },
  {
    id: 'studios.qrStudio.create',
    name: 'Generate QR Codes',
    section: 'studios',
    feature: 'qrStudio',
    action: 'create',
    description: 'Generate branded dynamic QR codes with UTM tracking.',
    riskLevel: 'low',
    dependencies: ['studios.qrStudio.view'],
    legacyPermissionId: 'qr_studio_create',
  },
  {
    id: 'studios.verifyStudio.view',
    name: 'View Verification Studio',
    section: 'studios',
    feature: 'verifyStudio',
    action: 'view',
    description: 'Inspect verified applicant badges and identity logs.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'verify_studio_view',
  },
  {
    id: 'studios.verifyStudio.create',
    name: 'Issue Verified Credentials',
    section: 'studios',
    feature: 'verifyStudio',
    action: 'create',
    description: 'Issue signed verification certificates and badges.',
    riskLevel: 'high',
    dependencies: ['studios.verifyStudio.view'],
    legacyPermissionId: 'verify_studio_create',
  },

  {
    id: 'studios.landingPages.view',
    name: 'View Landing Pages',
    section: 'studios',
    feature: 'landingPages',
    action: 'view',
    description: 'View published landing pages, conversion funnels, and page views.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'portals_view',
  },
  {
    id: 'studios.landingPages.create',
    name: 'Create Landing Pages',
    section: 'studios',
    feature: 'landingPages',
    action: 'create',
    description: 'Design and publish new marketing landing pages.',
    riskLevel: 'medium',
    dependencies: ['studios.landingPages.view'],
    legacyPermissionId: 'portals_create',
  },
  {
    id: 'studios.landingPages.edit',
    name: 'Edit Landing Pages',
    section: 'studios',
    feature: 'landingPages',
    action: 'edit',
    description: 'Modify landing page sections, copy, call-to-actions, and SEO metadata.',
    riskLevel: 'medium',
    dependencies: ['studios.landingPages.view'],
    legacyPermissionId: 'portals_edit',
  },
  {
    id: 'studios.landingPages.delete',
    name: 'Delete Landing Pages',
    section: 'studios',
    feature: 'landingPages',
    action: 'delete',
    description: 'Unpublish and permanently delete landing pages.',
    riskLevel: 'high',
    dependencies: ['studios.landingPages.view'],
    legacyPermissionId: 'portals_delete',
  },
  {
    id: 'studios.media.edit',
    name: 'Edit Media Assets',
    section: 'studios',
    feature: 'media',
    action: 'edit',
    description: 'Rename, tag, and organize media library files and folders.',
    riskLevel: 'low',
    dependencies: ['studios.media.view'],
  },
  {
    id: 'studios.flipbooks.view',
    name: 'View Flipbook Studio',
    section: 'studios',
    feature: 'flipbooks',
    action: 'view',
    description: 'Inspect digital flipbook brochures, publications, and reader metrics.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'studios.flipbooks.create',
    name: 'Create Flipbooks',
    section: 'studios',
    feature: 'flipbooks',
    action: 'create',
    description: 'Author new interactive digital flipbooks and brochures.',
    riskLevel: 'medium',
    dependencies: ['studios.flipbooks.view'],
  },
  {
    id: 'studios.flipbooks.edit',
    name: 'Edit Flipbooks',
    section: 'studios',
    feature: 'flipbooks',
    action: 'edit',
    description: 'Update flipbook pages, audio overlays, and interactive hotspots.',
    riskLevel: 'medium',
    dependencies: ['studios.flipbooks.view'],
  },
  {
    id: 'studios.flipbooks.delete',
    name: 'Delete Flipbooks',
    section: 'studios',
    feature: 'flipbooks',
    action: 'delete',
    description: 'Permanently remove flipbook publications.',
    riskLevel: 'high',
    dependencies: ['studios.flipbooks.view'],
  },
  {
    id: 'studios.thumbnails.view',
    name: 'View Thumbnail Studio',
    section: 'studios',
    feature: 'thumbnails',
    action: 'view',
    description: 'Browse generated social badges, banners, and thumbnail presets.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'studios.thumbnails.create',
    name: 'Generate Thumbnails',
    section: 'studios',
    feature: 'thumbnails',
    action: 'create',
    description: 'Generate high-resolution social share and video thumbnails.',
    riskLevel: 'low',
    dependencies: ['studios.thumbnails.view'],
  },
  {
    id: 'studios.thumbnails.edit',
    name: 'Edit Thumbnails',
    section: 'studios',
    feature: 'thumbnails',
    action: 'edit',
    description: 'Adjust thumbnail typography, dimensions, and color schemes.',
    riskLevel: 'low',
    dependencies: ['studios.thumbnails.view'],
  },
  {
    id: 'studios.thumbnails.delete',
    name: 'Delete Thumbnails',
    section: 'studios',
    feature: 'thumbnails',
    action: 'delete',
    description: 'Delete thumbnail graphic assets.',
    riskLevel: 'low',
    dependencies: ['studios.thumbnails.view'],
  },
  {
    id: 'studios.surveys.view',
    name: 'View Surveys',
    section: 'studios',
    feature: 'surveys',
    action: 'view',
    description: 'View customer satisfaction, NPS, and feedback surveys.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'studios.surveys.create',
    name: 'Create Surveys',
    section: 'studios',
    feature: 'surveys',
    action: 'create',
    description: 'Design new multi-step surveys, questionnaires, and polls.',
    riskLevel: 'medium',
    dependencies: ['studios.surveys.view'],
  },
  {
    id: 'studios.surveys.edit',
    name: 'Edit Surveys',
    section: 'studios',
    feature: 'surveys',
    action: 'edit',
    description: 'Modify survey logic, question branches, and response quotas.',
    riskLevel: 'medium',
    dependencies: ['studios.surveys.view'],
  },
  {
    id: 'studios.surveys.delete',
    name: 'Delete Surveys',
    section: 'studios',
    feature: 'surveys',
    action: 'delete',
    description: 'Permanently remove surveys and delete respondent histories.',
    riskLevel: 'high',
    dependencies: ['studios.surveys.view'],
  },
  {
    id: 'studios.docSigning.view',
    name: 'View Document Signing (PDFs)',
    section: 'studios',
    feature: 'docSigning',
    action: 'view',
    description: 'Inspect PDF signing templates, versions, and field placements.',
    riskLevel: 'medium',
    dependencies: [],
    legacyPermissionId: 'studios_view',
  },
  {
    id: 'studios.docSigning.create',
    name: 'Create Signing Templates',
    section: 'studios',
    feature: 'docSigning',
    action: 'create',
    description: 'Upload PDF source documents and define signature fields.',
    riskLevel: 'high',
    dependencies: ['studios.docSigning.view'],
    legacyPermissionId: 'studios_edit',
  },
  {
    id: 'studios.docSigning.edit',
    name: 'Edit Signing Templates',
    section: 'studios',
    feature: 'docSigning',
    action: 'edit',
    description: 'Reposition signature anchors, update variables, and configure routing rules.',
    riskLevel: 'high',
    dependencies: ['studios.docSigning.view'],
    legacyPermissionId: 'studios_edit',
  },
  {
    id: 'studios.docSigning.delete',
    name: 'Delete Signing Templates',
    section: 'studios',
    feature: 'docSigning',
    action: 'delete',
    description: 'Delete PDF signing templates and template versions.',
    riskLevel: 'critical',
    dependencies: ['studios.docSigning.view'],
  },
  {
    id: 'studios.qrStudio.edit',
    name: 'Edit QR Codes',
    section: 'studios',
    feature: 'qrStudio',
    action: 'edit',
    description: 'Update dynamic destination URLs and styling on active QR codes.',
    riskLevel: 'medium',
    dependencies: ['studios.qrStudio.view'],
  },
  {
    id: 'studios.qrStudio.delete',
    name: 'Delete QR Codes',
    section: 'studios',
    feature: 'qrStudio',
    action: 'delete',
    description: 'Deactivate and delete dynamic QR campaigns.',
    riskLevel: 'medium',
    dependencies: ['studios.qrStudio.view'],
  },
  {
    id: 'studios.verifyStudio.edit',
    name: 'Edit Verification Records',
    section: 'studios',
    feature: 'verifyStudio',
    action: 'edit',
    description: 'Update badge attributes and verification expiry dates.',
    riskLevel: 'high',
    dependencies: ['studios.verifyStudio.view'],
  },
  {
    id: 'studios.verifyStudio.delete',
    name: 'Revoke & Delete Credentials',
    section: 'studios',
    feature: 'verifyStudio',
    action: 'delete',
    description: 'Revoke and delete verified identity credentials.',
    riskLevel: 'critical',
    dependencies: ['studios.verifyStudio.view'],
  },

  // ============================================================================
  // SECTION 4: SOCIAL HUB (Dashboard, Composer, Calendar, Inbox, Profiles)
  // ============================================================================
  {
    id: 'social.dashboard.view',
    name: 'View Social Hub Dashboard',
    section: 'social',
    feature: 'dashboard',
    action: 'view',
    description: 'View aggregate social engagement, reach KPIs, and follower growth.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'social.composer.view',
    name: 'View Social Composer',
    section: 'social',
    feature: 'composer',
    action: 'view',
    description: 'View drafted social posts and publishing queues.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'social.composer.create',
    name: 'Compose & Schedule Posts',
    section: 'social',
    feature: 'composer',
    action: 'create',
    description: 'Author new posts and schedule them across connected social platforms.',
    riskLevel: 'medium',
    dependencies: ['social.composer.view'],
  },
  {
    id: 'social.composer.edit',
    name: 'Edit Scheduled Posts',
    section: 'social',
    feature: 'composer',
    action: 'edit',
    description: 'Update copy, media attachments, and scheduling times for queued posts.',
    riskLevel: 'medium',
    dependencies: ['social.composer.view'],
  },
  {
    id: 'social.composer.delete',
    name: 'Cancel & Delete Posts',
    section: 'social',
    feature: 'composer',
    action: 'delete',
    description: 'Cancel scheduled posts and delete published social content.',
    riskLevel: 'high',
    dependencies: ['social.composer.view'],
  },
  {
    id: 'social.calendar.view',
    name: 'View Content Calendar',
    section: 'social',
    feature: 'calendar',
    action: 'view',
    description: 'Inspect multi-channel publishing calendars and editorial schedules.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'social.calendar.create',
    name: 'Plan Calendar Entries',
    section: 'social',
    feature: 'calendar',
    action: 'create',
    description: 'Place placeholders and campaign markers on the social calendar.',
    riskLevel: 'low',
    dependencies: ['social.calendar.view'],
  },
  {
    id: 'social.calendar.edit',
    name: 'Reschedule Calendar Slots',
    section: 'social',
    feature: 'calendar',
    action: 'edit',
    description: 'Drag-and-drop reschedule posts and update calendar dates.',
    riskLevel: 'medium',
    dependencies: ['social.calendar.view'],
  },
  {
    id: 'social.inbox.view',
    name: 'View Social Inbox',
    section: 'social',
    feature: 'inbox',
    action: 'view',
    description: 'Read inbound comments, mentions, and direct messages across social channels.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'social.inbox.create',
    name: 'Reply to Social Messages',
    section: 'social',
    feature: 'inbox',
    action: 'create',
    description: 'Send replies to social comments and direct messages.',
    riskLevel: 'medium',
    dependencies: ['social.inbox.view'],
  },
  {
    id: 'social.inbox.edit',
    name: 'Manage Inbox Conversations',
    section: 'social',
    feature: 'inbox',
    action: 'edit',
    description: 'Assign conversations to team members, tag sentiments, and update ticket status.',
    riskLevel: 'low',
    dependencies: ['social.inbox.view'],
  },
  {
    id: 'social.inbox.delete',
    name: 'Hide & Delete Comments',
    section: 'social',
    feature: 'inbox',
    action: 'delete',
    description: 'Delete comments or hide abusive social responses.',
    riskLevel: 'high',
    dependencies: ['social.inbox.view'],
  },
  {
    id: 'social.accounts.view',
    name: 'View Connected Profiles',
    section: 'social',
    feature: 'accounts',
    action: 'view',
    description: 'View connected Facebook, LinkedIn, Twitter/X, and Instagram handles.',
    riskLevel: 'medium',
    dependencies: [],
  },
  {
    id: 'social.accounts.create',
    name: 'Connect Social Accounts',
    section: 'social',
    feature: 'accounts',
    action: 'create',
    description: 'Authorize new OAuth connections to social media platforms.',
    riskLevel: 'high',
    dependencies: ['social.accounts.view'],
  },
  {
    id: 'social.accounts.edit',
    name: 'Configure Social Accounts',
    section: 'social',
    feature: 'accounts',
    action: 'edit',
    description: 'Update profile permissions, account sync tokens, and posting rules.',
    riskLevel: 'high',
    dependencies: ['social.accounts.view'],
  },
  {
    id: 'social.accounts.delete',
    name: 'Disconnect Social Accounts',
    section: 'social',
    feature: 'accounts',
    action: 'delete',
    description: 'Sever OAuth authorization and remove social handles.',
    riskLevel: 'critical',
    dependencies: ['social.accounts.view'],
  },

  // ============================================================================
  // SECTION 5: WORKSPACE AND USERS (Workforce, Directory, Onboarding, AI, Governance, Identity)
  // ============================================================================
  {
    id: 'workforce.intelligence.view',
    name: 'View User Intelligence',
    section: 'workforce',
    feature: 'intelligence',
    action: 'view',
    description: 'View team productivity metrics, login velocity, and active user analytics.',
    riskLevel: 'medium',
    dependencies: [],
  },
  {
    id: 'workforce.users.view',
    name: 'View Users Hub / Directory',
    section: 'workforce',
    feature: 'users',
    action: 'view',
    description: 'Browse workspace member directory, contact cards, and department assignments.',
    riskLevel: 'medium',
    dependencies: [],
    legacyPermissionId: 'users_view',
  },
  {
    id: 'workforce.users.create',
    name: 'Invite Workspace Members',
    section: 'workforce',
    feature: 'users',
    action: 'create',
    description: 'Invite new team members and dispatch activation links.',
    riskLevel: 'high',
    dependencies: ['workforce.users.view'],
    legacyPermissionId: 'users_create',
  },
  {
    id: 'workforce.users.edit',
    name: 'Edit Member Profiles & Access',
    section: 'workforce',
    feature: 'users',
    action: 'edit',
    description: 'Update department assignments, user titles, and workspace access.',
    riskLevel: 'critical',
    dependencies: ['workforce.users.view'],
    legacyPermissionId: 'users_edit',
  },
  {
    id: 'workforce.users.delete',
    name: 'Remove & Offboard Users',
    section: 'workforce',
    feature: 'users',
    action: 'delete',
    description: 'Remove members from workspace and revoke active access.',
    riskLevel: 'critical',
    dependencies: ['workforce.users.view'],
    legacyPermissionId: 'users_delete',
  },
  {
    id: 'workforce.onboarding.view',
    name: 'View Onboarding Journeys',
    section: 'workforce',
    feature: 'onboarding',
    action: 'view',
    description: 'Track employee onboarding journey progress and step completions.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'workforce.onboarding.create',
    name: 'Create Onboarding Journeys',
    section: 'workforce',
    feature: 'onboarding',
    action: 'create',
    description: 'Design structured multi-stage onboarding roadmaps.',
    riskLevel: 'medium',
    dependencies: ['workforce.onboarding.view'],
  },
  {
    id: 'workforce.onboarding.edit',
    name: 'Edit Onboarding Journeys',
    section: 'workforce',
    feature: 'onboarding',
    action: 'edit',
    description: 'Assign onboarding journey checklists and reorder milestone tasks.',
    riskLevel: 'medium',
    dependencies: ['workforce.onboarding.view'],
  },
  {
    id: 'workforce.onboarding.delete',
    name: 'Delete Onboarding Journeys',
    section: 'workforce',
    feature: 'onboarding',
    action: 'delete',
    description: 'Archive or remove onboarding journey templates.',
    riskLevel: 'high',
    dependencies: ['workforce.onboarding.view'],
  },
  {
    id: 'workforce.commandCenter.view',
    name: 'View AI Command Center',
    section: 'workforce',
    feature: 'commandCenter',
    action: 'view',
    description: 'Inspect live AI agent status, active agent runs, and autonomous tasks.',
    riskLevel: 'high',
    dependencies: [],
  },
  {
    id: 'workforce.commandCenter.edit',
    name: 'Manage AI Command Center',
    section: 'workforce',
    feature: 'commandCenter',
    action: 'edit',
    description: 'Dispatch, pause, or terminate autonomous AI agent processes.',
    riskLevel: 'critical',
    dependencies: ['workforce.commandCenter.view'],
  },
  {
    id: 'workforce.advisor.view',
    name: 'View AI Workforce Advisor',
    section: 'workforce',
    feature: 'advisor',
    action: 'view',
    description: 'View AI workforce planning recommendations and staffing insights.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'workforce.advisor.edit',
    name: 'Apply AI Advisor Plans',
    section: 'workforce',
    feature: 'advisor',
    action: 'edit',
    description: 'Approve and implement AI workforce staffing suggestions.',
    riskLevel: 'high',
    dependencies: ['workforce.advisor.view'],
  },
  {
    id: 'workforce.governance.view',
    name: 'View Governance & Security',
    section: 'workforce',
    feature: 'governance',
    action: 'view',
    description: 'Audit session tokens, password policies, and security compliance scores.',
    riskLevel: 'high',
    dependencies: [],
  },
  {
    id: 'workforce.governance.edit',
    name: 'Configure Security Policies',
    section: 'workforce',
    feature: 'governance',
    action: 'edit',
    description: 'Enforce MFA requirements, IP whitelists, and session timeout thresholds.',
    riskLevel: 'critical',
    dependencies: ['workforce.governance.view'],
  },
  {
    id: 'workforce.crmWorkload.view',
    name: 'View CRM Workload & Transfer',
    section: 'workforce',
    feature: 'crmWorkload',
    action: 'view',
    description: 'Inspect contact portfolio distribution and sales rep account loads.',
    riskLevel: 'medium',
    dependencies: [],
  },
  {
    id: 'workforce.crmWorkload.edit',
    name: 'Execute CRM Workload Transfers',
    section: 'workforce',
    feature: 'crmWorkload',
    action: 'edit',
    description: 'Bulk reassign contacts, deals, and accounts between team members.',
    riskLevel: 'critical',
    dependencies: ['workforce.crmWorkload.view'],
  },
  {
    id: 'workforce.enterpriseIdentity.view',
    name: 'View Enterprise SSO & SCIM',
    section: 'workforce',
    feature: 'enterpriseIdentity',
    action: 'view',
    description: 'Inspect SAML 2.0 / OIDC identity providers and SCIM 2.0 sync endpoints.',
    riskLevel: 'high',
    dependencies: [],
  },
  {
    id: 'workforce.enterpriseIdentity.edit',
    name: 'Configure Enterprise SSO & SCIM',
    section: 'workforce',
    feature: 'enterpriseIdentity',
    action: 'edit',
    description: 'Configure IdP metadata, certificate rotations, and auto-provisioning rules.',
    riskLevel: 'critical',
    dependencies: ['workforce.enterpriseIdentity.view'],
  },
  {
    id: 'workforce.roles.view',
    name: 'View Roles & Permissions Hub',
    section: 'workforce',
    feature: 'roles',
    action: 'view',
    description: 'Inspect organizational roles, access blueprints, and permission matrices.',
    riskLevel: 'high',
    dependencies: [],
  },
  {
    id: 'workforce.roles.edit',
    name: 'Create & Manage Roles',
    section: 'workforce',
    feature: 'roles',
    action: 'edit',
    description: 'Create custom roles, modify permission schemas, and clone industry presets.',
    riskLevel: 'critical',
    dependencies: ['workforce.roles.view'],
  },

  // ============================================================================
  // SECTION 6: MANAGEMENT (Audit, Scoring, Variables, Prompts, Webhooks, API)
  // ============================================================================
  {
    id: 'management.activities.view',
    name: 'View Audit Activities Log',
    section: 'management',
    feature: 'activities',
    action: 'view',
    description: 'Inspect comprehensive immutable audit trail of system events.',
    riskLevel: 'medium',
    dependencies: [],
    legacyPermissionId: 'activities_view',
  },
  {
    id: 'management.leadScores.view',
    name: 'View Lead Scoring Rules',
    section: 'management',
    feature: 'leadScores',
    action: 'view',
    description: 'Inspect rule-based lead qualification weights and engagement scoring tiers.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'management.leadScores.edit',
    name: 'Configure Lead Scoring Rules',
    section: 'management',
    feature: 'leadScores',
    action: 'edit',
    description: 'Update score criteria weights, activity decay factors, and threshold bands.',
    riskLevel: 'medium',
    dependencies: ['management.leadScores.view'],
  },
  {
    id: 'management.messagingSettings.view',
    name: 'View Invitation Messaging Settings',
    section: 'management',
    feature: 'messagingSettings',
    action: 'view',
    description: 'Inspect team invitation email templates and onboarding SMS notices.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'management.messagingSettings.edit',
    name: 'Configure Invitation Messaging',
    section: 'management',
    feature: 'messagingSettings',
    action: 'edit',
    description: 'Customize invitation copy, subject lines, and sender profiles.',
    riskLevel: 'medium',
    dependencies: ['management.messagingSettings.view'],
  },
  {
    id: 'management.fields.view',
    name: 'View Custom Fields & Variables',
    section: 'management',
    feature: 'fields',
    action: 'view',
    description: 'Inspect global template variables and entity custom field definitions.',
    riskLevel: 'low',
    dependencies: [],
    legacyPermissionId: 'fields_view',
  },
  {
    id: 'management.fields.create',
    name: 'Create Custom Fields',
    section: 'management',
    feature: 'fields',
    action: 'create',
    description: 'Define new schema fields for contacts, deals, and campuses.',
    riskLevel: 'medium',
    dependencies: ['management.fields.view'],
    legacyPermissionId: 'fields_create',
  },
  {
    id: 'management.fields.edit',
    name: 'Edit Custom Fields & Variables',
    section: 'management',
    feature: 'fields',
    action: 'edit',
    description: 'Update variable fallback values and field validation rules.',
    riskLevel: 'medium',
    dependencies: ['management.fields.view'],
    legacyPermissionId: 'fields_edit',
  },
  {
    id: 'management.fields.delete',
    name: 'Delete Custom Fields',
    section: 'management',
    feature: 'fields',
    action: 'delete',
    description: 'Delete custom schema attributes.',
    riskLevel: 'high',
    dependencies: ['management.fields.view'],
    legacyPermissionId: 'fields_delete',
  },
  {
    id: 'management.aiPrompts.view',
    name: 'View AI System Prompts',
    section: 'management',
    feature: 'aiPrompts',
    action: 'view',
    description: 'Inspect generative AI prompt blueprints, system instructions, and tone settings.',
    riskLevel: 'medium',
    dependencies: [],
  },
  {
    id: 'management.aiPrompts.create',
    name: 'Create AI Prompts',
    section: 'management',
    feature: 'aiPrompts',
    action: 'create',
    description: 'Author new AI prompt templates for messaging, copilot, and notes summarization.',
    riskLevel: 'medium',
    dependencies: ['management.aiPrompts.view'],
  },
  {
    id: 'management.aiPrompts.edit',
    name: 'Edit AI Prompts',
    section: 'management',
    feature: 'aiPrompts',
    action: 'edit',
    description: 'Tune prompt temperature, few-shot examples, and guardrail constraints.',
    riskLevel: 'high',
    dependencies: ['management.aiPrompts.view'],
  },
  {
    id: 'management.aiPrompts.delete',
    name: 'Delete AI Prompts',
    section: 'management',
    feature: 'aiPrompts',
    action: 'delete',
    description: 'Delete AI prompt templates.',
    riskLevel: 'medium',
    dependencies: ['management.aiPrompts.view'],
  },
  {
    id: 'management.effortRules.view',
    name: 'View Sales Effort Rules',
    section: 'management',
    feature: 'effortRules',
    action: 'view',
    description: 'Inspect sales velocity rules, KPI targets, and activity scorecard thresholds.',
    riskLevel: 'low',
    dependencies: [],
  },
  {
    id: 'management.effortRules.edit',
    name: 'Configure Sales Effort Rules',
    section: 'management',
    feature: 'effortRules',
    action: 'edit',
    description: 'Update call targets, meeting point allocations, and rep performance criteria.',
    riskLevel: 'medium',
    dependencies: ['management.effortRules.view'],
  },
  {
    id: 'management.systemSettings.view',
    name: 'View Organization System Settings',
    section: 'management',
    feature: 'systemSettings',
    action: 'view',
    description: 'Inspect tenant branding, custom domains, and integration configurations.',
    riskLevel: 'high',
    dependencies: [],
  },
  {
    id: 'management.systemSettings.edit',
    name: 'Modify System Settings',
    section: 'management',
    feature: 'systemSettings',
    action: 'edit',
    description: 'Configure tenant identity settings, authentication policies, and API keys.',
    riskLevel: 'critical',
    dependencies: ['management.systemSettings.view'],
    legacyPermissionId: 'system_admin',
  },
  {
    id: 'management.developerApi.view',
    name: 'View Developer API & Keys',
    section: 'management',
    feature: 'developerApi',
    action: 'view',
    description: 'Inspect developer REST API documentation, key IDs, and rate limit telemetry.',
    riskLevel: 'high',
    dependencies: [],
  },
  {
    id: 'management.developerApi.edit',
    name: 'Generate & Manage API Keys',
    section: 'management',
    feature: 'developerApi',
    action: 'edit',
    description: 'Create, rotate, and revoke scoped developer API keys and secret tokens.',
    riskLevel: 'critical',
    dependencies: ['management.developerApi.view'],
  },
  {
    id: 'management.webhooks.view',
    name: 'View Webhooks & Endpoints',
    section: 'management',
    feature: 'webhooks',
    action: 'view',
    description: 'Inspect outbound webhook subscription endpoints and delivery attempt logs.',
    riskLevel: 'medium',
    dependencies: [],
  },
  {
    id: 'management.webhooks.create',
    name: 'Create Webhook Subscriptions',
    section: 'management',
    feature: 'webhooks',
    action: 'create',
    description: 'Register new HTTPS webhook subscriber endpoints with signing secrets.',
    riskLevel: 'high',
    dependencies: ['management.webhooks.view'],
  },
  {
    id: 'management.webhooks.edit',
    name: 'Edit Webhooks',
    section: 'management',
    feature: 'webhooks',
    action: 'edit',
    description: 'Update subscribed event topics, retry schedules, and endpoint URLs.',
    riskLevel: 'high',
    dependencies: ['management.webhooks.view'],
  },
  {
    id: 'management.webhooks.delete',
    name: 'Delete Webhook Endpoints',
    section: 'management',
    feature: 'webhooks',
    action: 'delete',
    description: 'Deactivate and delete outbound webhook configurations.',
    riskLevel: 'high',
    dependencies: ['management.webhooks.view'],
  },
];

export class PermissionRegistryService {
  /**
   * Returns all canonical permission definitions.
   */
  static getAllPermissions(): PermissionDefinition[] {
    return CANONICAL_PERMISSIONS_CATALOG;
  }

  /**
   * Finds a permission definition by coordinate ID (e.g. `operations.campuses.create`).
   */
  static getPermissionById(permissionId: string): PermissionDefinition | undefined {
    return CANONICAL_PERMISSIONS_CATALOG.find((p) => p.id === permissionId);
  }

  /**
   * Filters permissions by section.
   */
  static getPermissionsBySection(section: keyof PermissionsSchema): PermissionDefinition[] {
    return CANONICAL_PERMISSIONS_CATALOG.filter((p) => p.section === section);
  }

  /**
   * Resolves and fixes DAG dependencies in a PermissionsSchema.
   * If `create`, `edit`, or `delete` is enabled, automatically activates `view: true`
   * and marks the parent feature and section as enabled.
   */
  static resolveDependencies(rawSchema: PermissionsSchema): PermissionsSchema {
    const resolved: PermissionsSchema = JSON.parse(JSON.stringify(rawSchema));

    const sections: (keyof PermissionsSchema)[] = [
      'operations',
      'finance',
      'studios',
      'social',
      'workforce',
      'management',
    ];

    sections.forEach((secKey) => {
      const section = resolved[secKey];
      if (!section) return;

      let hasMutateAction = false;

      Object.entries(section.features).forEach(([_featKey, actions]) => {
        if (!actions) return;

        // If any mutate action is enabled, view MUST be true (DAG invariant)
        if (actions.create || actions.edit || actions.delete) {
          actions.view = true;
          hasMutateAction = true;
        }
      });

      // Only auto-enable the section if a mutate action is asserted;
      // preserves operator's explicit section.enabled: false for view-only sets.
      if (hasMutateAction) {
        section.enabled = true;
      }
    });

    return resolved;
  }

  /**
   * Computes risk metrics and capability statistics for a given PermissionsSchema.
   */
  static calculateRiskMetrics(schema: PermissionsSchema): {
    totalActive: number;
    riskBreakdown: { low: number; medium: number; high: number; critical: number };
    capabilitySummary: {
      operations: number;
      finance: number;
      studios: number;
      social: number;
      workforce: number;
      management: number;
    };
  } {
    const riskCounts = { low: 0, medium: 0, high: 0, critical: 0 };
    const capSummary = {
      operations: 0,
      finance: 0,
      studios: 0,
      social: 0,
      workforce: 0,
      management: 0,
    };
    let totalActive = 0;

    for (const def of CANONICAL_PERMISSIONS_CATALOG) {
      const sec = schema[def.section];
      if (!sec || !sec.enabled) continue;

      const feat = sec.features[def.feature];
      if (!feat) continue;

      const actionKey = def.action as keyof typeof feat;
      if (feat[actionKey] === true) {
        totalActive++;
        riskCounts[def.riskLevel]++;
        if (def.section in capSummary) {
          capSummary[def.section as keyof typeof capSummary]++;
        }
      }
    }

    return {
      totalActive,
      riskBreakdown: riskCounts,
      capabilitySummary: capSummary,
    };
  }
}

