/**
 * ARCHITECTURE:
 * Starter Blueprints and Global Templates Data (Creative Studio 2.0 - Phase 5)
 * 
 * Provides canonical initial templates for template marketplace and seeding.
 */

import type { CreativeTemplate } from './creative-types';
import { FORMAT_PRESETS } from './creative-types';

export const STARTER_BLUEPRINTS: CreativeTemplate[] = [
  {
    id: 'tmpl-edu-growth',
    name: 'Education Enrollment Secret',
    description: 'High-converting curiosity framework for school owners, educators, and course creators.',
    category: 'education',
    format: FORMAT_PRESETS.youtube_thumbnail,
    scope: 'global',
    baselineHealthScore: 95,
    backgroundColor: '#064e3b',
    backgroundGradient: {
      type: 'linear',
      angle: 135,
      colors: ['#022c22', '#0f172a'],
    },
    elements: [
      {
        id: 'edu-el-1',
        type: 'text',
        x: 10,
        y: 20,
        width: 80,
        height: 24,
        zIndex: 1,
        text: 'DOUBLE ENROLMENT',
        fontFamily: 'Impact',
        fontSize: 56,
        fontWeight: '900',
        fill: '#34d399',
        textAlign: 'center',
        textStrokeWidth: 3,
        textStrokeColor: '#000000',
        semanticRole: 'headline',
      },
      {
        id: 'edu-el-2',
        type: 'text',
        x: 20,
        y: 50,
        width: 60,
        height: 14,
        zIndex: 2,
        text: 'The 3-step school admissions blueprint',
        fontFamily: 'Inter',
        fontSize: 24,
        fontWeight: 'bold',
        fill: '#ffffff',
        textAlign: 'center',
        semanticRole: 'subtitle',
      },
      {
        id: 'edu-el-3',
        type: 'text',
        x: 35,
        y: 72,
        width: 30,
        height: 10,
        zIndex: 3,
        text: 'VERIFIED FORMULA',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: '900',
        fill: '#000000',
        badgeColor: '#facc15',
        textAlign: 'center',
        semanticRole: 'badge',
      },
    ],
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'tmpl-b2b-saas-hook',
    name: 'SaaS Growth & Conversion',
    description: 'High-contrast conversion layout designed for B2B founders, lead generation campaigns, and demos.',
    category: 'business',
    format: FORMAT_PRESETS.youtube_thumbnail,
    scope: 'global',
    baselineHealthScore: 92,
    backgroundColor: '#0f172a',
    backgroundGradient: {
      type: 'linear',
      angle: 135,
      colors: ['#0f172a', '#1e1b4b'],
    },
    elements: [
      {
        id: 'saas-el-1',
        type: 'text',
        x: 8,
        y: 18,
        width: 65,
        height: 22,
        zIndex: 1,
        text: 'SCALE TO $100K MRR',
        fontFamily: 'Montserrat',
        fontSize: 50,
        fontWeight: '900',
        fill: '#38bdf8',
        semanticRole: 'headline',
      },
      {
        id: 'saas-el-2',
        type: 'text',
        x: 8,
        y: 45,
        width: 60,
        height: 14,
        zIndex: 2,
        text: 'How top tech companies acquire enterprise clients',
        fontFamily: 'Inter',
        fontSize: 22,
        fill: '#94a3b8',
        semanticRole: 'subtitle',
      },
      {
        id: 'saas-el-3',
        type: 'text',
        x: 8,
        y: 68,
        width: 25,
        height: 9,
        zIndex: 3,
        text: 'LIVE WORKSHOP',
        fontFamily: 'Inter',
        fontSize: 13,
        fontWeight: 'bold',
        fill: '#ffffff',
        badgeColor: '#0284c7',
        semanticRole: 'badge',
      },
    ],
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'tmpl-real-estate-luxury',
    name: 'Luxury Showcase & Tour',
    description: 'Elegant golden aesthetic for property tours, premium service launches, and high-ticket offers.',
    category: 'ads',
    format: FORMAT_PRESETS.youtube_thumbnail,
    scope: 'global',
    baselineHealthScore: 94,
    backgroundColor: '#18181b',
    backgroundGradient: {
      type: 'linear',
      angle: 135,
      colors: ['#18181b', '#27272a'],
    },
    elements: [
      {
        id: 're-el-1',
        type: 'text',
        x: 10,
        y: 20,
        width: 80,
        height: 22,
        zIndex: 1,
        text: 'EXCLUSIVE TOUR',
        fontFamily: 'Playfair Display',
        fontSize: 48,
        fontWeight: 'bold',
        fill: '#fbbf24',
        semanticRole: 'headline',
      },
      {
        id: 're-el-2',
        type: 'text',
        x: 10,
        y: 48,
        width: 70,
        height: 14,
        zIndex: 2,
        text: 'Step inside the most prestigious private estates',
        fontFamily: 'Inter',
        fontSize: 22,
        fill: '#f4f4f5',
        semanticRole: 'subtitle',
      },
    ],
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'tmpl-podcast-vip-interview',
    name: 'VIP Guest Spotlight',
    description: 'Split layout optimized for guest face and large bold interview quote.',
    category: 'podcast',
    format: FORMAT_PRESETS.youtube_thumbnail,
    scope: 'global',
    baselineHealthScore: 96,
    backgroundColor: '#09090b',
    backgroundGradient: {
      type: 'linear',
      angle: 135,
      colors: ['#09090b', '#18181b'],
    },
    elements: [
      {
        id: 'pod-el-1',
        type: 'text',
        x: 8,
        y: 18,
        width: 55,
        height: 26,
        zIndex: 1,
        text: '"THIS CHANGED EVERYTHING"',
        fontFamily: 'Impact',
        fontSize: 46,
        fontWeight: '900',
        fill: '#f43f5e',
        semanticRole: 'headline',
      },
      {
        id: 'pod-el-2',
        type: 'text',
        x: 8,
        y: 50,
        width: 50,
        height: 14,
        zIndex: 2,
        text: 'Episode 42 with Special Guest',
        fontFamily: 'Inter',
        fontSize: 22,
        fontWeight: 'bold',
        fill: '#ffffff',
        semanticRole: 'subtitle',
      },
    ],
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];
